### ISSUE TITLE
实时通信服务总览 - 对话（Conversation）的 unique 字段用 REST API 设置的问题

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1011]
目前，使用 REST API 设置 unique 字段，在控制台可以显示出该字段值的变化 true / false，但实际上是无效的。这可能会给某些好奇的开发者带来困惑：用 REST API 尝试改了 unique 字段的值，但是用 SDK 调用对应接口，出现了和预想不一样的结果。

**建议**：把文字说明里的（仅用于内部使用，REST API 设置无效）改成（仅限于各平台 SDK 调用对应接口使用，REST API 设置会显示有值，但是无效）

@sunng87 宁姐，请看一下，还是觉得有点绕。「REST API 设置会显示有值」这个地方比较反直觉...

**Comment by jwfing** [comment]
@BinaryHB 什么意思？这是 bug 吗？

**Comment by ylgrgyq** [comment]
unique 用于避免重复创建成员相同的对话，创建过程使用了 findAndModify 接口，但这个接口只能是实时通信服务内部调用，直接通过 REST API 创建对话时带着 unique 参数也不能起到避免重复创建对话的作用。
@BinaryHB 这里的问题意思是说 REST API 带着  unique 创建对话没有起到避免重复创建对话的作用，但创建出来的对话里 unique 参数为 true 是不合理的对吗？或者说没有描述清楚是吧
