### ISSUE TITLE
iOS 存储文档却少调用云引擎的说明。

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#1031]
https://leancloud.cn/docs/leanstorage_guide-ios.html
https://leancloud.cn/docs/android_guide.html#调用云引擎

**Comment by wujun4code** [comment]
在新版云引擎的文档中有专门的章节介绍 与 客户端 SDK 交互的，只是暂时有些措辞还在修改中，近日发布。

**Comment by jwfing** [comment]
重复了： leancloud/docs#982
