### ISSUE TITLE
[偶发]报错：Redis connection gone from end event

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1075]
这个错误如果是偶尔出现，则没什么问题，如果出现频率很高，则很有可能有问题。
所以需要将 [偶发] 两个字加入到标题中。
https://leancloud.cn/docs/leancache_guide.html#报错_Redis_connection_gone_from_end_event

**Comment by myleslee** [comment]
不论是「偶发」还是「频发」，放在标题中不妥，要放在内容里加以区分。否则在搜索结果中出现多条 [xxxx Redis connection gone from end event]，读者会疑惑。已修改相应内容。
