### ISSUE TITLE
Android 实时通信签名部分

### ISSUE THREAD

**Issue by sunng87** [leancloud/docs#1077]
https://leancloud.cn/docs/realtime_guide-android.html#%E5%AE%9E%E7%8E%B0%E7%AD%BE%E5%90%8D%E5%B7%A5%E5%8E%82

需要增加云引擎范例的链接

另外下面单点登录以 QQ 为例的时候不要出现 w.qq.com 的链接，或者出现不要加链接，如果加链接最好加上 http://noreferer.net/ 包一下

**Comment by wujun4code** [comment]
好，明天修改。
