### ISSUE TITLE
补充：批量数据导入不触发 LeanEngine beforeSave hook

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#1083]
这一点应该分别在云引擎文档和数据导入文档里说明。

**Comment by myleslee** [comment]
@killme2008 数据导入不触发 beforeSave，那会触发 beforeUpdate 吗？还有 afterSave 和 afterUpdate？都跟保存有关。

**Comment by killme2008** [comment]
任何 hook 都不会触发
