### ISSUE TITLE
合并「权限管理使用指南」与「权限管理以及 ACL 快速指南」

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#1088]
对于权限管理与 ACL 设置，目前的入口是「[数据与安全](https://leancloud.cn/docs/data_security.html)」。里面会引用到「[权限管理使用指南](https://leancloud.cn/docs/acl_guide-android.html)」，然后权限管理使用指南里面又会引用到「[权限管理以及 ACL 快速指南](https://leancloud.cn/docs/acl_quick_start-android.html)」，最后「快速指南」里面又回指到「使用指南」。

这样层次太多了，而且最后的「快速指南」文档像是一个 FAQ，可以把部分内容合并到知识库，介绍性的东西都集中到「使用指南」里面来描述为好。

**Comment by wujun4code** [comment]
我不赞成合并。快速指南的意图是让用户知道不用 ACL 和 用 ACL 的区别是很大的，而 权限管理使用指南 给技术指南，是给要用和已经使用的用户做接口以及用法指导的，立意不一。
@myleslee 达叔决定吧。

**Comment by wujun4code** [comment]
还是保留了吧。
