### ISSUE TITLE
在实时通信文档中强调 SDK 的自动重连机制

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1121]
iOS 和 Android 的 IM 的 SDK 都有自动重连机制：
1、调用 open 成功之后，只要没有退出登录，SDK 会一直尝试和服务器保持长连接，此时 AVIMClient 的状态可以通过以下接口得到：
https://leancloud.cn/docs/realtime_guide-ios.html#网络状态响应
https://leancloud.cn/docs/realtime_guide-android.html#网络状态响应
2、调用 close 退出登录成功后，就会断开连接，SDK 也不再试图和服务器保持连接。

现在我见到的用户，很大部分都自己写了断线重连的逻辑，写的不好的就会碰上 1001 错误，而 SDK 已经做了这件事，没必要再自己去写。希望文档里面可以强调一下这个问题。

**Comment by myleslee** [comment]
Closed by #1209
