### ISSUE TITLE
增加 _User 表唯一字段的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1125]
_User 表内 `username`  `email` `mobilePhoneNumber` 这三个字段中的内容是惟一的，不允许重复内容出现。
现在在文档中没有对这件事进行说明，

**Comment by myleslee** [comment]
不唯一的时候，后端返回的错误码是什么?

**Comment by nicecui** [comment]
https://leancloud.cn/docs/error_code.html#_202
https://leancloud.cn/docs/error_code.html#_203
https://leancloud.cn/docs/error_code.html#_214

**Comment by myleslee** [comment]
https://leancloud.cn/docs/leanstorage_guide-ios.html#用户名和密码注册
这里说：
>如果注册不成功，请检查一下返回的错误对象。最有可能的情况是，用户名或电子邮件已经被另一个用户注册，此时可以提示用户尝试用不同的用户名进行注册，**也可以要求用户用 Email 做为用户名注册**。

>这样做的好处是，在用户提交信息时可以将输入的「用户名」默认设置为用户的 Email 地址，以后在用户忘记了密码的情况下，可以使用 LeanStorage 提供的「重置密码」功能。

如果 username 字段用了自己的邮件地址，比如 `docs@leancloud.cn`，那 email 字段我就不能再设成 `docs@leancloud.cn` 了吗？

**Comment by nicecui** [comment]
可以的，只是在该字段这一列是唯一的，其他字段不影响。
