### ISSUE TITLE
向 Rest API 文档补充 /1.1/users/me 

### ISSUE THREAD

**Issue by jysperm** [leancloud/docs#1137]
这个 API 是用来根据 sessionToken 获取用户信息的，JavaScript SDK 的 AV.User.become 用的就是这个，但现在文档上并没有 https://github.com/leancloud/javascript-sdk/blob/master/src/user.js#L670

**Comment by myleslee** [comment]
URL|HTTP|功能
---|---|---
`/1.1/users/me`|GET|根据 [sessionToken](js_guide.html#SessionToken) 获取用户信息

### 已登录的用户信息

用户成功注册或登录后，服务器会返回 sessionToken 并保存在本地，后续请求可以通过传递 sessionToken 来获取该用户信息（如访问权限等）。更多说明请参考 [存储 &middot; sessionToken](js_guide.html#SessionToken)。

```
curl -X GET \
  -H "X-LC-Id: {{appid}}" \
  -H "X-LC-Key: {{appkey}}" \
  -G \
  --data-urlencode 'sessionToken=qmdj8pdidnmyzp0c7yqil91oc' \
  https://api.leancloud.cn/1.1/users/me
```
返回的 JSON 数据：

```
待补充
```
@killme2008 请修订。

**Comment by jysperm** [comment]
Session 是在 `X-LC-Session` 这个头里吧？GET 请求不能发 body 的

**Comment by myleslee** [comment]
@killme2008
