### ISSUE TITLE
iOS 存储，增加 Boolean 查询示例代码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1141]
support 邮箱中来自用户 Issac 的邮件中看到，进行 Boolean 查询时，用户错误地使用了 0 和 1 进行查询。
介于 iOS 的 Bool 确实有些特殊（不是一个对象），建议在文档中增加对 Boolean 查询的示例代码。
```
[query whereKey:@"booleanTest" equalTo:@(YES)];
```

文档位置：
https://leancloud.cn/docs/leanstorage_guide-ios.html#条件查询

**Comment by myleslee** [comment]
Closed by #1209
