### ISSUE TITLE
求补充有关更新时附带查询条件的内容

### ISSUE THREAD

**Issue by jysperm** [leancloud/docs#1142]
需要补充到 Restful API 文档和各 SDK 文档。

目前只有我们的内部文档上有这个功能的介绍： https://github.com/leancloud/paas/issues/808

**Comment by myleslee** [comment]
REST 文档已补充：
- https://leancloud.cn/docs/rest_api.html#按条件更新对象
- https://leancloud.cn/docs/rest_api.html#按条件删除对象

存储 SDK 使用 saveOptions 的相应选项。
- https://leancloud.cn/docs/leanstorage_guide-ios.html#保存选项
- https://leancloud.cn/docs/leanstorage_guide-android.html#保存选项
- https://leancloud.cn/docs/leanstorage_guide-js.html#保存选项

**Comment by myleslee** [comment]
JS 和 iOS 暂不支持 DeleteOption，Update 使用方法待补充。
