### ISSUE TITLE
leanstorage文档的query.whereContainsAll接口描述错误

### ISSUE THREAD

**Issue by dittoyi** [leancloud/docs#1159]
query.whereContainsAll是查询包含的接口，并不是如文档所说的精确匹配，需要在模版中修改一下

**Comment by myleslee** [comment]
https://leancloud.cn/docs/leanstorage_guide-android.html#数组查询

@BinaryHB  请确认一下

**Comment by dittoyi** [comment]
@BinaryHB  举例来说，如果有一个字段的值为数组[1,2,3],有一个为数组[1,2],当用query.whereContainsAll查询包含[1,2]时，会把[1,2]和[1,2,3]都查询出来，而不是如文档所说只匹配到[1,2]

**Comment by myleslee** [comment]
@lbt05 请帮助确认

**Comment by lbt05** [comment]
李伟帮忙确认一下吧。。。

**Comment by lbt05** [comment]
稍等，我确认一下

2016-05-17 9:33 GMT+08:00 烨辰陆 <lbt0506@gmail.com>:

> 李伟帮忙确认一下吧。。。

**Comment by daweibayu** [comment]
确实如此，稍后我修改一下文档，谢谢反馈。

**Comment by wujun4code** [comment]
我来修改。

**Comment by myleslee** [comment]
Closed by #1201
