### ISSUE TITLE
存储文档需要单独介绍一下 sessionToken 

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1163]
- [x] 注册和登录之后会返回 sessionToken
- [x] ACL 判断是根据 http header 包含的 sessionToken 来判断用户的权限的
- [ ] 实例代码在注册和登录之后最好在控制台打印一下 sessionToken，并解释一下过期时间等等

**Comment by myleslee** [comment]
前两条已完成：https://leancloud.cn/docs/leanstorage_guide-ios.html#SessionToken

第三条需要补充。

**Comment by weakish** [comment]
> 实例代码在注册和登录之后最好在控制台打印一下 sessionToken，并解释一下过期时间等等

sessionToken 并没有过期时间，对于 SDK 的使用者来说，sessionToken 其实是透明的。
对于开发者来说，了解 SDK 在本地保存了登录信息，发送请求时会自动附上鉴权信息在绝大部分场景下就足够了，至于通过 sessionToken 实现只是细节。所以就不加这样的语句了。
