### ISSUE TITLE
增加常见问题：为什么 iOS 的离线消息推送了两次？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1175]
大部分原因是这种情况造成的：
Client A 和 B 同在一个对话中，A 调用 openWithCallback 登录了实时通信，在没有调用 closeWithCallback  退出登录的情况下， B 使用同一个设备也调用了 openWithCallback 登录了实时通信。
此时应用退出到后台，其他同在这个对话中的成员向这个对话发送了消息，服务器会给不在线的 A 和 B 发送消息推送，这个设备就会收到两条消息推送。
解决方案：
确保 B 登录时 A 已经调用 closeWithCallback 成功地退出了登录。

**Comment by hanl001** [comment]
已排除该原因，还可能有其他原因吗

**Comment by myleslee** [comment]
@hanl001 
可以到论坛（https://forum.leancloud.cn）中提问。如果使用商用版，请提交工单（https://leanticket.cn）来确认。
