### ISSUE TITLE
[feature]swift sdk 文档编写计划

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1216]
目前 swift sdk 已经 alpha 并且功能如下：

- [x] 存储
- [x] 用户
- [ ] 短信
- [ ] 聊天
- [x] 调用云引擎和云函数
- [x] ACL以及角色
- [ ] 推送

文档初步计划如下按照顺序如下
- [x] /docs/leanstorage-guide-swift.html
- [ ] /docs/setup-guide-swift.html
- [ ] /docs/quick-start-swift.html
- [ ] /docs/acl-guide-swift.html

@tang3w

**Comment by tang3w** [comment]
👍  把 Swift 文档独立出来能避免混淆。待文档发布时，SDK 也一起开放出去。
