### ISSUE TITLE
JS 的应用内搜索不包含 query.whereContains？

### ISSUE THREAD

**Issue by jt-wang** [leancloud/docs#1217]
我想要和 Android 一样，似乎无法实现
```java
// 查询 pubUser 字段的值中包含 "LeanCloud" 字的数据
AVQuery query = new AVQuery("Post");
query.whereContains("pubUser", "LeanCloud");
```
请问有相关办法吗？

**Comment by myleslee** [comment]
请参考 <https://leancloud.cn/docs/leanstorage_guide-js.html#包含查询>。如果不是文档内容有误，使用上的问题请到社区 <https://forum.leancloud.cn> 咨询或提交工单 <https://leanticket.cn/t/leancloud>。
