### ISSUE TITLE
关于如何加强引导用户阅读 ACL 文档的讨论

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1226]
首先确定一点是数据恢复在未来是一定要**收费**的，目前根据和教练，晓丹的讨论如下：
1. 单个应用首次数据恢复是免费
2. 第二次申请数据恢复，会有一封邮件发送给开发者，里面包含了 ACL 的文档以及相关知识点。最主要的是给用户选择如下：阅读 ACL 文档回答相关问题，然后根据回答是否达到一定的分数标准给予免费数据恢复，用户也可以选择直接缴费进行数据恢复。

**Comment by killme2008** [comment]
关联下 https://github.com/leancloud/uluru-platform/issues/2106
