### ISSUE TITLE
无网情况偶现崩溃，空指针问题

### ISSUE THREAD

**Issue by jiweibreadtrip** [leancloud/docs#1246]
看崩溃找到AVPushConnectionManager类中代码
`public void cleanupSocketConnection(int code, String message) {`
`        if(this.socketClient == null || !this.socketClient.isConnecting() && !this.socketClient.isOpen()) {`
`            if(this.socketClient.isClosing()) {`
`                this.socketClient = null;`
`            }`
`        } else {`
`          //...`
`        }`
`    }`

第二行判断socketClient为空，第三行继续调用socketClient.isClosing()空指针崩溃。

**Comment by daweibayu** [comment]
你好，该问题会在本周的版本中修复并发布。另外，技术问题建议到论坛（https://forum.leancloud.cn/） 或者工单系统（https://leanticket.cn/）反馈。

**Comment by daweibayu** [comment]
最迟明天。

**Comment by jiweibreadtrip** [comment]
好的，多谢

**Comment by jiweibreadtrip** [comment]
新版本什么情况了？我看下载里面还是没有？

**Comment by daweibayu** [comment]
我在论坛里新建了一个反馈 https://forum.leancloud.cn/t/topic/9304 ，具体的详情我已经在该反馈中说明，后续如有反馈请到论坛。
