### ISSUE TITLE
增加离线分析对分析结果导出限制的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1247]
https://leancloud.cn/docs/leaninsight_guide.html

由于系统框架和对资源使用的限制，我们的离线分析对于导出的条数有 100000 条的上限，更多的结果是无法导出的。你们如果全表导出可以直接走数据导出的流程，如果查询结果要导出，那么可以分多次查询来操作。

![image](https://cloud.githubusercontent.com/assets/10130959/16067048/406d3a58-32eb-11e6-9e47-14041c55e7a5.png)

**Comment by myleslee** [comment]
https://github.com/leancloud/avfr/pull/769

更新控制台
