### ISSUE TITLE
部分 URL 中有下划线

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1249]
URL 中尽量不要出现「下划线」，因为很容易被下划线覆盖，另外文档 URL 有的是下划线，有的是连接线，非常乱。

不过，这个是细节，酌情考虑调整。

来自用户反馈  http://weibo.com/3969284293/DA46h1tuS

**Comment by wujun4code** [comment]
这个怎么修复？我不太懂。。。

@sparanoid

**Comment by myleslee** [comment]
文件名和链接要改动得太多了。

`leanstorage_guide-ios.md` > 
`leanstorage-guide-ios.md`

`android_push_guide.md` >
`android-push-guide.md`

以后结构大动的时候，包括重新规范文档命名的时候会考虑的。

**Comment by wujun4code** [comment]
先关了吧。

**Comment by sparanoid** [comment]
这个我刚间文档的时候就提到过了，你们说改 URI 之前的链接就失效了……

**Comment by wangxiao** [comment]
😂 这事最好是在用户量不大的时候改，不然以后肯定改不掉了。。。

**Comment by leeyeh** [comment]
之前的可以留着页面跳转到新的。

**Comment by wangxiao** [comment]
这种问题，还是能想到多少就直接改多少吧，也别留中间过渡方法了，不然以后也难以维护。
