### ISSUE TITLE
在所有文檔上增加當前文檔最後的更新時間

### ISSUE THREAD

**Issue by sparanoid** [leancloud/docs#125]
-> https://github.com/leancloud/avfr/issues/176

> freewing99 commented on Jan 13
> 精确到天即可，这个时间在html渲染的时候，读取一下github上 当前的 md 文档最后被更新的时间即可。
> 格式我建议是：2015-01-04 这种国际通俗易懂的即可。
> 
> wangxiao commented on Jan 13
> 好建议，文档更新日期挺重要的。
> 
> sunchanglong commented on Jan 14
> 上次 @sparanoid 还说加一个 文档的 对应 GitHub 地址
> 
> sunchanglong commented on Jan 14
> 如果在加上 一个类似 History 链接呢
> 
> sparanoid commented on Jan 14
> 當時我參考了 Linode 的文檔：
> https://www.linode.com/docs/getting-started
> 
> wangxiao commented on Jan 14
> 行，就是有个「文档更新历史」之类的可查的链接也行。
> 
> sparanoid commented on Jan 14
> 我覺得主要目的是可以讓用戶看到我們的文檔有錯誤或者不足時直接就可以轉到 GitHub 那邊 fork 或者提 issue（大概就是 Linode 那樣）
> 
> wangxiao commented on Jan 14
> 更新时间也很重要的。
> 我之前基于 Google 开发就遇到过类似问题，前一天还支持的接口，第二天发现文档里面找不到了，
> 后来看了下更新日期，才发现晚上更新了文档。
> 文档变成新的接口了，没有更新日期的化，真是死无对证了。
> 
> sunchanglong commented a day ago
> 尝试了利用 GitHub API ，获取更新日期以及相关信息，在 build 文档的时候处理。
> 1 get contents by md dir path.
> 2 遍历每个 md 文件的 commit 信息。（path = md 文件名）
> 可以实现，但是遇到 API rate limit 的问题，build 多次就会出问题。暂时还没有想到其他方案。

**Comment by sparanoid** [comment]
@sunchanglong 我覺得可以試一下 Jekyll＋jekyll-last-modified-at 的方案，現在 https://github.com/leancloud/open 就是這樣實現的

**Comment by sunchanglong** [comment]
是通过读取文件的last modified？而不是读取 github api？

**Comment by sparanoid** [comment]
@sunchanglong 是基於文件的

**Comment by sparanoid** [comment]
Bump, @wujun4code 前段时间也提到过这个

**Comment by myleslee** [comment]
Closed by #1816
