### ISSUE TITLE
文档上部分的源地址链接失效

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1257]
![image](https://cloud.githubusercontent.com/assets/558368/16144012/f3e158cc-34a2-11e6-92d1-a741a3377cdc.png)

如图，这部分的链接失效了，需要排查处理一下。

**Comment by wujun4code** [comment]
这个不是问题，md 是代码生成的，github 上没有是正常的。

**Comment by wangxiao** [comment]
那就把这块链接写死吧，之前是用户反馈想帮我们修改文档，但是不知道在哪修改，这个链接是失效的。

**Comment by wangxiao** [comment]
已修正 https://github.com/leancloud/docs/pull/1262
