### ISSUE TITLE
请问这个文档是用什么插件处理md文件的？

### ISSUE THREAD

**Issue by hezll** [leancloud/docs#1260]
如题，谢谢，整个文档非常漂亮，想知道这个使用什么插件处理转化md成html的？还是自己实现的node.

**Comment by myleslee** [comment]
使用了 https://github.com/treasonx/grunt-markdown
任务定义在 [Gruntfile.js 中](https://github.com/leancloud/docs/blob/master/Gruntfile.js#L124)。
@hezll

**Comment by hezll** [comment]
非常感谢您的回答！
