### ISSUE TITLE
对 AppKey 的说明有误

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#1261]
既然对于移动应用来说 AppKey 无法保密也不是保证安全的手段，那么就不应该被描述为密码，以免引起误解。
![leancloud_ _-_](https://cloud.githubusercontent.com/assets/18527/16216501/d2ef7e2a-379d-11e6-9c23-250bf2a5dfda.png)

**Comment by myleslee** [comment]
Closed by #1265
