### ISSUE TITLE
android sdk 查看用户发件箱的状态数目

### ISSUE THREAD

**Issue by achaly** [leancloud/docs#1267]
sdk中并没有这个接口，请问如何才能实现？

**Comment by daweibayu** [comment]
你好，一般开发中的技术问题请到论坛（https://forum.leancloud.cn）或工单系统（https://leanticket.cn/t/leancloud/）提问，此 repo 不负责提供技术支持服务。以在论坛建立相关条目，请移步 https://forum.leancloud.cn/t/android-sdk/9380
