### ISSUE TITLE
需要补充 React Native 的使用方式

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1289]
收到比较多的反馈，不知道如何在 React Native 中使用 JS SDK，还是需要在官方文档中补充明确的用法。

**Comment by leeyeh** [comment]
其实并没有什么特殊用法。

**Comment by wangxiao** [comment]
![image](https://cloud.githubusercontent.com/assets/558368/16508873/ec1a0478-3f69-11e6-9034-701259f785f2.png)

补充在「SDK 安装指南」里面吧。
