### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1292]
https://leancloud.cn/docs/realtime_guide-ios.html#常见问题

**Comment by myleslee** [comment]
哪里失效？

**Comment by nicecui** [comment]
链接里的黑体全部失效了。。
比如说：
https://leancloud.cn/docs/faq_list.html
![image](https://cloud.githubusercontent.com/assets/10130959/16482875/76abd232-3ee4-11e6-82a3-7cc82851356c.png)
