### ISSUE TITLE
「从网络路径构建文件」文档有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1293]
https://leancloud.cn/docs/leanstorage_guide-ios.html#从网络路径构建文件
https://leancloud.cn/docs/leanstorage_guide-android.html#从网络路径构建文件

「从一个已知的 构建文件也是很多应用的需求，例如，从网页上拷贝了一个图像的链接，希望 SDK 能够读取并且上传到自己的应用内，之后的使用中不必担心原网址失效，而造成 UI 的缺失。」
这句话建议删掉，通过网络路径构建文件，文件不会上传，只是保存了原有的 url 地址外链。

**Comment by myleslee** [comment]
@wujun4code

**Comment by wujun4code** [comment]
这个我跟 天勇确认过，只要按照 ios 的代码执行，先用 getData 然后再调用 save 是可以保存外链图片到我们自己的云端的。

**Comment by wujun4code** [comment]
已删除。
