### ISSUE TITLE
JavaScript SDK AV.Push.send where 参数描述有误、需要有 where 参数的示例

### ISSUE THREAD

**Issue by jysperm** [leancloud/docs#1294]
https://leancloud.cn/api-docs/javascript/symbols/AV.Push.html#.send

按照 API 文档 where 是一个 AV.Query，但文档页面上写的是 String，而且最好在文档里补充一个有 where 参数的示例：

https://leancloud.cn/docs/js_push.html#pushObject_send_options_

**Comment by zhaoxin111** [comment]
竟然是我发现的，oh。。。

**Comment by leeyeh** [comment]
目前建议使用 leancloud-storage 中的 `AV.Push.send` 来发送推送，其中的 where 参数的类型是 `AV.Query`。

https://leancloud.cn/docs/leanstorage_guide-js.html#Push_通知
