### ISSUE TITLE
“SDK 安装” 部分独立为 block

### ISSUE THREAD

**Issue by sdjcw** [leancloud/docs#1295]
因为有的新文档暂时没提供安装文档。

https://github.com/leancloud/docs/blob/07400a9ad43278827ead40b37109444e14a9ca3c/views/leanstorage_guide.tmpl#L49

**Comment by myleslee** [comment]
已加上。但是安装文档是基本文档，新文档没有的话，不应该算 ready。
`{% block section_sdk_setup %}{% endblock %}`
