### ISSUE TITLE
保存对象的例子建议改成 Todo，而不是现在的 TodoFolder

### ISSUE THREAD

**Issue by sdjcw** [leancloud/docs#1296]
存储主文档所有关于 TodoFolder 的部分建议都改成 Todo，这样和其它部分一致。
关系建模指南里有 TodoFolder 没什么问题。
/leanstorage_guide-java.html#保存对象

**Comment by wujun4code** [comment]
改动有点大，几乎所有语言的代码都得修改，而且优先级不高。
