### ISSUE TITLE
关于数组查询的时候使用 whereEqualTo 可能是错的 

### ISSUE THREAD

**Issue by sdjcw** [leancloud/docs#1301]
在 Android 文档中，下面的描述：

> 如果你要查询包含 8:30、9:30 这两个时间点响起闹钟的 Todo，可以使用如下代码：

中使用 whereEqualTo 来判断查询一个指定数组是有问题的，应该换成 whereContainsAll。
其它 sdk 的也看下，根据情况修改。

**Comment by myleslee** [comment]
JS 用的 `query.equalTo('reminders', reminderFilter);`
https://leancloud.cn/docs/leanstorage_guide-js.html#数组查询
@wangxiao 请确认。

PHP 用的 `$query->containsAll("reminders", array($date1, $date2));` 应该没问题。https://leancloud.cn/docs/leanstorage_guide-php.html#数组查询
@juvenn 

Python 用的 `query.equal_to('reminders', [reminder1, reminder2])`。
https://leancloud.cn/docs/leanstorage_guide-python.html#数组查询
@aisk 再确认下。

iOS 应该已经更正了：`[query whereKey:@"reminders" containsAllObjectsInArray:reminders];`
https://leancloud.cn/docs/leanstorage_guide-ios.html#数组查询
@tang3w

**Comment by leeyeh** [comment]
js 中可以使用 equalTo(value) 来匹配数组中的一个元素，或者 containsAll(array) 来匹配数组中的多个元素。所以文档中的例子是有问题的。
