### ISSUE TITLE
[not]containedIn 文档容易引起误解

### ISSUE THREAD

**Issue by leeyeh** [leancloud/docs#1312]
~~containedIn 对应 mongo 中的 $in。~~

~~> 如果想让返回的对象的某个属性匹配多个值，你可以使用 containedIn，提供一个数组就可以了。这样通常可以用单个的查询来获取多个结果，比如 你要查询「LeanCloud官方客服、LeanCloud江宏、滚滚艾买提」三个账号的微博时，可以使用 containedIn（类似 SQL 中的 in 查询）方法来实现：~~

~~https://github.com/leancloud/docs/blob/master/archive/js_guide.md#查询条件~~

~~新文档描述有误：https://leancloud.cn/docs/leanstorage_guide-js.html#包含查询~~

~~iOS 与 Android 的共用的一套模板，可能也不对。~~

建议在文档中单列一节来说 containedIn / notContainedIn，尤其是要与 contains 分开。目前 notContainedIn 在「包含查询」部分内提到，比较容易引起误解。

**Comment by wujun4code** [comment]
我这周来修复这些文档的误解之处。
