### ISSUE TITLE
语言命名空间以及 Object，Query 等对象的命名现状

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1327]
| 语言 | 命名空间 (包名)|对象(AVObject) | 查询(AVQuery) | 关系(AVRelation)|
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Objective-C |   | `AVObject` | `AVQuery` | `AVRelation`
| Java | `com.avos.avoscloud` | `AVObject`  | `AVQuery` | `AVRelation`
| C# | `AVOSCloud` | `AVObject`  | `AVQuery` | `AVRelation`
| PHP | `LeanCloud` | `LeanObject`  | `LeanQuery` | `LeanRelation`
| Swift | `LeanCloud` | `LCObject`  | `Query` | `LCRelation`
| Python | `LeanCloud` | `Object` | `Query` | `Relation`| 
| JavaScript | `leancloud-storage` | `Object` | `Query` | `Relation`|

**Comment by sdjcw** [comment]
PHP 和 Swift 统一一下吧，这个难受死了。

**Comment by jwfing** [comment]
我一直坚持全部统一成 AVObject／AVQuery／AVRelation

**Comment by jwfing** [comment]
@tang3w 能把 Query -> LCQuery 吗？这样至少 Swift 使用者看起来命名是统一的。

**Comment by hjiang** [comment]
在同一个语言之内应该统一。我对于新 SDK 要不要继续沿用 AV 持中立态度，我觉得各有优劣。但是新的 SDK 之间应该统一，不要有的是 LC*，有的是 Lean*，有的没有前缀。namespace 本来就是用来解决命名冲突问题的，所以我觉得新的这些语言都统一成 LeanCloud.Object, LeanCloud.Query, LeanCloud.Relation 是可以的。考虑到 Python 和 JS SDK 已经发布了一段时间，这样对现有用户影响也最小。

**Comment by tang3w** [comment]
@jwfing 主要是 Swift 的 API 设计规范不建议使用前缀，而且几乎所有 Swift 第三方库都没有加前缀的习惯。本来 LCObject 和 LCRelation 等数据类型也不希望加前缀的，就像 Python 和 JavaScript 那样，但由于 Swift 的编译检查比较严格，且 import 时不支持指定外部名称，会导致 LeanCloud 的数据类型跟原生类型冲突时出现二义性，导致编译失败。因此在数据类型上了前缀，其他类遵循 Swift API 设计指南。

**Comment by jwfing** [comment]
@tang3w 明白，所以我觉得咱们一个语言内统一，这样比较合适。另外，我觉得单一语言的规范我们需要尊重，但是如果从产品本身考虑，我们整体上更加统一也是一个很重要的因素，所以有时候我们稍微突破一下命名规范也是值得的（就像 Parse 的 Swift 类命名一样）。
现在，我们把用户使用到的类都加上 LC 前缀，是不是可以呢？

**Comment by tang3w** [comment]
可以，那 Swift SDK 中所有的类都加 LC 吧。

**Comment by wujun4code** [comment]
前缀确定为 LC 了？

**Comment by jwfing** [comment]
就用 LC 吧。

**Comment by wujun4code** [comment]
done.

**Comment by juvenn** [comment]
那 PHP 也跟进调整成 LC 吧？我还是倾向于语言之间尽可能保持一致的。

**Comment by juvenn** [comment]
嗯，刚好第 100 个 issue leancloud/php-sdk#100  😂
