### ISSUE TITLE
Swift 文档折叠到 iOS/OS X 中

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1350]
![image](https://cloud.githubusercontent.com/assets/558368/16754007/30848f88-4821-11e6-8543-52ddeadda295.png)

目前来看，iOS / OS X 并不是一个语言分类，而是系统分类，而 Swift 是个语言，所以放到系统分类中更好些。

另外，随着支持语言的不断增多，导航栏资源就变得稀缺了。部分语言其实用户量很少，文档内容也缺失较多，建议酌情考虑先做折叠处理。

**Comment by wujun4code** [comment]
这个我跟达叔商量过了，ios 下拉列表里面东西太多了，加上 swift 未来是可以面向服务端的，并不是只针对 iOS/ watchOS / tvOS 等客户端，Swift 的用户显然是呈一个上升趋势，未来可以考虑 swift 的客户端合并进入 iOS 而 swift 服务端合并进入云引擎，但是现在 ios 的下拉列表实在太长，暂定就这么做吧。
