### ISSUE TITLE
增加常见问题：如何做到先验证手机号码再注册？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1359]
可以使用 AVUser 的 signUpOrLoginWithMobilePhoneNumber 方法。
https://leancloud.cn/docs/leanstorage_guide-ios.html#手机号码登录
https://leancloud.cn/docs/leanstorage_guide-android.html#手机号码登录
https://leancloud.cn/docs/leanstorage_guide-js.html#手机号码登录

**Comment by wujun4code** [comment]
啥意思？在那里添加常见问题？

**Comment by nicecui** [comment]
https://leancloud.cn/docs/faq_list.html
https://leancloud.cn/docs/faq.html
我来添加吧。

**Comment by wujun4code** [comment]
添加了么？
