### ISSUE TITLE
规范「聊天室」的介绍

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1367]
https://leancloud.cn/docs/realtime_v2.html#对话_Conversation_
这里对聊天室的介绍：
![image](https://cloud.githubusercontent.com/assets/10130959/16869246/8c55842c-4aae-11e6-992c-a90f7e190d5a.png)

这里的「进入聊天界面」「关闭界面」不是我们来做的，我们其实并不涉及前端方面的东西，所以建议修改为：
`其二在于聊天室强调的是在线人数，没有固定成员的概念，所有参与者加入即为成员，断线即为退出。`

**Comment by myleslee** [comment]
@sunng87 @ylgrgyq

**Comment by ylgrgyq** [comment]
这里实际上是在打比方，或者说在举例子，整个段落连起来看实际说的进入聊天界面、关闭界面都说的是这个拿来作为例子的“很多应用使用的聊天室”。我感觉改成加入和断线反而会比较怪，前后不一致。
这个感觉似乎理解上还可以啊，是有用户提到说理解错了？是否有可能提供一下原始出处？我想看看上下文。

**Comment by sunng87** [comment]
我也倾向于保留，这里主要是场景的描述，还不完全是功能的叙述

**Comment by wujun4code** [comment]
既然都保留，那就关了，保留吧。

**Comment by nicecui** [comment]
上下文：
https://forum.leancloud.cn/t/tr-transient/9766
![image](https://cloud.githubusercontent.com/assets/10130959/16938384/d028691e-4da9-11e6-818d-137b010cd45e.png)

**Comment by nicecui** [comment]
@sunng87 @ylgrgyq

**Comment by sunng87** [comment]
如果实在要改，我建议把上面：

> 这里要特别讨论一下单聊、群聊、聊天室、公众号等概念

改为：

> 这里要特别讨论一下单聊、群聊、聊天室、公众号等使用场景

文档在这里实际上还没有开始介绍我们的功能，只是介绍用例。如果这里就写得很接口，又会有另一些用户不知道这里在说什么。

**Comment by wujun4code** [comment]
我已经按照 宁姐的意思改了。
@sunng87 @nicecui

**Comment by nicecui** [comment]
我没有意见
