### ISSUE TITLE
iOS 实时通信单点登录，强制登录的代码有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1372]
https://leancloud.cn/docs/realtime_guide-ios.html#处理登录冲突
#### 原代码如下
init 时没有说明要设置 tag ，open 时没有说明要设置 option
![image](https://cloud.githubusercontent.com/assets/10130959/16905618/6c13befc-4cdb-11e6-8d7c-d5aa53bd08f7.png)

#### 建议修改
```
    self.client = [[AVIMClient alloc] initWithClientId:@"Tom" tag:@"Mobile"];
    
    AVIMClientOpenOption *option = [[AVIMClientOpenOption alloc] init];
    option.force = YES;
    
    [self.client openWithOption:option callback:^(BOOL succeeded, NSError *error) {
        
    }];
```

**Comment by myleslee** [comment]
@wujun4code
