### ISSUE TITLE
自定义域名应该绑定到二级域名

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#1381]
文档里是绑定到顶级域名，这样会导致不必要的跳转。 @kadashu 确认下。
![leancloud_ _-_ _ _node_js](https://cloud.githubusercontent.com/assets/18527/16949301/a6aaf582-4dec-11e6-95fd-5b47d32c246d.png)

**Comment by kadashu** [comment]
刚刚看到 https://leancloud.cn/docs/leanengine_guide-cloudcode.html#主域名 已经更新了
