### ISSUE TITLE
存储文档缺少了 fetch(keys) 的接口

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1392]
该接口表示的是可以在 AVObject#fetch 的时候传入指定的 key，要求返回关联数据的详细内容。

**Comment by weakish** [comment]
又看了一下，现在文档的[同步对象][doc]部分已经讲了通过 keys 参数指定需要刷新的属性

[doc]: https://leancloud.cn/docs/leanstorage_guide-js.html#hash668169761
