### ISSUE TITLE
完善文件删除的示例代码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1437]
问题来源：
https://forum.leancloud.cn/t/topic/10187
https://forum.leancloud.cn/t/avfile/9496

问题描述：
这里两个用户都在本地通过 url new 一个 AVFile 进行删除，然后删不掉服务器中的文件。
建议在文档中完善文件的删除代码，给出从查询到删除的一整套流程，防止再出现同样的问题。
https://leancloud.cn/docs/leanstorage_guide-ios.html#删除
https://leancloud.cn/docs/leanstorage_guide-android.html#删除

**Comment by jwfing** [comment]
通过 url 构造的文件，都没有保存到 AVFile 表里面去，却要做删除，这有点有悖常理啊。
这里要做的不应该是文档里面做修改（不可能任何地方都来全套接口的使用 sample），可改善的地方是我们 SDK 报错提示指向性更明确一点（目前 Swift 的提示信息确实让人看不懂，Android 稍好一些）：

```
只有保存到 LeanCloud 之后的 AVFile 才可以删除（前提是 AVFile 里面 objectId 属性必须存在）
```

**Comment by nicecui** [comment]
@jwfing 
SDK 可以修改，但是 SDK 的报错是在用户错误操作之后产生的提示，我希望用户在写代码时就避免出现这样的错误。

况且这个情况的误操作性太高了：
文档里面有个用户的提问：「如何删除指定URL的图片？」
加上其他三个用户的提问和社区的两个人，说明至少有 6 个人遇到这个问题了。

我们的 AVObject 可以通过 objectId 构造后然后直接 delete 掉的，这可能是用户认为可以 delete url 构造的 AVFile 的原因。

所以还是建议直接在文档中增加说明：
`如果要删除指定 URL 的文件，需要得到该文件对应的有 objectId 的 AVFile，然后调用 delete 方法`

**Comment by wangxiao** [comment]
其实，如果这个操作真的非常多人要用，可以在 SDK 层面封装一个接口歘来，内部就是先 query url，然后再调用 destory 方法删除。

**Comment by nicecui** [comment]
如果 SDK 封装一个接口也不太合适，万一用户要删的不是存在我们服务中的文件呢？
觉得还是在文档中说清楚更合适，然后 SDK 的错误提示更明显一些。

**Comment by nervouna** [comment]
从客户端删除文件不是我们推荐的用法吧？删除文件不是应该客户端标记成待删除，然后跑个定时任务么。允许从客户端直接物理删除文件有安全隐患吧。

**Comment by nicecui** [comment]
最近不再遇到用户有问题了，先关闭了。
