### ISSUE TITLE
添加说明：登录时可以将 email 当做 username 进行登录

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1443]
这个功能没有在文档的任何地方被提到

**Comment by myleslee** [comment]
https://leancloud.cn/docs/leanstorage_guide-ios.html#用户名和密码注册

>开发者也可以要求用户使用 Email 做为用户名注册，即在用户提交信息后将 _User 表中的 username 和 email 字段都设为相同的值，这样做的好处是用户在忘记密码的情况下可以直接使用「邮箱重置密码」功能，无需再额外绑定电子邮件。

**Comment by nicecui** [comment]
这个描述的有些不清楚，即使 email 和 username 不同，将 email 的值传入 username 也可以登录成功。

**Comment by wujun4code** [comment]
@nicecui 这个早两年跟晓丹确认过，这个仅仅是一个 trigger，并不鼓励这么做，所以在文档我没有提及。你可以在 faq 里面加上吧。

**Comment by nicecui** [comment]
我抽时间加一下
