### ISSUE TITLE
代码段中的应用变量未被渲染

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#1444]
https://leancloud.cn/docs/leanengine_webhosting_guide-java.html#使用_Eclipse_启动应用

<img width="564" alt="aaa" src="https://cloud.githubusercontent.com/assets/108758/17519344/2bda8992-5e7e-11e6-93f4-b4da0d29107f.png">

@sunchanglong

**Comment by myleslee** [comment]
@sdjcw 这跟 nunjucks 有没有关系？

**Comment by sdjcw** [comment]
我也不知道这是为何，难道是下面的 `{{appid}}` 两边需要一个空格？

**Comment by sunchanglong** [comment]
在代码段中出现的 appid 应该被引号包围。
比如

```
AVOSCloud.initialize(this, "{{appid}}", "{{appkey}}");
```

具体原因是 这块代码会先做 code pretty，然后angular才开始工作渲染。因为没有引号，做 pretty  的时候会改变 {{appid}} 这种方式

**Comment by sunchanglong** [comment]
如果不能加引号，这块代码段就别做 code表示了，  别用  ``` 包围了。
暂时没找到禁止format特定字符串的方法
