### ISSUE TITLE
And 查询，示例代码不合适

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1450]
https://leancloud.cn/docs/leanstorage_guide-ios.html#AND_查询
https://leancloud.cn/docs/leanstorage_guide-android.html#AND_查询
https://leancloud.cn/docs/leanstorage_guide-js.html#AND_查询

修改示例：

```
AVQuery *lotsOfWins = [AVQuery queryWithClassName:@"Player"];
[lotsOfWins whereKey:@"wins" lessThan:[NSNumber numberWithInt:150]];

AVQuery *fewWins = [AVQuery queryWithClassName:@"Player"];
[fewWins whereKey:@"wins" greaterThan:[NSNumber numberWithInt:5]];

AVQuery *query = [AVQuery andQueryWithSubqueries:[NSArray arrayWithObjects:fewWins,lotsOfWins,nil]];
[query findObjectsInBackgroundWithBlock:^(NSArray *results, NSError *error) {
// 返回赢球次数小于 150 场且大于 5 场的球员
}];
```

**Comment by myleslee** [comment]
为什么「返回 priority 小于 3 并且 status 等于 0 的 Todo」的示例不合适？

为上下文统一，新的示例代码要使用 Todo 的例子。

**Comment by nicecui** [comment]
and 不是这么用的，「返回 priority 小于 3 并且 status 等于 0 的 Todo」直接使用普通的 whereKey 查询就可以，不需要构造两个 Query  and 起来。
and 查询用在对同一个字段需要有两个条件进行约束的时候，比如说「返回 wins 小于 150 场且大于 5 场的球员」

**Comment by nicecui** [comment]
球场的代码只是举个例子说明使用场景，可以换成 Todo 的例子，比如用两个条件约束 createdAt，获取大于 x 日且小于 y 日这两个日期之间建立的 todos。

**Comment by jwfing** [comment]
@nicecui 是有用户反馈说照着我们的文档，写不出 priority 小于 3 且大于 1 的查询吗？我觉得现在的示例也没有问题，就是 AND 可以把两个查询条件拼起来，这两个条件是对同一个属性，还是不同的属性，是对多个属性还是单个属性，这不是关键。

**Comment by nicecui** [comment]
@jwfing 具体的工单在这里：https://leanticket.cn/t/leancloud/2524
工单里面的用户疑惑了，为什么对不同的字段约束有两种写法，到底应该用哪一个呢？既然有简单的写法为什么还要写个 and query 呢？

我当时也疑惑了很久，还问了 @wujun4code ，骏骏想了很久才想起来 and Query 的典型的使用场景是针对同一个字段的。
