### ISSUE TITLE
常见问题链接失效

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1451]
https://leancloud.cn/docs/realtime_guide-ios.html#常见问题
这里面每一个问题的标题都没有链接了：
![image](https://cloud.githubusercontent.com/assets/10130959/17654713/abadfe48-62d8-11e6-9dbc-273d6e52a335.png)

**Comment by myleslee** [comment]
这些标题都太长，出现在左侧导航里会很干扰视线。
如果需要引用，可以在相关的问题上加上 `<a name="anchor_name">`。
