### ISSUE TITLE
ChatKit 文档，补充功能说明：如何生成联系人列表

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1454]
来源：https://leanticket.cn/t/leancloud/2571?show=all

**Comment by myleslee** [comment]
@daweibayu

**Comment by daweibayu** [comment]
ChatKit 其实不包含联系人列表，这个我赶脚写到 ChatKit github 的  readme 上倒是更合理一些。
@wujun4code 你感觉呢？

**Comment by wujun4code** [comment]
我感觉不要让用户在两个地方读文档。就全都加在这上面吧。不包含的话就直接说，默认不包含好友列表这个UI就行了。。。

@daweibayu
