### ISSUE TITLE
cql 查询，增加 AVRelation 示例代码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1455]
文档位置：
https://leancloud.cn/docs/cql_guide.html#关系查询

问题来源：
https://forum.leancloud.cn/t/cql-relation/10372
![image](https://cloud.githubusercontent.com/assets/10130959/17695621/008033ce-63dc-11e6-82a8-168769e5d852.png)

改进建议：
在截图的那条代码中下方增加这样一条说明：

```
如果要找到某一个用户 like 的所有的 post，可以这样查询：
select * from Post where likes=pointer('_User', '51e3a359e4b015ead4d95ddc')
```

**Comment by myleslee** [comment]
文档向上挪几行就已经有类似的例子了：

<img width="916" alt="screen shot 2016-08-18 at 09 21 44" src="https://cloud.githubusercontent.com/assets/108758/17758851/5fe27b3e-6525-11e6-8835-9bf00e4abfd9.png">

这里介绍的是 `related ...  to ...`，再插入 `where likes=pointer...` 感觉会有点混乱。

**Comment by nicecui** [comment]
文档类似的例子查的是 pointer ，AVRelation 和 Pointer 还是有些不一样的。
另外我们的数据模型设计指南里面是给了示例的：
https://leancloud.cn/docs/relation_guide-ios.html#使用_Relation_实现多对多关系
在这个大标题下的「Relation 的查询」第一部分的示例代码，就是 cql 里面缺失的。

**Comment by wujun4code** [comment]
Relation 不推荐使用了，这个 issue 也该过期了。
