### ISSUE TITLE
文档有没有修改自动刷新功能？

### ISSUE THREAD

**Issue by finderL** [leancloud/docs#1458]
有没有编写文档实时浏览器刷新功能

**Comment by wujun4code** [comment]
什么意思？您是说修改文档之后就自动更新线上的文档？还是其他？

**Comment by finderL** [comment]
现在是修改文档后等待脚本执行完成后手动刷新浏览器，有没有自动刷新的功能？

**Comment by myleslee** [comment]
@finderL 这个文档项目有自动刷新的功能：https://github.com/sparanoid/almace-scaffolding
