### ISSUE TITLE
补充说明，AVRelation 的缺陷

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1460]
@paomian 表示 AVRelation 有一些缺陷需要让用户知道，多对多模型建议用户自己维护关联表。
能否请 @wujun4code 将这件事情在文档中讲清楚？

**Comment by wujun4code** [comment]
![image](https://cloud.githubusercontent.com/assets/5119542/19218344/df76281e-8e29-11e6-9cf9-1f51b8616baa.png)
当前已经做了提示，但是呢，不太想暴露过多的细节，比如缺陷在哪里，因为这个一时半会儿也解释不清楚，只有泡面和晓丹能准确地描述，因此经过商量就给个提示就好了，如果红色提示都不看的话，解释太多细节，用户根本也不会看，甚至也看不懂。

**Comment by nicecui** [comment]
数据建模指南里面也提一下吧。
