### ISSUE TITLE
建议实时通信的 iOS 和 Android 的文档将「未读」修改为「未拉取的离线消息」

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1467]
现在 iOS 和 Android 里面的「未读消息」事实上是「未拉取的离线消息」
而 JavaScript 里面的 「未读消息」是真的需要标记为已读的消息

这三个平台的「未读」概念并不一致，建议以实时通信的最新版为准，将 iOS 和 Android 里面的「未读消息」修改为「未拉取的离线消息」。

举例：
SDK 默认的接收机制是：当客户端上线时，离线消息会自动通过长连接发送至客户端。如果开启了「主动拉取离线消息」，消息接收机制变为：当客户端上线时，会收到其参与过的会话的离线消息数量，云端不再主动将离线消息通知发送至客户端，转而由客户端负责主动拉取。

主动获取离线消息，需要在 AVOSCloud 初始化语句后面加上：
……

**Comment by myleslee** [comment]
@sunng87 @ylgrgyq

**Comment by sunng87** [comment]
支持，这里准确来说是未获取的消息。
之前 rest api 的接口已经改为未收取消息：
https://leancloud.cn/docs/realtime_rest_api.html#%E6%9C%AA%E6%94%B6%E5%8F%96%E6%B6%88%E6%81%AF%E6%95%B0

各个 SDK 也更新一下吧
