### ISSUE TITLE
三大平台增加说明：如何调用云引擎预备环境中的函数

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1470]
问题来源：
https://forum.leancloud.cn/t/-receiversoffline-type/10467/4

记得之前文档中有说明，现在都没有了
iOS 的写法是：
[AVCloud setProductionMode:NO];

**Comment by myleslee** [comment]
https://leancloud.cn/docs/leanengine_cloudfunction_guide-php.html#切换云引擎环境

**Comment by myleslee** [comment]
JS 的，地方有点不统一。https://leancloud.cn/docs/leanengine_webhosting_guide-node.html#12c00ff04a421c32ca5eae5a030bd46d

**Comment by nicecui** [comment]
这些位置不太好找呀。。我找了半天没找到直接去问的宜龙。。
甚至用搜索都没搜出来。。

**Comment by myleslee** [comment]
我搜的是 `setproduction`。放在云引擎的文档中是合适的。如果问的人很多的话，可以在 FAQ 里加个链接，不过好像上次看数据 FAQ 的浏览量也不是很高。

**Comment by nicecui** [comment]
faq 的量不是很大，最好是能搜索到，这是 setproduction 的结果，没有一个是上面的链接，这种情况需要搜索优化？
![image](https://cloud.githubusercontent.com/assets/10130959/17882852/9eec12de-6941-11e6-8b81-17ac9a978abd.png)

**Comment by myleslee** [comment]
以上出现的网站托管的链接，用户要是能仔细看里面的内容还是有帮助的。我想可能是因为搜索引擎不对代码块建立索引，所以云函数文档中的内容通过 `setproduction` 是找不到的。
@jwfing 可以确认搜索机制。

**Comment by myleslee** [comment]
确认搜索引擎的确不对代码段进行索引。[workaround] 将切换环境的说明提升至文档靠前的位置。
