### ISSUE TITLE
Javascript 实时通信，on membersjoined 事件文档有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1473]
https://leancloud.cn/docs/realtime_guide-js.html#成员变更接口
在这里全文搜索 `memberjoined`，然后全部替换成 `membersjoined `（少了一个 「s」）

**Comment by myleslee** [comment]
https://leancloud.github.io/js-realtime-sdk/docs/Conversation.html#event:memberjoined
@leeyeh 请核实。API 里也是 `memberjoined `。
