### ISSUE TITLE
在权限管理文档中补充 ACL 默认值、Class 级别 ACL、Object 级别 ACL 的区别和联系

### ISSUE THREAD

**Issue by jysperm** [leancloud/docs#1475]
> 网页上新建class时指定的ACL权限（话说这个有地方可以看到吗？）、选中表=>其他=>权限设置里指定的权限、某条数据的ACL字段权限（可能是网页后台直接修改、或者客户端/服务端代码修改的），这三种权限互相之间的关系是怎样的？文档里貌似没有提到这个。

https://forum.leancloud.cn/t/leancloud/10519/7

**Comment by wangxiao** [comment]
前端也会在创建时增加概念的说明和设置  https://github.com/leancloud/avfr/issues/893

**Comment by myleslee** [comment]
>网页上新建class时指定的ACL权限（话说这个有地方可以看到吗？）

可点 ACL 那一列的「编辑」，可以在默认值里面看到和修改。

>选中表=>其他=>权限设置里指定的权限、某条数据的ACL字段权限（可能是网页后台直接修改、或者客户端/服务端代码修改的），这三种权限互相之间的关系是怎样的？

「网页上新建class时指定的ACL权限」选择的 ACL 会作为新建的 Object 的 ACL 的默认值，当创建 Object 没有指定 ACL 时就会使用这个默认值。

在读写数据的时候，会同时判断 Class 级别 ACL（选中表=>其他=>权限设置里指定的权限）和 Object 级别的 ACL（某条数据的ACL字段权限），只有当两者同时满足的情况下，才会允许这次读写操作。

-----------------------

这样的描述不长，放在前端直接展示给用户没问题，比放在文档中体验要好。

**Comment by wangxiao** [comment]
恩，我是觉得后续文档中过多的说明，应该放到用户操作的具体流程中。很多说明，用户看文档的时候是不在意的，但是真正用到那个功能时，又很重要，所以也放在网站具体流程中比较好。

**Comment by chuyik** [comment]
请问「Class 级别 ACL」 怎么修改？
有个表我想改成「限制写入」，但没找到相关的配置接口和文档。

**Comment by wangxiao** [comment]
@chuyik Class 级别 ACL 设置入口在下图所示位置：
![image](https://cloud.githubusercontent.com/assets/558368/19760051/499103ea-9c62-11e6-991e-57fbe150cdcb.png)

**Comment by myleslee** [comment]
@chuyik 
**权限设置** 里将 **update** 的权限改为「指定用户」，不指定用户和角色，即变为完全只读。

<img width="595" alt="screen shot 2016-10-27 at 07 55 36" src="https://cloud.githubusercontent.com/assets/108758/19760178/fc2377c2-9c62-11e6-9fd3-d12f9f4b5617.png">

文档稍后会补上，目前这样的操作只能在网页控制台里进行，没有对应 REST  API 接口。

**Comment by wujun4code** [comment]
这个 issue 有结论么

**Comment by weakish** [comment]
现在数据和安全中已经有这部分的说明：https://leancloud.cn/docs/data_security.html#hash283315336
