### ISSUE TITLE
安全文档中强调 appKey 是泄露的

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1483]
appKey 是客户端的 key，文档中应该着重强调 appKey 默认就应该认为是泄露的。这点对于 Web 开发者是理所应当的，Web 开发者从安全层面上不信任任何来自于客户端的请求，但是客户端开发者很多都忽视了这点。而安全文档中又着重强调了客户端中，我们有很多安全手段，不易泄露 appKey。

建议强调，默认就应该认为 appKey 是泄露的，而且所有安全防御应该默认不信任客户端。

目前安全文档的第一段，对于 appKey 在客户端的安全性存在误导，用户仍然不会在意 ACL。

**Comment by wujun4code** [comment]
@myleslee

**Comment by jysperm** [comment]
《应用密码学》前言：

> 如果把一封信锁在保险柜中，把保险柜藏在纽约的某个地方，然后告诉你去看这封信。这并不是安全，而是隐藏。相反，如果把一封信锁在保险柜中，然后把保险柜及其设计规范和许多同样的保险柜给你，以便你和世界上最好的开保险柜的专家能够研究锁的装置。 而你还是无法打开保险柜去读这封信，这样才是安全的。

**Comment by wujun4code** [comment]
```
网络世界中总有一些别有用心的人存在，appId 和 appKey 在这里是明文传输的，尽管我们做了很多努力，但还是难保不会泄漏。所以，为了避免这种风险，我们又采用了一种更安全的鉴权方式：
```
原文当中已经存在这段文字，因此这个 issue 可以关闭了。
