### ISSUE TITLE
推送文档中没有测试方式

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#1486]
推送是需要一个测试方式的，但是在文档中没有体现，部分用户搞不清楚如何测试，结果误发得到线上。文档中应补充，据了解，目前有两种测试方式：
- 完全新建一个 App 测试；
- 使用一个特定的 channel，将测试设备加入；

请 Android 和 iOS 补充各自的测试文档。

**Comment by wujun4code** [comment]
https://leancloud.cn/docs/push-guide-leanengine.html

**Comment by wangxiao** [comment]
在这个文档中直接搜索「测试」没有任何内容，建议更直白些，就直接增加一个标题叫做「测试」，或者一个位置写上「如何测试」
