### ISSUE TITLE
云引擎 java 文档中 appid／key 没有被渲染

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#1487]
https://leancloud.cn/docs/leanengine_webhosting_guide-java.html

![screen shot 2016-08-30 at 4 07 13 pm](https://cloud.githubusercontent.com/assets/985038/18081266/ebf1dbd8-6ecb-11e6-8b6b-783a82af60d5.png)

**Comment by myleslee** [comment]
Duplicate #1444
