### ISSUE TITLE
建议详述我们文档中的 schema 结构

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1497]
如果用户只看我们文档中的一个功能，不了解 schema 的话，需要费一番力气才能看懂文档。

举个例子：
我要向用户解释我们的「内嵌查询」，把下面这个链接发给用户：
https://leancloud.cn/docs/leanstorage_guide-js.html#内嵌查询

当用户看到这个文档时，第一反应是：TodoFolder 是什么？Comment 是什么？两者是怎样的关系？
这些背景在这里并没有被解释清楚，我看到这一块时也是通过看代码反推出来的上面的问题。
所以建议在文档中把 schema 讲清楚，不管用户直接跳到哪一部分都能很快地看懂文档。

**Comment by wujun4code** [comment]
这个可以仿照俊文的写的关系建模指南里面，写个 table 如下：
![image](https://cloud.githubusercontent.com/assets/5119542/18190341/ac0f5894-70f4-11e6-90ce-237109559f30.png)

额，要不依然你来写吧？
@nicecui

**Comment by myleslee** [comment]
我原来也有这个想法，我来加吧。

**Comment by myleslee** [comment]
### Todo（待办事项）

字段 |类型|说明
:---|:---|:---
`content`|String|事项的详细内容
`images`|AVFile|与事项相关的图片
`location`|String|处理该事项的地点
`priority`|Number|0 优先级最高，最迫切需要完成。
`reminders`|Array|设置提醒日期和时间
`status`|Number|0 未完成，1 已完成
`title`|String|事项的标题（简短描述）
`views`|Number|该事项被浏览过的次数
`whereCreated`|AVGeoPoint|创建时该事项时的地理定位

### TodoFolder（待办事项的分组）

字段 |类型|说明
:---|:---|:---
`containedTodos`|Relation|所包含的 Todo，与表 `Todo` 相关联。
`name`|String|分组的名称，如家庭、会议。
`owner`|Pointer|分组的所有者或创建人，指向表 `_User` 
`priority`|Number|该分组的优先级别，0 优先级最高。
`tags`|Relation|标签，与表 `Tag` 相关联。

### Comment（待办事项分组的评论）

字段 |类型|说明
:---|:---|:---
`content`|String|评论的内容
`like`|Number|点了赞就是 1，点了不喜欢为 -1，没有做任何操作就为 0（默认）。
`targetTodoFolder`|Pointer|相关联的待办事项分组，指向表 `TodoFolder` 的 objectId

---------------

`targetTodoFolder.targetAVUser`：我理解 `targetAVUser` 只是[举例](https://leancloud.cn/docs/leanstorage_guide-android.html#关联属性查询)，不算 `TodoFolder` 的正式字段。

---------------

### Tag（待办事项分组的标签）

字段 |类型|说明
:---|:---|:---
`name`|String|标签的名称，如今日必做、老婆吩咐、十分重要等。

----------------

应该再加一张图可能更清楚。

**Comment by myleslee** [comment]
<img width="856" alt="screen shot 2016-12-12 at 17 20 00" src="https://cloud.githubusercontent.com/assets/108758/21095910/7d813e54-c098-11e6-8bb2-91cf34405ea6.png">

在文档开始我们说了云端存储的好处是不需要提前定义表结构，所以放在前面不合适。

- 对象
- 文件（没使用 Todo 这样的例子）
- 查询（举例都跟 Todo、TodoFolder、Comment 等相关）

决定放在「查询」的一开始。
