### ISSUE TITLE
REST API 美国节点的示例代码全部用的 api.leancloud.cn，应该是 us-api.leancloud.cn

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1511]
在美国节点中，用户直接进入文档某个模块进行复制粘贴的时候，会直接复制粘贴错误的 api.leancloud.cn。
https://us.leancloud.cn/docs/rest_api.html

**Comment by sunchanglong** [comment]
刚注意到，目前都是写死的。
我需要加个变量处理，找个时间点统一替换下。

**Comment by myleslee** [comment]
#1550
