### ISSUE TITLE
SDK 安装文档应该集中起来，现在 Swift／Java 还单独在外面

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#1517]

**Comment by myleslee** [comment]
建议保持分开。所谓的快速入门，95% 的内容是安装，剩下的内容就是向云端存了一个对象。

详细指南目前都按语言平台归类，而各语言的安装文档又集中放在快速入门里，用 tab 去切换内容，这种不统一也会给用户带来困惑。

快速入门就叫安装指南，拆分放到各自的语言分类之下，这样定位方便，名字也直白准确。

另外，快速入门的正文标题都要从 h4 开始，回归到正常文档以后，内容结构从样式和语义上都跟其他文档一致了。

还有一处要统一的就是应用切换。目前只有使用了 `{{appid}}`  等变量的代码块（主要集中在 start、rest 相关文档）中会出现以下选择：

<img width="339" alt="screen shot 2016-09-08 at 11 01 09" src="https://cloud.githubusercontent.com/assets/108758/18335700/0a533e52-75b4-11e6-85f4-a523b0a94519.png">

但在很多文档的正文中，控制台链接（控制台 > 应用选项……）也会包含变量，部分文档的正文（非代码块）也涉及到了变量，目前是没有办法切换的。建议加一个全局的切换，放在页面的固定位置，如同快速入门这样，也比目前的做法要节省代码和带宽：

<img width="403" alt="screen shot 2016-09-08 at 10 58 07" src="https://cloud.githubusercontent.com/assets/108758/18335702/0c0b784a-75b4-11e6-9a66-b735bb7827b9.png">

总结一下：干掉快速入门，让安装文档与其他文档保持一致的样式、结构和位置。

**Comment by myleslee** [comment]
Closed by #1843
