### ISSUE TITLE
文档中增加「帮助完善文档」

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#153]
可以在各个文档，以及相关文档入口增加「帮助完善文档」这个链接，就是直接链接到文档的 repo。

**Comment by wangxiao** [comment]
@sparanoid 我看文档左侧都有目录，能在目录最后增加这个固定项目么，还有文档首页？

**Comment by sparanoid** [comment]
現在文檔標題右側已經有查看和編輯 GitHub 上對應文件的功能了：

![image](https://cloud.githubusercontent.com/assets/96356/6774077/9cdeb774-d155-11e4-8902-d71ae7f68c5b.png)

**Comment by wangxiao** [comment]
普通用户如果没有 repo 权限，「编辑文件」这个功能点过去能提交修改么？

**Comment by sparanoid** [comment]
沒有權限的話會變成這樣：

![image](https://cloud.githubusercontent.com/assets/96356/6783824/e7840de0-d1b6-11e4-8034-837ac8d30c2e.png)

**Comment by wangxiao** [comment]
好的，谢谢刘老师。
