### ISSUE TITLE
增加国际短信的价格

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1552]
我们已经上线了国际短信，但是对价格还没有明确的文档说明。
https://leancloud.atlassian.net/wiki/pages/viewpage.action?pageId=32014350

**Comment by myleslee** [comment]
以前统一把价格从文档中全部移除，引向官网价格页面了，免得维护两处。另外还要等国际短信 SDK和相关文档完备后再处理价格的事，官网改版后也会加入价格展示。

**Comment by jwfing** [comment]
暂缓吧。
