### ISSUE TITLE
修改 Python API doc 至 readthedocs

### ISSUE THREAD

**Issue by aisk** [leancloud/docs#1554]
新的 API 文档地址： ~~http://leanclooud-python-sdk.readthedocs.io/zh/latest/~~ https://leancloud.readthedocs.io/

**Comment by myleslee** [comment]
leancl【oo】ud-python-sdk.readthedocs.io/zh/latest/
拼写错了

**Comment by aisk** [comment]
好尴尬 ……

**Comment by aisk** [comment]
直接使用 leancloud 这个名称了： https://leancloud.readthedocs.io/

**Comment by aisk** [comment]
:+1:
