### ISSUE TITLE
JavaScript 文件查询示例代码有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1567]
https://leancloud.cn/docs/leanstorage_guide-js.html#文件查询
这里是关联 Pointer 的代码，没有「查询」

**Comment by wujun4code** [comment]
这个部分有点尴尬了。AVUser 不支持查询。ios 文档里面隐藏了这个 block，js 这边有刚需么？
@nicecui

**Comment by nicecui** [comment]
不支持查询还这么关联。。不是把用户往坑里面带么。。

**Comment by wujun4code** [comment]
这个好像是旧版本的遗留问题，AVFile 的查询本身就是一个黑科技

```
let query = new AV.Query('_File');
```

**Comment by nicecui** [comment]
可以在其他场景上把 AVFile 关联上去，然后再查询获得

**Comment by myleslee** [comment]
https://github.com/leancloud/javascript-sdk/blob/next/changelog.md#140-beta0-2016-8-23

AV.Query 支持查询 AV.File

**Comment by shifuchen98** [comment]
实测支持。
