### ISSUE TITLE
去掉部分适配 iOS  9 第三方登录时的文本

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1569]
地址：https://leancloud.cn/docs/sns.html#iOS_9_适配

下图红框里的都可以移除了：

![_2016-09-23_16-52](https://cloud.githubusercontent.com/assets/6046086/18780155/cc054b84-81ae-11e6-90e2-b778797c21a1.png)

**Comment by myleslee** [comment]
已确认，可以删除。
