### ISSUE TITLE
ChatKit iOS 文档，更清晰的说明：胶水函数快速集成

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1578]
https://leancloud.cn/docs/chatkit-ios.html#胶水函数快速集成
这里有很多 invoke 方法，我找了半天也不知道应该通过哪个对象调用，最后还是得去翻源码。
这个需要在文档里面讲清楚。

**Comment by wujun4code** [comment]
@ChenYilong 这个还是需要详细描述一下调用方式

**Comment by shifuchen98** [comment]
ChatKit iOS 已下线。
