### ISSUE TITLE
顶部导航栏增加 Python 相关部分

### ISSUE THREAD

**Issue by aisk** [leancloud/docs#158]

**Comment by wangxiao** [comment]
这个问题我和大龙在看，目前顶部的导航较多，考虑设计一个比较好的分类方式。

目前结论：

![image](https://cloud.githubusercontent.com/assets/558368/6830100/a77d155a-d352-11e4-98c5-7f75073f83ec.png)

**Comment by jwfing** [comment]
能不能按照功能（存储、消息、统计、其他）作为第一级分类、平台/语言作为第二级分类来组织文档？要是一个只使用部分功能的用户（譬如说要找到 Push or 短信 API），目前的结构就比较麻烦。现在的文档和 https://leancloud.cn/features/ 对应不起来。

**Comment by wangxiao** [comment]
讨论之后，觉得按功能还是比较好的，再考虑一下。

**Comment by wangxiao** [comment]
又讨论了下，暂时按照上图去修改，后续看下使用感受。

按照功能非的问题：
* 这种方式更适合对系统熟悉的人，按照功能查找更方便些；
* 如果真的是想通过语言去系统学习 LeanCloud，可能按照语言更合适；

当然，现在也有问题：
* 如果按照功能去找，并不是很方便；
* 文档过多，分类较乱；

**Comment by wangxiao** [comment]
https://github.com/leancloud/docs/pull/171
