### ISSUE TITLE
存储文档中 fetchWhenSave 的解释有误

### ISSUE THREAD

**Issue by leeyeh** [leancloud/docs#1623]
https://leancloud.cn/docs/leanstorage_guide-objc.html#同步对象

其中在 fetch 的例子之后提到「如果需要在保存或更新之后让本地数据自动与云端保持一致，可以使用 fetchWhenSave」。但是根据 #1622 fetchWhenSave 并不等价于在一个请求中完成 save + fetch。

**Comment by jwfing** [comment]
fetchWhenSave 就是 save+fetch 啊，如果结果不是这样，就是 bug 了。

**Comment by sdjcw** [comment]
fetchWhenSave 只会返回本地修改**属性**的最新值，而不是整个对象的最新值。

应用场景是高并发情况，你递增一个字段时，操作成功后，数据库最新的值可能不是你现有值 +1，所以通过 fetchWhenSave 可以拿到服务器最新的值

文档需要修改。

**Comment by jwfing** [comment]
如果 server 端改成更新所有值，代价会大很多吗？如果用户的第一直觉就是更新整个 object，那么我们最好就提供符合预期的结果，这样就不需要专门来解释了。

**Comment by myleslee** [comment]
@nervouna @killme2008 需要再讨论下。

**Comment by nervouna** [comment]
理论上是应该符合用户的直觉，但是这样的改动很可能导致以前在使用这个方法的用户拿到不符合预期的结果。所以我的看法是应当纠正文档里的说法。

**Comment by killme2008** [comment]
fetchWhenSave 是原子的，他获取的是更新后的最新值，如果你再去 fetch 查询一次，那不一定是最新的，特别 id 分配这种情况。
