### ISSUE TITLE
JavaScript quick start severely outdated

### ISSUE THREAD

**Issue by nervouna** [leancloud/docs#1659]
[JavaScript SDK quick start](https://leancloud.cn/docs/start.html)提供的 av-min.js 还是 1.2.1 版本的。

**Comment by leeyeh** [comment]
这个是手动更新的，我看看能不能搞成动态的

**Comment by myleslee** [comment]
象 jQuery 那样换成 `av-min-latest.js` 如何？

**Comment by myleslee** [comment]
负责人目前时间有限，还未有计划。先悬着。
