### ISSUE TITLE
实时通信增加说明： m 字段为空的 conversation 会在 1 年后自动删除

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1672]
用户遇到的问题：
https://forum.leancloud.cn/t/topic/11514

和 @sunng87 沟通后发现，m 字段为空的 conversation 会在 1 年后自动删除，不需要用户再手动操作。
这个功能可以写到文档里面。

对应的文档：
https://leancloud.cn/docs/realtime_v2.html

**Comment by sunng87** [comment]
看到 #1673 的修改，里面实际上已经有了关于 updatedAt 超过一年没有更新会自动删除的说明，我建议不要再针对 m 字段专门说明了。 conversation 过期删除是由于没有更新触发 updatedAt 字段增加而导致的，并非是由于 m 为空。

**Comment by nicecui** [comment]
之前文档里面实际上已经有了关于 updatedAt 超过一年没有更新会自动删除的说明。
这个说明在哪儿？

**Comment by myleslee** [comment]
https://leancloud.cn/docs/realtime_guide-android.html#对话的有效期 @nicecui

**Comment by nicecui** [comment]
我根据用户的问题再思考一下，这个 issue 先关闭。
