### ISSUE TITLE
REST API 对数组的查询，增加多个包含的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1677]
我记得之前文档里面有写：
有一个字段类型是 Array，同时查询出这个 Array 包含 A 的或包含 B 或包含 C 的数据，是有一个方法的。
现在怎么消失了？

**Comment by myleslee** [comment]
`whereKey:containedIn:` 可查询包含不同值的对象。它接受数组，可实现用单一查询来代替多个查询。

``` objc
// 找出 “LeanCloud官方客服”，“LeanCloud江宏”，“滚滚艾买提” 三个账号的微博帖子
NSArray *names = [NSArray arrayWithObjects:@"LeanCloud官方客服",
                                           @"LeanCloud江宏",
                                           @"滚滚艾买提",
                                           nil];
[query whereKey:@"pubUser" containedIn:names];
```

相反，要让查询不包含某些值的对象，则用 `whereKey:notContainedIn:` ：

``` objc
// 找出除 “LeanCloud官方客服”，“LeanCloud江宏”，“滚滚艾买提” 三个账号以外的其他人的微博帖子
NSArray *names = [NSArray arrayWithObjects:@"LeanCloud官方客服",
                                           @"LeanCloud江宏",
                                           @"滚滚艾买提",
                                           nil];
[query whereKey:@"pubUser" notContainedIn:names];
```


@nicecui 是这个吗？

**Comment by nicecui** [comment]
对，是这个。

**Comment by nicecui** [comment]
REST API 里面也需要提供一下示例：
https://leancloud.cn/docs/rest_api.html#对数组的查询

**Comment by myleslee** [comment]
文档中提过 $in 的用法，只是没有归于「对数组的查询」里面。为阅读顺畅，再按上下文增加一个例子。
<img width="886" alt="screen shot 2016-11-24 at 17 19 18" src="https://cloud.githubusercontent.com/assets/108758/20592779/697dfaa0-b26a-11e6-9534-f9dec4890faf.png">
