### ISSUE TITLE
增加说明：一个开发者账号最多创建 50 个应用，一个应用最多创建 300 个 class

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1686]
https://leancloud.cn/docs/dashboard_guide.html

**Comment by myleslee** [comment]
建议把这些明显的限制放在界面上直接展示出来，请 @nervouna 在新版中考虑下。

这些限制信息隐藏在文档中，要靠用户自己去挖掘或是让支持人员引导才能知晓，体验不好。
这样文档站点也不会越来越臃肿。

**Comment by nervouna** [comment]
谢谢，这些信息我其实以前都不知道。已经记录下来，会想办法加进去。
