### ISSUE TITLE
通过REST API如何限制只向安卓设备推送消息？

### ISSUE THREAD

**Issue by lhongda** [leancloud/docs#1692]
调用REST API中的通知推送push API时，总是出现如下提示：

{"code":1,"error":"The iOS certificate file is expired or disabled."}

仔细翻阅文档并没找到如何限制只向安卓设备发送推送消息的说明。
通过data内的数据限制也不行：

"data": {
          "android": {
            "title": "测试POST推送"
            "alert": "LeanCloud 向您问好！"
          }

**Comment by ylgrgyq** [comment]
您好，上述提示的原因是您推送中 prod 参数指明的证书或者正式版证书过期了，为了避免使用已知的过期证书发推送占用资源，我们在收到请求的时候一方面会检查 prod 指明的证书(没有 prod 则默认检查正式环境证书)是否过期，如果发现过期并且 query 条件查出的目标设备中可能存在 iOS 设备，就直接拒绝本次推送。

所以，避免上述问题的方法一个是将过期证书替换掉，或者是在 query 条件中通过 deviceType 字段明确指定 _Installation 表中设备类型为非 iOS 设备来发推送。比如将目标设置为 android，就是 deviceType: "android"。

这里我们文档有疏漏的地方，会立即做补充。谢谢指出。

**Comment by myleslee** [comment]
#1694
