### ISSUE TITLE
把 LeanChat-iOS 换成 ChatKit-OC

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1695]
把下图中的 LeanChat 换成 [ChatKit-OC](https://github.com/leancloud/ChatKit-OC)。

![image](https://cloud.githubusercontent.com/assets/6046086/20479751/52fffb18-b01a-11e6-9f04-4544642cfc74.png)

**Comment by myleslee** [comment]
`realtime_guide-ios.html` 已更名为 
`realtime_guide-objc.html`，但仍然可以访问。

应该在部署时清理掉，方案正在讨论。

**Comment by myleslee** [comment]
Closed by #1702
