### ISSUE TITLE
修改 429 错误码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1707]
通过 REST API 上传的限制在 SDK 里面没有限制，用户在 REST API 里面触发了这些限制之后，看到这里的文档，就会希望我们能为他提高并发。事实上并发不需要提升，只要换用 SDK 就可以了。
这里应该把错误码的解释更明确一些，让用户知道原因。

https://leancloud.cn/docs/error_code.html#_429
![image](https://cloud.githubusercontent.com/assets/10130959/20586381/61667ea4-b23e-11e6-85c4-bec69740b7e6.png)

https://leancloud.cn/docs/rest_api.html#文件
![image](https://cloud.githubusercontent.com/assets/10130959/20586403/8ab10eb4-b23e-11e6-9b3e-add348507453.png)

**Comment by myleslee** [comment]
如果就是想用 REST API 不用 SDK 的话，还是得找我们提升吧？

**Comment by nicecui** [comment]
是的。不过 REST API 的限制我们不会提升。
可以看下丰老师刚才回复的一封邮件（上传活动图像到LeanCloud失败），里面对 REST API 的限制不会提升有说明。

**Comment by nicecui** [comment]
这个问题还是有些复杂。
把 REST API 上传文件的限流和并发限制返回的错误码区分开应该是比较合适的。

**Comment by nicecui** [comment]
https://github.com/leancloud/uluru-platform/issues/2938
