### ISSUE TITLE
在移动版上折叠顶部导航和文档目录

### ISSUE THREAD

**Issue by nervouna** [leancloud/docs#1712]
否则会有严重的可用性问题

**Comment by wujun4code** [comment]
@sparanoid

**Comment by nervouna** [comment]
文档目录会随着当前阅读章节展开，在手机屏幕上会造成页面跳跃。

**Comment by nervouna** [comment]
有个选择是在移动版上不显示目录。

**Comment by fuchenshi** [comment]
可以考虑移动端目录不展开，只显示一级目录，因为二级和以后的目录是永远无法被看到的：

1. 如果在页面顶部点击某个一级目录项，会直接跳转到正文的那个地方，而非展开目录；
2. 在浏览正文的过程中是看不到目录的，而且页面的滚动还会导致目录的自动展开和折叠，使得页面跳动。
