### ISSUE TITLE
ChatKit-OC 聊天界面滑动返回但是不返回消息列表界面又重新回到聊天界面

### ISSUE THREAD

**Issue by ShunzhiTang** [leancloud/docs#1714]
聊天界面滑动返回但是不返回消息列表界面又重现回到聊天界面 ， 键盘没有隐藏也没有和底部的输入框合并
![5828a7db-e308-4200-95ab-e79c55cac014](https://cloud.githubusercontent.com/assets/14285513/20618386/a87a980c-b329-11e6-973c-4166a75ea0a5.png)

**Comment by myleslee** [comment]
请到 https://github.com/leancloud/ChatKit-OC/issues/193 进行后续讨论：
