### ISSUE TITLE
去掉文档里所有与 relation 相关的描述

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1748]
不然就是一波波的用户往里跳。比如：https://forum.leancloud.cn/t/javascript-skip/12362/8

文档的位置，比如有：
https://leancloud.cn/docs/relation_guide-android.html#使用_Relation_实现多对多关系

其他的地方请 @wujun4code 一并检查。

**Comment by BinaryHB** [comment]
https://leanticket.cn/t/leancloud/4124 又有个用户跳坑

relation 都去掉吧

**Comment by BinaryHB** [comment]
Android 这里还有：https://leancloud.cn/docs/relation-guide.html#使用_Relation_实现多对多关系

**Comment by myleslee** [comment]
https://leancloud.cn/docs/relation-guide.html#使用_Relation_实现一对多关系

这个用去吗？

**Comment by BinaryHB** [comment]
需要的。文档就不要提到 relation 建模。

我们无法杜绝用户把 relation 关系用在 100 个数据以上的情况，即使文档这些写了：https://leancloud.cn/docs/relation-guide.html#选择_Pointer_或_Relation_的依据

一旦用在 100 条以上的 relation 数据上，就会出现查询时，返回数据的排序失效。

**Comment by wujun4code** [comment]
我做直播之前一直想着隐藏掉算了，但是我在建模那里详细描述了什么情况下可以使用 Relation 什么情况下请不要使用 Relation，我觉得还是应该让用户自己选择，这部分我们已经加了说明不推荐，但是老用户以及一些高端用户是可以使用的。

**Comment by nervouna** [comment]
> 高端用户是可以使用的

出于这个目的的话，在 SDK API docs 里体现就够了吧

**Comment by nervouna** [comment]
这个后来有结论吗？现在各个 SDK 的数据存储开发指南里都有关于 `Relation` 的描述。

> 我们已经加了说明不推荐，但是老用户以及一些高端用户是可以使用的。

@wujun4code 如果是这个思路的话，可能只需要用一句话提及 `Relation` 然后链接到各自的 SDK API Doc？

**Comment by BinaryHB** [comment]
是的。文档里不要对 relation 进行任何的讲解，一句话带过就好了。不然用户会很自然地去用 relation。
