### ISSUE TITLE
明确「自定义离线消息」和 receiversOffline 的关系

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1749]
在客户端「自定义离线消息」会触发 receiversOffline 吗？
在什么场景下应该使用 receiversOffline？什么情况下要在客户端「自定义离线消息」？
相关：
https://leancloud.cn/docs/realtime_guide-objc.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%A6%BB%E7%BA%BF%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9

**Comment by sunng87** [comment]
还是会触发的，有的时候那个 hook 不仅仅是用来定义推送内容
