### ISSUE TITLE
数据存储所有运行环境的文档在显著位置增加如何开启 debug log

### ISSUE THREAD

**Issue by sdjcw** [leancloud/docs#1754]
方便用户排查问题

**Comment by tang3w** [comment]
示例代码:

Objective-C SDK: `[AVOSCloud setAllLogsEnabled:YES];`
Java / Android SDK: `AVOSCloud.setDebugLogEnabled(true);`

这个 API 主要针对 Native SDK，可以在存储文档的开始添加以下描述（草稿）：

> 在应用开发阶段，您可以开启 SDK 的调试日志。开启后，SDK 会把一些调试信息（例如网络请求、错误消息等）打印到 IDE 的日志窗口中。请调用以下接口来打开调试日志：
>
> `[AVOSCloud setAllLogsEnabled:YES]; // iOS`
> `AVOSCloud.setDebugLogEnabled(true); // Android`

@leancloud/docs-editor

**Comment by leeyeh** [comment]
Node 中设置环境变量 `DEBUG=leancloud*`
浏览器中设置 localStorage `localStorage.setItem('debug', 'leancloud*');`

**Comment by tang3w** [comment]
@leeyeh JavaScript SDK 开启调试日志后，会打印哪些信息？网络请求会已 curl 的形式打印出来吗？

**Comment by leeyeh** [comment]
日志是这个样子的：

**Comment by leeyeh** [comment]
https://github.com/leancloud/js-realtime-sdk#开启调试模式

实时通讯的调试模式也是类似，但是日志会更加的 verbose，一般我会根据具体问题让用户启用特定的 filter。
