### ISSUE TITLE
[improvement] AV.Role 优化建议

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1774]
## Role 对象自身的 ACL 优化

AV.Role 在初始化的时候它有两个参数,以 js 为例

```js
class Role extends Object {

constructor: function constructor(name, acl) {
      if (_.isString(name)) {
        AV.Object.prototype.constructor.call(this, null, null);
        this.setName(name);
      } else {
        AV.Object.prototype.constructor.call(this, name, acl);
      }
      if (acl === undefined) {
        var defaultAcl = new AV.ACL();
        defaultAcl.setPublicReadAccess(true);
        if (!this.getACL()) {
          this.setACL(defaultAcl);
        }
      } else if (!(acl instanceof AV.ACL)) {
        throw new TypeError('acl must be an instance of AV.ACL');
      } else {
        this.setACL(acl);
      }
    }
   }
```
如果不传入 ACL ，SDK 会做自动设置一个默认值：所有人不可写，所有人可读

但实际上这种行为下，创建出来的 Role 根本不可用。
因此个人认为可以在调用父类(Object) 的 save 方法之前，做一下检测，首先需要检测 ACL 是否是可用的：

### 客户端 SDK 创建的 Role 不可以是所有人都不可写
因为如此做这个 Role 存在本身就没意义，而且用户一旦存储了这种数据会产生困惑，不可用（除了控制台或者用 master key 更新）但是又存储成功了。关于 master key 更新 Role 这种行为我们需要在云引擎文档上让用户加以区分行为类型，比如用户确实有一种需求是只允许 master key 来修改某一个 SA 角色下属的用户，这个完全是可以云引擎自己的默认行为，客户端 SDK 创建这种 Role 本质上没什么意义。

### 也不可以是所有人都可写
假设用户需要一个所有人都不可写的 Role `A`，那我们就换一种思路进行如下改造：

1. 创建一个 `B` Role，然后它自身的 ACL 是某一个 SA 用户可写，其他人可读
2. 创建角色 `A` ，指定 A 的 ACL 是 B 可写，所有人可读
3. 让当前 App 下的所有用户都拥有 B 的角色

这样做，即可以满足用户需求，因为 A 这个角色所有人都可以改（因为所有人都拥有角色 B ，而 B 角色拥有针对 A 修改的 ACL 权限），又可以增加 App 自身的安全性（没有登录的用户不可修改 A）。

## 语义化 API 接口
现在 User 里面已经有一个接口叫做 getRoles 了，它返回的不再是一个 Relation，而直接返回了 Role 的数组，因此个人认为加上语义化的接口更有好处：

```js
role.grant( AV.User[] | AV.Role[] )// 向当前角色 users 和 roles 这两个字段里面添加 AV.User[] | AV.Role[]
role.deny( AV.User[] | AV.Role[] ) //  当前角色从 users 和 roles 这两个字段里面删除参数里面包含的 AV.User[] | AV.Role[]

// 均是实例方法
```

这样做的好处：
 1. 再次降低用户理解 Relation 的难度，并且可以逐步淡化 Relation 的概念
 2. 用户使用起来更接近客户端行为的自身的含义，便于使用

##  Role#save 修改如下

```js
    public save() {
        if (!this.ACL) throw new Error('Role must have a ACL.');

        if (this.ACL.getPublicWriteAccess()) {
            throw new Error('can NOT set Role.ACL public write access in true.');
        }

        if (!(this.ACL.findWriteAccess() && AVClient.inLeanEngine)){
            throw new Error('can NOT set Role.ACL write access in closed.');
        }

        return super.save();
    }
```

**Comment by leeyeh** [comment]
>但实际上这种行为下，创建出来的 Role 根本不可用。

不是很理解，具体展开说一下？

此外，Userg#getRoles 返回的不是 relation，是 roles。

**Comment by wujun4code** [comment]
@leeyeh 
1. 所有人都不可改-这个 Role 只有云引擎在使用 master 的情况下才可以使用，否则相当于这就是死数据，因此这种需求只应该存在于云引擎的 master key 运行环境下。所以，当前 js sdk 处理默认 ACL 应该是云引擎 SDK 的默认行为

**Comment by tang3w** [comment]
我对 SDK 验证 Role 的 ACL 没有意见，但要明确 SDK 中对非法情况的行为，是拒绝保存还是告警。我建议拒绝保存。我对语义化 API 保持中立，倾向使用 add / remove 等 SDK 现有的谓词来命名。

**Comment by nicecui** [comment]
没有太理解，现在 Role 和 Relation 之间的关系遇到什么问题了吗？这个 issue 是想要优化 role 还是想要淡化 relation ？

**Comment by wujun4code** [comment]
> 没有太理解，现在 Role 和 Relation 之间的关系遇到什么问题了吗？这个 issue 是想要优化 role 还是想要淡化 relation ？
第一是现在的 Role 的保存之前没有做 ACL 的检测需要加上；
第二是就是要淡化 Relation；

**Comment by wujun4code** [comment]
鉴于我们的用户普遍对 ACL 不会用，这个还是关了吧。。大部分用户还都是仅仅关注功能，安全的问题是意识，不是功能。。
