### ISSUE TITLE
规范文档排版

### ISSUE THREAD

**Issue by sparanoid** [leancloud/docs#179]
@leancloud/developers 

文档这个 repo 在创建初期的时候，由于多人撰写导致排版、格式很不规范，我统一使用了 [vinta/paranoid-auto-spacing](https://github.com/vinta/paranoid-auto-spacing) 用来自动规范排版。这个 lib 的主要功能就是在应该有空格的地方加上空格，让文档总体上看起来舒服一些

但这并不是一个完美的解决方案

比如我们的文档中经常会有全角／半角标点用错：

> LeanCloud平台提供了一个移动App的完整后端解决方案,我们的目标是完全消除写 后端代码和维护服务器的必要性.
>
> 我们的 JavaScript SDK 基于流行的 Backbone.js 框架.它与已经存在的 Backbone程序是兼容的,只需要在你的代码中做出一点点改变,我们的最小化 配置,让你很快地用在LeanCloud上使用JavaScript和HTML5.

又或者名词大小写不规范的情况出现：

> 公开AVAnalytics.h头文件，osx可以使用统计功能了。
> …
> 在LeanCloud上你可以为你的每一个移动应用创建一个App,每一个App都有它专属 的App id和App key.你在LeanCloud上的账户可以容纳多个App.对每一个应用你都 可以部署不同的版本到测试或生产环境.

单纯的选择自动排版，只会让我们和贡献者继续忽略这些细节，所以从现在开始，我 [禁用掉了](https://github.com/leancloud/docs/commit/58588d02777c6c9f1b9259dc3d66eeef14a91917) `pangu.page_spacing();`，这样各位可以明显的看出来哪些文档还有排版问题，希望各位可以在今后的修改中陆续完善现有文档的排版、并将这个传统保持下去

谢谢大家

下面是有用的链接：

- 我们的文案规范：[open.avoscloud.com/copywriting-style-guide.html](http://open.avoscloud.com/copywriting-style-guide.html)
- 文案排版指北：[sparanoid/chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)
- 一些其他团队的排版／写作风格标准：[khowarizmi/Style-Guidelines](https://github.com/khowarizmi/Style-Guidelines)

**Comment by sunng87** [comment]
有没有现成的格式检查的库，我们可以集成到 travis-ci 里去，对每次提交做一次自动的检查

**Comment by sparanoid** [comment]
完全現成的似乎沒有，但是有類似的實現不知道有沒有幫助：

https://github.com/sparanoid/chinese-copywriting-guidelines#%E5%B7%A5%E5%85%B7
