### ISSUE TITLE
各 SDK 文档里对 in 查询没有提及

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#1790]
比如 Python 的 `contained_in`

**Comment by nervouna** [comment]
前两天社区里有人提这个问题。其实 [API 文档里有](https://leancloud.readthedocs.io/zh_CN/latest/#leancloud.Query.contained_in)，但是现在文档的展示结构导致 API 文档没人看。

**Comment by nervouna** [comment]
#1874 也是同样的问题。API doc 里面也是有的（虽然是英文）。

**Comment by weakish** [comment]
现文档中已包含相关内容
