### ISSUE TITLE
存储文档中关于 notContainedIn 的错误

### ISSUE THREAD

**Issue by aisk** [leancloud/docs#1791]
链接： https://leancloud.cn/docs/leanstorage_guide-js.html#%E6%95%B0%E7%BB%84%E6%9F%A5%E8%AF%A2

其中的描述 `notContainedIn` 是用来做数组「不包含」的查询。单实际上 `notContainedIn` 是用来查询单个字段不在结果中的查询。

**Comment by myleslee** [comment]
<img width="972" alt="screen shot 2016-12-30 at 21 49 55" src="https://cloud.githubusercontent.com/assets/108758/21566040/f89edba6-ced9-11e6-9fae-0c7ff247cba1.png">

https://leancloud.github.io/javascript-sdk/docs/AV.Query.html#notContainedIn

API 文档里是 array，记得我也测过用 array 是通过的

**Comment by aisk** [comment]
查询的值可以是 array，但是查询的值应该是「非 array」字段，比如如下的表：

```json
{objectID: "1", name: "foo"}
```

做如下的查询：

```js
AV.Query('ClassName').notContainedIn('name', 'foo')
```

**Comment by myleslee** [comment]
好像是自适应。

<img width="411" alt="screen shot 2016-12-31 at 10 25 16" src="https://cloud.githubusercontent.com/assets/108758/21575336/df6c4d66-cf43-11e6-9f06-4688577ffad5.png">
<img width="483" alt="screen shot 2016-12-31 at 10 25 55" src="https://cloud.githubusercontent.com/assets/108758/21575337/df97c3b0-cf43-11e6-9f4b-c7bdec8c96f9.png">

http://myleslee.jsplay.avosapps.com/wit/edit?html,js,console
