### ISSUE TITLE
sdk 安装也应该区分语言以及平台

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#1802]

**Comment by myleslee** [comment]
<img width="865" alt="a" src="https://cloud.githubusercontent.com/assets/108758/22645833/0f2e37d0-eca4-11e6-8b66-97c99bbb3174.png">
<img width="890" alt="b" src="https://cloud.githubusercontent.com/assets/108758/22645838/11c67f20-eca4-11e6-93fa-0b783ba5975f.png">

还是保持原来的结构，点进去再选择语言，挺清晰的。

<img width="769" alt="screen shot 2017-02-06 at 20 48 11" src="https://cloud.githubusercontent.com/assets/108758/22647634/a1dbd37c-ecad-11e6-9094-38080b0ed5b4.png">
