### ISSUE TITLE
补充服务器时间

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1836]
我记得之前文档里面有相应的内容，好像在某次去掉了？
https://forum.leancloud.cn/t/topic/13152/2

**Comment by wujun4code** [comment]
确实有这个接口，合并的版本会加上这个。

**Comment by myleslee** [comment]
已经存在：
- https://leancloud.cn/docs/rest_api.html#其他_API
- https://leancloud.cn/docs/rest_api.html#其他_API-1

我在具体内容那里再加个「服务器时间」的副标题。
