### ISSUE TITLE
新用户注册时，mobilePhoneNumber 字段全部加上 +86

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1846]
https://forum.leancloud.cn/t/topic/13243
https://forum.leancloud.cn/t/av-user-verifymobilephone/13184

测试手机号的功能中，使用测试手机号作为 MobilePhoneNumber 注册新用户时，如果不填写 +86，可以成功获取到验证码，但是无法验证，验证时会出现 211（找不到用户）错误。

也就是说，注册用户时：
```
if 测试手机号：
    手机号之前要填 +86
else:
    手机号之前加不加 +86 都可以
```

同时在注册用户的时候，我们也是推荐加上 +86 区号的。因此建议文档中把用户注册时的示例代码全部加上 +86 ，这样用户根据文档写代码的时候也不再会遇到 211 的问题了。
对应的文档有：
https://leancloud.cn/docs/leanstorage_guide-android.html#手机号码登录
https://leancloud.cn/docs/sms_guide-android.html#验证类
https://leancloud.cn/docs/leanstorage_guide-objc.html#手机号码登录
https://leancloud.cn/docs/sms_guide-objc.html#注册验证
https://leancloud.cn/docs/leanstorage_guide-js.html#手机号码登录
https://leancloud.cn/docs/sms_guide-js.html#注册验证
https://leancloud.cn/docs/leanstorage_guide-python.html#手机号码登录
https://leancloud.cn/docs/rest_sms_api.html#短信验证_API-1
https://leancloud.cn/docs/rest_sms_api.html#用户账户与手机号码验证

**Comment by myleslee** [comment]
>所以 测试手机号 统一使用了 「国际区号+手机号码的格式」 

现在只支持 +86 吗？

**Comment by nervouna** [comment]
我觉得应当是请求验证码时如果手机号没有加上国际区号，就返回一个错误信息，譬如 missing international prefix 之类。

后端自动干了某件事又没向客户端说明，感觉是个坑。

**Comment by nicecui** [comment]
> 现在只支持 +86 吗？
不是的，国际短信也支持的，国内短信推荐加上 +86

> 请求验证码时如果手机号没有加上国际区号……，或者在验证用户的时候也采用相同的逻辑，对于缺失国际区号的手机号码 fall back 到 +86 再查。
昨天和 @paomian 沟通非测试手机号加不加都能通过，测试手机号要兼容有安全隐患。

**Comment by nervouna** [comment]
> 昨天和 @paomian 沟通非测试手机号加不加都能通过，测试手机号要兼容有安全隐患。

那么可能需要在文档里说明原因，要不还是会出问题的。

或者可以在 211 错误码的文档里追加一句，如果您正在使用测试手机号，请确认手机号格式正确，如 `+8618512345678`。

**Comment by nicecui** [comment]
https://github.com/leancloud/uluru-platform/issues/3258

**Comment by myleslee** [comment]
兼容代码发布后，是不是文档就不需要改动了？

**Comment by nicecui** [comment]
@paomian

**Comment by paomian** [comment]
已上线
