### ISSUE TITLE
更友好的「对话禁言」说明

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1884]
## 背景
1、对话禁言，这个词，第一眼看不好理解。用户一般都会搜索关键字「拉黑」或者「黑名单」。
2、我们又没有可追溯的更新日志，很难知晓这个功能已经上线了

## 改进
在文档里说明运用场景：
我们可以用这个 API 来满足，实时通信里「拉黑」或者「黑名单」的需求场景。

@sunng87 宁姐觉得如何？

**Comment by sunng87** [comment]
我没问题，可以在描述里增加一些 黑名单 这样的关键词

**Comment by sunng87** [comment]
@myleslee 要不你来丰富一下那个描述吧

**Comment by myleslee** [comment]
「拉黑」和「黑名单」我理解是在不取消拉黑或移出黑名单的情况下一直生效/禁言。但我们的禁言的最长时间为 24 小时。会不会对用户有误导？
