### ISSUE TITLE
考虑在数据存储文档数据类型一节说明我们对时区的处理

### ISSUE THREAD

**Issue by nervouna** [leancloud/docs#1895]
1. 我们服务器（中国）使用的时区是 CST。
2. 我们 REST API 返回值使用的时区是 UTC。
3. 我们的 SDK 会将这个时间本地化为 CST。

因为这里 API 和 SDK 的行为是不一致的（数据一致），所以有必要单独说明。

**Comment by myleslee** [comment]
SDK 为什么要替开发者做转成 CST 的决定？

**Comment by nervouna** [comment]
我觉着这个行为还算合理，考虑到中国节点的用户几乎都需要使用 CST。美国节点应当是不转的。

**Comment by nervouna** [comment]
严格来说也不是转时区，只是根据时区信息 toLocal。
