### ISSUE TITLE
onverified hook 函数不需要 success

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1901]
>onVerified 没有 response 这个参数，也不需要调用 response.success();
https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#onVerified

@jysperm 帮忙补充一下示例代码

**Comment by jysperm** [comment]
删掉 response 和 response.success(); 就行了 ...

逻辑就是所有 after 类的 hook 都是没有 response 的。
