### ISSUE TITLE
Swift LCFile链接无法跳转

### ISSUE THREAD

**Issue by HawkinsZhao** [leancloud/docs#1918]
[这个页面](https://leancloud.cn/docs/leanstorage_guide-swift.html#SDK_安装) 上的 LCFile 链接无法跳转，请问在哪里可以找到相关的文档？

谢谢！

**Comment by myleslee** [comment]
Swift 目前还不支持 LCFile，替代办法是先将文件上传至自己的服务器或任何地方，取得 URL 后，通过 `LCObject` 将这个 URL 保存到 `_File` 表里：`let file = LCObject(className, "_File")`。文档会修正这部分。

**Comment by myleslee** [comment]
或者在代码中调用 REST API 来上传并保存文件到 `_File` 表：
https://leancloud.cn/docs/rest_api.html#上传文件

将来的 LCFile 也是对此 API 的封装。
