### ISSUE TITLE
属性限定 -> 返回部分属性？

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1923]
位置：https://leancloud.cn/docs/leanstorage_guide-android.html#属性限定

## 问题：
目前，小标题为「属性限定」。而用户想到这个需求，在文档里总是搜不到，然后去论坛发帖时用的关键字是：「部分」「字段」「属性」「返回」。

由于「限定」太书面了，用户搜索文档时，一般想不到用这个词，很难命中文档里的对应部分说明。

## 建议：
属性限定 -> 返回部分属性？

**Comment by myleslee** [comment]
「选择返回属性或字段」？「选择」跟 API `selectKeys` 中的 select 也很搭

**Comment by BinaryHB** [comment]
选择返回部分字段？

「部分」这个字眼也是蛮重要。

**Comment by myleslee** [comment]
严格说「部分」好像不完全正确，「返回指定属性/字段」?

**Comment by BinaryHB** [comment]
「返回指定属性/字段」就这个了

**Comment by myleslee** [comment]
嗯是的
