### ISSUE TITLE
增加 4318 错误码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1925]
https://forum.leancloud.cn/t/ios-callback/13863

@ylgrgyq @sunng87

**Comment by myleslee** [comment]
<img width="927" alt="screen shot 2017-03-14 at 21 25 15" src="https://cloud.githubusercontent.com/assets/108758/23902617/c1bcf5b6-08fc-11e7-835b-8d4c572a64de.png">
https://leancloud.cn/docs/realtime_v2.html#云端错误码说明
