### ISSUE TITLE
说明 _User 表的 authData 默认是客户端不可见的

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#1933]
来源：https://leanticket.cn/t/leancloud/4257

文档位置：https://leancloud.cn/docs/sns.html

改进：直接放在**最前头**，说明 authData 必须在控制台上点击右边的向下箭头，关掉「列属性」里的「客户端不可见」后，才能获取得到。

达叔，觉得把这段说明放在哪里，会最不容易让用户漏掉？

**Comment by myleslee** [comment]
SNS：
<img width="287" alt="1" src="https://cloud.githubusercontent.com/assets/108758/24340124/8012c6c8-12e2-11e7-9438-53fd211ddaae.png">

<img width="285" alt="22222" src="https://cloud.githubusercontent.com/assets/108758/24340130/85f38ece-12e2-11e7-854c-6e4a652f2d91.png">

 REST API：
<img width="244" alt="33333" src="https://cloud.githubusercontent.com/assets/108758/24340132/898e6ab8-12e2-11e7-95cf-7c2a17c0092f.png">

FAQ：
<img width="297" alt="4444" src="https://cloud.githubusercontent.com/assets/108758/24340127/82d8ff62-12e2-11e7-81d3-5ac602eb089f.png">
