### ISSUE TITLE
PHP 数据存储开发指南中的一个 Typo

### ISSUE THREAD

**Issue by nervouna** [leancloud/docs#1936]
https://leancloud.cn/docs/leanstorage_guide-php.html#数据类型

```php
$date = new \DateTime();
```

多了一个 `\`，应为

```php
$date = new DateTime();
```

**Comment by juvenn** [comment]
这里 `\DateTime` 可以理解为 root 命名空间下的 DateTime  类，而 `DateTime` 则表示用户当前命名空间下的类，如果用户自定义了这么一个类，就会使用用户的定义，而不是内置的定义。

所以我觉得应该要加 `\` 才对。 cc @myleslee

**Comment by nervouna** [comment]
TIL.
