### ISSUE TITLE
Readme 中的 IssueStats 图片出错

### ISSUE THREAD

**Issue by nervouna** [leancloud/docs#1940]
链接 http://issuestats.com/github/leancloud/docs 返回：

![image](https://cloud.githubusercontent.com/assets/1436139/24190284/307ffa1c-0f23-11e7-801a-017bc80b81ff.png)

**Comment by myleslee** [comment]
不太知道这个 issuestats 有什么作用，如果无法用就去掉？
@sparanoid

**Comment by sparanoid** [comment]
在 https://github.com/leancloud/docs/commit/77e0d63cc0dc3de45bef9c4c475a9790ef9886c5 中去掉了
