### ISSUE TITLE
REST API 修改 /1.1/login 请求方式为 POST

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1944]
https://leancloud.cn/docs/rest_api.html#%E7%94%A8%E6%88%B7
GET 修改为 POST 

![image](https://cloud.githubusercontent.com/assets/10130959/24236574/6108aee4-0fdd-11e7-9331-723f900f70ed.png)

**Comment by myleslee** [comment]
Closed by 88d5ff9
