### ISSUE TITLE
SDK 文档，补充解析云函数 response 的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#1969]
见图片中的红框：
![image](https://cloud.githubusercontent.com/assets/10130959/24702162/2da7ba10-1a30-11e7-825c-c859de2324cd.png)

**Comment by nicecui** [comment]
https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#参数信息

**Comment by myleslee** [comment]
新的 NODE SDK 2.0 取消了 response 参数
https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#参数信息

老版本文档放在了 Github 的《Node SDK v1 API 文档》上
  
后续有必要说明的内容就补充到《Node SDK v1 API 文档》吧

**Comment by nicecui** [comment]
讨论了一番之后，决定从 SDK 层面修掉：
https://github.com/leancloud/objc-sdk/issues/212
