### ISSUE TITLE
短信模版里有一些字段为保留字段

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2009]
如 {{name}} 默认是应用名。

请 @paomian 列举：

1. 所有的保留字段有哪些？
2. 分别是什么含义？

然后把这些保留字段放进文档里，强调用户不能用做其他用途。

**Comment by myleslee** [comment]
目前文档里是 3 个保留字段：https://leancloud.cn/docs/sms_guide-js.html#模板变量

**Comment by paomian** [comment]
这不算保留字段，这个东西完全可以用在模板里，但是他们也有相关的业务信息在里面，比如用户传递了`template` 可以选择模板，而且用户在模板里有 template 变量，其实这个 template 也可以在 template 被渲染，这个在两边都可以用。

**Comment by BinaryHB** [comment]
@paomian 无法理解你说的意思。

- name：应用名称
- code：验证码（通知类和营销类不会包含）
- ttl：过期时间（默认为 10 分钟）

核心问题是，上面的这三个字段，用户不能作它用。如果文档里停留在，仅仅说明这 3 个字段是保留字段，而不去清晰地告知用户不能去做什么。就会出现工单里的这个不按常理出牌的用户。

并且进一步：
如果用户在 request 模版的时候，主动传入了某一个保留字段，我们的后端也要**返回报错**，提示用户系统保留字段无法自定义。

**Comment by paomian** [comment]
这三个不是保留字段，只是会有一些意义

**Comment by BinaryHB** [comment]
>这些只是用户用了我们会覆盖。

那你觉得这个问题，是否有必要在文档里进行说明？如果是的话，你会撰写什么样对用户清晰友好的说明呢？@paomian

**Comment by paomian** [comment]
name 我们会覆盖为应用名称，code 会覆盖为我们的 code，ttl 有默认的，用户也可以穿，sign template 这些是和业务相关的，用户这里如果模板里用可能会有冲突
比如用户模板是 `{{name}} {{code}} {{ttl}} {{sign}} {{template}}` 用户基本上得传递 template 和 sign ，比如用户用模板 A 并且使用签名 B 模板就会被渲染为 `应用名称 验证码 过期时间 B A` 传上来的数据是一个 JSON 字段不能有重名，相当于 sign 和 template 这两个字段，既指定了签名和模板，有渲染了模板内容

**Comment by BinaryHB** [comment]
你没有回答我的问题...而且有 2 个错字...

我换个说法，我建议改进如下：
位置 https://leancloud.cn/docs/sms_guide-js.html#模板变量
模板还可以使用系统预留变量，在发送短信发送时，它们会被自动填充：
------>
模板还可以使用系统预留变量`。但是`在发送短信发送时，它们会被自动填充`。注意不要把它们作其他的用途`：

@paomian 你觉得如何？

**Comment by paomian** [comment]
可以这么理解

**Comment by myleslee** [comment]
https://leancloud.cn/docs/sms-guide.html#8bc186a585d691c239a77ea96afc8d98

在模板中还可以使用系统预留变量，在短信发送时，它们会被自动填充，**开发者无法对其重新赋值**：
