### ISSUE TITLE
Android 发布版本时同步更新文档里 SDK 版本号

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2039]
### 问题
已更新 v4.0 版本，但是前一个版本是 v3.16.4。所以需要更新文档 compile 里的  v3.+ 为 v4.+。

### 讨论
不过 @daweibayu **不建议**把 SDK 自动集成的 compile 写成 v4.+ 这种形式。
因为可能出现一种不好情况：
假如用户使用 v4.1 版本测试完毕打算上线，这时候我们恰好发布 v4.2 版本，而用户在默认的情况下，打包集成的版本就自动变成了 v4.2。因为 v4.1 到 v4.2 的升级变化，或许有一些未可知的问题。

### 建议
SDK 安装文档里，版本号写死。比如现在是 v4.0，就直接写成 4.0。当发布 v4.1 以后，同步更新文档里的 gradle 为 v4.1。

**Comment by myleslee** [comment]
closed by #2075
