### ISSUE TITLE
第三方登录，增加 JavaScript SDK 说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2041]
https://leancloud.cn/docs/sns.html

https://leanticket.cn/t/leancloud/4798

**Comment by wujun4code** [comment]
这个不是登录是关联，是已注册用户可以关联自己的社交账号。
其他 sdk 也都有这个接口但是都没提。

我加一下吧。

**Comment by weakish** [comment]
刚刚看了下，现在的 js 存储指南已经包含 `associateWithAuthData` 的内容
