### ISSUE TITLE
通过 REST API 发消息，返回值改动

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2087]
https://leancloud.cn/docs/realtime_rest_api.html#通过_REST_API_发消息
现在返回的是下面的格式，不再是空值了：
```
{"result":{"msg-id":"0PrGHIn4RQcWxcQSKvD6CN","timestamp":1495788609845}}
```

![image](https://cloud.githubusercontent.com/assets/10130959/26488057/8e0df988-4234-11e7-89bd-306394d598e6.png)

**Comment by myleslee** [comment]
Closed by #2087
