### ISSUE TITLE
补充 will 消息的文档

### ISSUE THREAD

**Issue by tang3w** [leancloud/docs#2092]
SDK 已经支持 will 消息，但文档中一直没写。需要补充一下。

不过 will 消息得仔细描述，因为它有一些特点（限制）：

1. 同一时刻只对一个对话生效；
2. 当 client 主动 close 时，will 消息不会下发。因为 mqtt 中认为这是计划性下线。

    > mqtt 里计划性的下线是不发的，我觉得是合理的，计划性的下线你可以自己发出这个消息了
    > 这样分开就可以覆盖所有的场景，如果是非计划的就用will，如果是计划的就自己发
    > by nsun

    > Situations in which the Will Message is published include, but are not limited to:
    >
    > An I/O error or network failure detected by the Server.
    > The Client fails to communicate within the Keep Alive time.
    > The Client closes the Network Connection without first sending a DISCONNECT Packet.
    > The Server closes the Network Connection because of a protocol error.

如果用户要用这个机制实现下线通知，需要在 close 时，主动通知自己下线。可以通过暂态消息实现。

@wujun4code

**Comment by myleslee** [comment]
- [x] iOS
- [x] Android
- [x] Unity, .NET
- [ ] JavaScript

**Comment by myleslee** [comment]
#2151 #2167
