### ISSUE TITLE
TodoDemo 超链 404

### ISSUE THREAD

**Issue by jiacai2050** [leancloud/docs#2105]
![snip20170607_39](https://user-images.githubusercontent.com/3848910/26872707-10754498-4baa-11e7-8950-80e906b4f275.png)

这里的 TodoDemo 超链 https://github.com/leancloud/Android-SDK-demos/tree/master/AVOSCloud-Todo 404 了

https://leancloud.cn/docs/app_search_guide.html 这个文档地址

**Comment by myleslee** [comment]
@BinaryHB 知道这个 demo 的新位置吗？

**Comment by BinaryHB** [comment]
这个 demo 已经很久远，都找不到了。

可以暂时先去掉超链接。
