### ISSUE TITLE
如何获取一个class的总数据量？

### ISSUE THREAD

**Issue by thejojo87** [leancloud/docs#2118]
问个小白问题。一个表里，默认返回查询数量是100，使用limit也是1000.
我如果想知道所有的数据数，该怎么获取？

比如1300条数据，然后我自己再分页什么的。
我该如何获取这1300这数据呢？

小白问题，还请见谅。

**Comment by wujun4code** [comment]
https://forum.leancloud.cn/t/topic/9945
