### ISSUE TITLE
[新增一条知识库] 云引擎为什么有 Application not found 报错

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2121]
1、调用错了环境。最常见的情况是，免费的体验实例是没有预备环境的，开发者却主动设置去调用预备环境；
2、xxx.leanapp.cn 二级域名填错了，比如微信回调地址。一定要确认单词 xxx 完全一致。
有个开发者二级域名 xxx 有 3 个 lll，回调地址里填的却只有 2 个 ll。

**Comment by myleslee** [comment]
二级域名是不是以 monotype 等宽字体显示会好一些？
