### ISSUE TITLE
补充使用 sessionToken 登录的文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2147]
#### 问题来源
https://leanticket.cn/t/leancloud/4797
https://forum.leancloud.cn/t/sessiontoken-ios-sdk/4702/8

#### 相关文档位置
https://leancloud.cn/docs/leanstorage_guide-objc.html#SessionToken

#### 详情
增加一个小标题，叫：「使用 sessionToken 登录」

##### 使用 sessionToken 登录
在没有用户名密码的情况下，客户端可以使用 sessionToken 来登录。

常见的使用场景有：

* App 某个页面内的 WebView 登录
* 在服务端登录后，返回 sessionToken 给客户端，客户端根据返回的 sessionToken 登录

具体的接口如下：
Obj-C：
```
[AVUser becomeWithSessionTokenInBackground:@"sessionToken" block:^(AVUser * _Nullable user, NSError * _Nullable error) {
        
}];
```
Android:
```
AVUser.becomeWithSessionTokenInBackground
```
JavaScript：
```
AV.User.become(sessionToken)
```

**Comment by nicecui** [comment]
补充一个来源：
工单 [4819](https://leanticket.cn/t/leancloud/4819)

**Comment by myleslee** [comment]
代码部分可以再完整一些：
@tang3w @daweibayu @leeyeh 

```
// 1. getSessionToken()
// 2. become(sessionToken)
// 3. 在成功的回调中更新 currentUser 的信息 become(sessionToken)
```
然后再提及一下：不过如果是使用 URL 打开外部浏览器，使用 URL 来传递 session token 的话，是一种有危险的行为，请避免。

**Comment by tang3w** [comment]
SDK 内部会更新 currentUser 的信息，OC 示例代码这样写吧：

```objc
NSString *sessionToken = <#SessionTokenYouGetFromOtherPlace#>;

[AVUser becomeWithSessionTokenInBackground:sessionToken
                                     block:^(AVUser * _Nullable user, NSError * _Nullable error) {
                                         if (!error) {
                                             NSLog(@"User did login with session token.");
                                         }
                                     }];
```

`<#` 与 `#>` 是 Xcode IDE 中 placeholder 的语法。

**Comment by nicecui** [comment]
一般来说，OC 和 Android 需要用到的 sessionToken，是服务端返回的，在服务端使用 Node.js 获取 sessionToken 的方法如下：
```
var sessionToken = request.currentUser._sessionToken;
```

而 WebView 需要用到的 sessionToken 是从客户端拿到的。
OC 拿到的方法如下：
```
AVUser *currentUser = [AVUser currentUser];
NSString *sessionToken = currentUser.sessionToken;
```

Android 拿到的方法如下：
```
AVUser.getCurrentUser().getSessionToken();
```
