### ISSUE TITLE
Python / PHP/ Java 缺乏「云函数调用的超时」文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2157]
Python / PHP/ Java 云函数调用超时的处理链接无效：

https://leancloud.cn/docs/leanengine_cloudfunction_guide-php.html#错误信息

![image](https://user-images.githubusercontent.com/10130959/27820686-2d133118-60d2-11e7-8807-83f2972f9035.png)

**Comment by myleslee** [comment]
@juvenn @aisk @sdjcw 请确认下面这部分对 Python、PHP 和 Java 是否适用？
https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#云函数超时

**Comment by sdjcw** [comment]
不太适用，因为除了 Node.js，其他语言都是同步调用，要改成同步响应，异步处理需要额外的操作，需要额外补充一些示例代码。

**Comment by aisk** [comment]
Python / Java 可以考虑推荐用户开一个线程来做这件事 @sdjcw

**Comment by weakish** [comment]
在 #3060 中跟进
