### ISSUE TITLE
增加消息的撤回与修改文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2158]
https://github.com/leancloud/docs/pull/2151/files#diff-3679a3ff5e47afdfadfe5715df328c38R511

@tang3w @daweibayu @leeyeh @wujun4code 

看看哪里还缺示例代码，填一下尽快上线哟

**Comment by myleslee** [comment]
- [x] iOS
- [x] Android
- [x] Unity, .NET
- [ ] JavaScript

**Comment by leeyeh** [comment]
补充到那个 PR 上了
