### ISSUE TITLE
推送增加常见问题：为什么成功设备数小于目标设备数？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2162]
建议是放到这里：
https://leancloud.cn/docs/push_guide.html#推送问题排查

答案：
「目标设备数」是指符合本次推送查询条件的有效设备数量，「成功设备数」是指这次推送成功到达的设备数量。
没有到达设备一般有以下三种情况：
* Android 设备中的应用被杀掉，在网络中处于离线状态。对于这种情况，稍等一段时间等待设备上线后，成功设备数就会逐渐增加。同时推荐集成[混合推送](https://leancloud.cn/docs/android_push_guide.html#混合推送)来提升推送的到达率。
* Android 设备的用户删掉或重装应用生成了新的设备数据，之前的无效数据被包含到了成功设备数中。
* iOS 设备的用户删掉或重装了应用，之前的无效数据被包含到了成功设备数中，这些数量就是 invalidTokens 数量。

@ylgrgyq 看看描述是否有纰漏。

**Comment by myleslee** [comment]
invalidTokens 会被自动清理掉吗？这样下一次就不用再发给已失效的设备了？

**Comment by ylgrgyq** [comment]
invalidTokens 大多数时候不会被清理掉，在 DB 中可能还会存在。但是我们会缓存 invalid tokens 设备，下一次发消息时候虽然还包含在目标设备中，但是发送之前会检查缓存，如果发现是无效设备就不进行实际发送，只是记录 invalid tokens 计数。

清理 invalid tokens 机制比较麻烦，我们在发现 invalid token 时候先要判断 APNs 返回的 invalid 时间和用户 installation updatedAt 字段先后顺序，如果发现 invalid 之后一直没有 update 过，说明这个数据确实是无效的，可以删除，我们也会执行删除操作。但是如果 invalid 时间在 update 之后，说明 token invalid 后，其 installation 记录又 update 过，这个时候不进行删除，避免错误删除无效 token。APNs 给的文档说不要对 token 是否变化有过多期待，每次注册 token 可能颁发的 token 是一样的， 也可能不一样。所以我们没有认为无效的 token 一定不会再被启用，所以没有随意删除。
