### ISSUE TITLE
推送增加常见问题：内容为空时是什么情况？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2163]
建议是放到这里：
https://leancloud.cn/docs/push_guide.html#推送问题排查

答案：
当针对不同目标设备类型设置了不同消息内容时，内容一栏会显示为空，需要点击消息 ID 打开推送详情来查看具体消息内容。

**Comment by myleslee** [comment]
控台已有，跟操作相关，放在控台维护更合适
（第一条）
<img width="1032" alt="screen shot 2017-07-10 at 08 18 59" src="https://user-images.githubusercontent.com/108758/27998891-93acf222-6548-11e7-9e1d-c7c43e55ebfa.png">

**Comment by nicecui** [comment]
这里是打算把问题添加到文档之后，优化一下控制台的解释。
现在控制台这里太乱了，考虑的是这里只放问题的链接，然后点击链接到相应的文档页面。

**Comment by myleslee** [comment]
https://leancloud.cn/docs/push_guide.html#为什么推送记录的内容为空_

**Comment by nicecui** [comment]
达叔么么哒 😘
