### ISSUE TITLE
推送增加常见问题：目标设备数为 0 是什么情况？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2164]
建议放到这里：
https://leancloud.cn/docs/push_guide.html#推送问题排查

答案：
「目标设备数」是指符合本次推送查询条件的有效设备数量，该值为 0 时请检查推送查询条件及目标设备是否有效。点击这里查看[目标设备数的限制](https://leancloud.cn/docs/push_guide.html#限制)。

**Comment by myleslee** [comment]
控台已有，跟操作相关，放在控台维护更合适
（最后一条）
<img width="1032" alt="screen shot 2017-07-10 at 08 18 59" src="https://user-images.githubusercontent.com/108758/27999076-f2aeca96-654a-11e7-943b-c84eaca39163.png">
