### ISSUE TITLE
推送增加常见问题：为什么只能给三个月内活跃过的设备发消息？能否发全量设备？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2165]
我们限制只能给 _Installation 表内 updatedAt 时间在最近三个月以内的设备推送消息。原因如下：

三个月没有活跃过的设备，用户打开推送的概率已经非常小了，我们认为这些不活跃的设备为无效设备。

考虑到成本的原因，如果要全量推送，需要处理的无效设备数量会成倍增长，这样会造成投入非常多，产出却非常小。其中一个能感知到的影响就是推送时间，目标设备数成倍增长也意味着单次全量推送的时间也是成倍增长。

因此处于效率上的考虑，在公有云上只能给三个月以内活跃过的设备发消息。如果您确实需要给全量设备发消息，可以联系 support@leancloud.rocks 使用我们的企业版服务，为您的应用划分独立集群来提供推送服务。

**Comment by nicecui** [comment]
@ylgrgyq 确认一下这个问题，面谈的时候很多用户询问。

**Comment by ylgrgyq** [comment]
这个要写到哪里吗？我感觉没有问题啊
