### ISSUE TITLE
补充 Android 推送唤醒机制的文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2181]
如果一个设备上装了两个使用 LC 推送的应用，应用被杀掉时，另一个应用唤醒时可以同时唤醒当前应用的推送。

@daweibayu

**Comment by nicecui** [comment]
把原来的 <service android:name="com.avos.avoscloud.PushService"/> 改为 <service android:name="com.avos.avoscloud.PushService" android:exported="true"/>
就可以了。

**Comment by myleslee** [comment]
`android:exported="true"` 不会有副作用吗？

<img width="916" alt="screen shot 2017-08-14 at 10 30 31" src="https://user-images.githubusercontent.com/108758/29256311-12031bde-80dc-11e7-93f5-5b2bff3c081d.png">

还是我们不改上面的，再加一段说明：

如果希望支持应用间的推送唤醒机制，即在同一设备上有两个使用了 LeanCloud 推送的应用，应用 A 被杀掉后，当应用 B 被唤醒时可以同时唤醒应用 A 的推送。

```
<service android:name="com.avos.avoscloud.PushService" android:exported="true"/>
```
@daweibayu

**Comment by nicecui** [comment]
应该是加一段说明，因为有的用户可能不希望默认这个行为，觉得是骚扰行为的一种，所以这个是默认关闭的。
