### ISSUE TITLE
增加文档更新页面

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2184]
https://forum.leancloud.cn/t/swift/15313

考虑增加一个页面，专门放最近文档的更新。
这样用户来查看文档时也能迅速看到最近发布的一些新功能。

**Comment by wujun4code** [comment]
我想想怎么搞。得给一个比较好的维护方式。

**Comment by wujun4code** [comment]
这个目前搞不了，我们的文档都是静态页面，而且更新历史依赖于当前项目的 issue 和 commit，很难转化为用户可读可接受的文字陈列在某一个文档页面上。工程量很大，并且实际效果只是为了给用户看一眼的话，意义不大。

**Comment by nicecui** [comment]
也不只是给用户看一眼，主要是为了这个场景：用户定期项目升级的时候，来我们网站看文档时，可以看到最近的一些新功能的更新。

**Comment by wujun4code** [comment]
关键是现在这个真做不了，技术上需要投入的东西很多，比如从每次发布之前需要执行脚本从 github 的 commit log 把人类可读的内容读出来，生成对应的 html 标签放在文档的底部，这个工作量不小的。而且还需要通晓老师来调整一下样式，我很蛋疼。。。

**Comment by nicecui** [comment]
我是觉得可以先人工维护一份。。。

**Comment by wujun4code** [comment]
纳尼。。。

**Comment by fuchenshi** [comment]
可以在涉及到的文档的开头加一个「新功能」章节，里面用一个列表概括最近新增的功能，然后用锚点将每个功能链接到相关的章节。
