### ISSUE TITLE
文档中应该说明文件存储服务包含 CDN

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#2186]

**Comment by hjiang** [comment]
另外应该说明一下开通国际 CDN 的流程。

**Comment by myleslee** [comment]
将《常见问题》中的「[CDN 加速](https://leancloud.cn/docs/faq.html#文件存储有_CDN_加速吗_) 」也添加到《存储》文档中，并将步骤细节设置为折叠收起样式。 
<img width="451" alt="screen shot 2017-07-20 at 08 45 50" src="https://user-images.githubusercontent.com/108758/28395669-2afb9d4a-6d28-11e7-9dae-1700a831435c.png">

------

FAQ 中默认折叠打开。
<img width="442" alt="screen shot 2017-07-20 at 08 54 28" src="https://user-images.githubusercontent.com/108758/28395777-10d9cc10-6d29-11e7-8a34-f9e84b4bc38f.png">
