### ISSUE TITLE
增加知识库：非 Web 组如何调用云函数

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2187]
https://leanticket.cn/tickets/4872

**Comment by myleslee** [comment]
<img width="639" alt="screen shot 2017-07-20 at 11 37 25" src="https://user-images.githubusercontent.com/108758/28399485-dfd2d71c-6d3f-11e7-9692-e411ff569c54.png">

这里是不是应该说「只允许通过 REST 来调用云函数，不支持通过 SDK 来调用云函数，也不支持 Hook 函数和定时任务。 」

@sdjcw

**Comment by sdjcw** [comment]
我建议只写 「不支持通过 SDK 来调用云函数，也不支持 Hook 函数和定时任务。」

至于使用 REST 方式调用，不是我们推荐的，懂的用户也能明白，不懂的用户也不容易解释。
