### ISSUE TITLE
去掉 JS 文档对比较查询的错误限定

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2197]
来源：
https://forum.leancloud.cn/t/username-username/15490/5

位置：
https://leancloud.cn/docs/leanstorage_guide-js.html#比较查询

改动：
去掉最后一行字`比较查询只适用于可比较大小的数据类型，如整型、浮点等。`

原因：
因为最后那行字，导致用户误以为 equalTo 不能用来精确匹配字符串。

**Comment by myleslee** [comment]
要改成这样呢？
`，如字符串、数字、日期等。`

**Comment by myleslee** [comment]
@wujun4code 你的建议？
