### ISSUE TITLE
增加 Java 云引擎 2GB 内存运行时一个优化操作

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2205]
位置：https://leancloud.cn/docs/leanengine_webhosting_guide-java.html

文档：`Java 运行环境对内存的使用较多，所以建议：`这行文字的最后面增加第四列

- 以 示例项目 起步的应用，建议使用 512MB 或以上规格的实例。
- 使用 Spring Boot 的应用，建议使用 1GB 或以上规格的实例。
- 本地启动并模拟完成主要业务流程操作，待应用充分初始化后，根据 Java 进程内存占用量选择相应的实例规格，需要注意保留一定的余量用以应对请求高峰。
- 使用最高 2GB 内存实例运行时，建议在云引擎的设置页面，增加环境变量，名称：`JAVA_OPTS`，值 `-Xmx1500m`，这样限制 jvm 堆最大为 1.5GB，剩下 500MB 是给对外内存和其他一些杂项使用。

**Comment by sdjcw** [comment]
文案建议修改下：

Java 应用可能在启动初期因为内存使用增长较快，导致 JVM 堆内存申请非常多，从而超出实例规格限制。可以考虑增加 JVM 堆内存最大使用限制来避免该问题：假设使用 2GB 内存规格的实例运行，则可以在云引擎的设置页面增加「自定义环境变量」，名称：`JAVA_OPTS`，值 `-Xmx1500m` 限制 JVM 堆最大为 1.5GB，剩下 500MB 是给持久代或堆外内存，或者其他一些杂项使用。**注意**：请合理设置 `-Xmx` 参数，设置的过小可能导致大量 CPU 消耗在无休止的 GC 任务上。
