### ISSUE TITLE
Windows WinFrom & WPF 聊天文档编写

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2216]
## 起因
因为基于 Windows 开发的行业特征，一般依然还在 Windows 平台开发的企业一般都是外包公司居多，做的也都是基于企业内部的一些 IT 项目或者监控类的项目，其本身存在的行业问题是

- 程序员研发实力普遍较弱
- 阅读文档能力偏弱

目前我们的限行的文档不适合他们阅读的主要原因如下：

- 开发指南都是偏向于移动端并且带有诸多社交性质的指导代码
- 针对企业内部 it 项目缺乏对应的指导
- 阅读门槛还是偏高

## 改善方案
编写一个面向企业 OA 聊天系统的文档

- [ ] 以企业员工为切入点阐述 AVUser 可以作为一个聊天的用户
- [ ] 以企业部门为切入点阐述 Conversation 
- [ ] 以新闻消息为切入点阐述自定义消息
- [ ] 以 钉钉为例进行解析，找到 LeanCloud 实现 钉钉功能点的对应接口

## 暂缓
为了尽快的吸引用户使用，我们正在计划改善现在的签名机制，签名暂时不做介绍

**Comment by weakish** [comment]
暂时先关了。以后有人有兴趣写这个主题的文档可以再打开。
