### ISSUE TITLE
[知识库] 如何获取云引擎的入口和出口 IP 地址

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2239]
在命令行里运行以下 2 行代码：
```
dig -t txt in.leanengine.leancloud.cn
dig -t txt out.leanengine.leancloud.cn
```
in 表示入口 IP，out 表示出口 IP。如果您遇到 IP 变动的问题，请随时运行命令以获取最新的 IP 地址。

_**说明**_：在 https://github.com/leancloud/uluru-platform/issues/3918 issue 开发关闭之后，再新增这条知识库。

**Comment by myleslee** [comment]
结论是用户去控台里点击按钮获取，不通过用命令行，所以就不作为知识库条目了。
