### ISSUE TITLE
添加「超过 1 年未活跃的会话会自动删除」的说明

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2254]
可以加到这里：https://leancloud.cn/docs/realtime_v2.html#限制

**Comment by myleslee** [comment]
文档中有两处：
总览：https://leancloud.cn/docs/realtime_v2.html#对话_Conversation_

<img width="918" alt="screen shot 2017-08-22 at 21 20 17" src="https://user-images.githubusercontent.com/108758/29567424-be41778e-877f-11e7-9afd-2d806e372145.png">

https://leancloud.cn/docs/realtime_guide-android.html#对话的有效期
