### ISSUE TITLE
增加存储文档：select 级联获取

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2269]
https://leancloud.cn/docs/leanstorage_guide-objc.html#关联属性查询
 select 和 include 一样，是支持 . 级联查询的，类似于下面这样：
```
AVQuery *query = [AVQuery queryWithClassName:@"Post"];
[query includeKey:@"comment"];
[query includeKey:@"comment.owner"];
[query selectKeys:@[@"comment.owner.username"]];
```

**Comment by wujun4code** [comment]
@nicecui 
这个的效果是啥？我看如果使用 include 的话，整个 comment.owner 都可以拿到，为什么还要 select 呢？

**Comment by nicecui** [comment]
经过我在 xcode 的测试，这个效果最终只会拿到 comment.owner.username，可以节省流量。

**Comment by wujun4code** [comment]
```
[query includeKey:@"comment.owner"];
```
加上这句也只能拿到 `comment.owner.username`？

**Comment by nicecui** [comment]
是的，include 不影响，但是如果 selectKeys 里面加上 `comment.owner`，那么拿到的是全部 comment.owner。

**Comment by wujun4code** [comment]
恩，显然这个 feature 很少有人会用。。。行吧，我加上吧。
