### ISSUE TITLE
希望提供 Dash 支持 

### ISSUE THREAD

**Issue by XerWandeRer** [leancloud/docs#227]
https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

**Comment by killme2008** [comment]
谢谢，我看看好不好搞。

**Comment by callmewhy** [comment]
+1。。。要不然每次都打开太麻烦了。

**Comment by sparanoid** [comment]
记得之前提过 https://github.com/leancloud/avoscloud-docs/issues/183

**Comment by callmewhy** [comment]
@sparanoid 链接错了，方便再提供一下吗？

**Comment by sparanoid** [comment]
@callmewhy 那是个内部的 private repo :)

**Comment by wujun4code** [comment]
这个感觉是不是不做了？
