### ISSUE TITLE
新增 node.js 开启 gc 日志的说明

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2275]
位置：https://leancloud.cn/docs/leanengine_webhosting_guide-node.html#健康监测

文案：在最后增加

如果对内存增长有疑问，可以开启 gc 日志：

package.json
```
···
"start": "node --trace_gc server.js",
···
```

增加参数 `--trace_gc`，这样每次 GC 都会有日志输出。

**Comment by myleslee** [comment]
@sdjcw

**Comment by sdjcw** [comment]
内容本身没问题，但是感觉加在文档这个地方怪怪的，因为「健康监测」部分和内存增长没有任何关系。

我更建议有一个类似于「云引擎内存泄漏排查」的 FAQ 来列这类技巧。

**Comment by BinaryHB** [comment]
那就先列在 https://leancloud.cn/docs/leanengine_faq.html 云引擎常见问题里。等之后「内存泄漏排查」相关的信息比较完整之后，可以单独作为一个小节放出来。
