### ISSUE TITLE
增加 实时通讯 使用 AVUser 登录的文档

### ISSUE THREAD

**Issue by jiacai2050** [leancloud/docs#2278]
现在各个 sdk 已经完成功能，希望能把文档补上，并在**显要位置**推荐使用这种方式使用实时通讯。

**Comment by ylgrgyq** [comment]
辛苦家财在 paas 那个工程开个 issue 吧，把这个链接过去。SDK 同事关注 docs 可能不多，放到  Paas 他们就比较容易看到了。
