### ISSUE TITLE
讲解微信小程序使用 unionId 如何登录

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2284]
### 步骤
1、使用如下格式 authData，注意字段名 openid 和 uid 一定要书写正确：
```
AV.User.signUpOrlogInWithAuthData({
'openid' : openid,
'uid' : unionId,
 ……其他可选属性
}, 'xiaochengxu');
```
2、在控制台给 authData.xiaochengxu.uid 加个唯一索引。点开 _User 表->「其他」->「索引」，点击 authData 后，输入 authData.xiaochengxu.uid 保存。

请 @leeyeh review 后，决定放在哪里。建议放在小程序专有的文档里，作为一个小节。

**Comment by myleslee** [comment]
放在 **小程序** > **存储** > **用户系统** 下，新加一下标题？ 
https://leancloud.cn/docs/weapp.html#用户系统

**Comment by leeyeh** [comment]
`xiaochengxu` 这个改成 `lc_weapp_union` 吧
