### ISSUE TITLE
增加 installation.apnsTopic 的文档

### ISSUE THREAD

**Issue by tang3w** [leancloud/docs#2293]
基于 Token Authentication 的推送要求应用设置 installation.apnsTopic 字段，该字段是 iOS app 的 bundle ID。目前 iOS native SDK 会默认读取，但如果应用再 React Native 等环境中使用，需要让开发者显式地设置。因此这个 API 需要在文档中描述一下。

@wujun4code

**Comment by BinaryHB** [comment]
具体代码是：
```
LeancloudInstallation.getCurrent()
.then(installation => {
installation.set('deviceType', 'ios');
installation.set('apnsTopic', 'com.example');
installation.set('deviceToken', 'xxxxxxxx');
return installation.save();
});
```

**Comment by myleslee** [comment]
#2346 跟这个 PR 是相关的吧？我是不是关早了？

**Comment by tang3w** [comment]
相关的是两者都在描述如何指定 apnsTopic；不相关的是一个在说 push，另一个在说 installation。
可以独立地描述。
