### ISSUE TITLE
应用内搜索文档有一处和实际描述不符

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2302]
在"应用内搜索和 DeepLink 开发指南">"开发步骤">"设置应用内搜索选项"中介绍属性**应用 URL Host**时,原文是"我们推荐默认使用avoscloud",但是在控制台推荐默认是**leancloud**

**Comment by SXiaoXu** [comment]
###补充一处问题:
在"应用内搜索和 DeepLink 开发指南">"开发步骤">"第三步:在应用内集成搜索组件>Android 集成">"高级定制指南"小节的最后一句话**"你也可以参考 我们的 SearchActivity"**点击链接回复404 Not Found.

**Comment by myleslee** [comment]
fixed via 74a1b2a
