### ISSUE TITLE
AVUser 单点登录方案

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2312]
考虑使用实时通信的单点登录来实现。

原来的方案：https://leancloud.cn/docs/leanstorage_guide-objc.html#单点登录

@wujun4code

**Comment by wujun4code** [comment]
这个解决方案我们讨论了一下，我会更新到这里来。

**Comment by wujun4code** [comment]
### 前提条件：用户在 A 设备上已登录，用户准备在 B 设备上登陆

### 在 B 设备上要做的操作如下

1. 调用 AVUser.logIn(username,passowrd)

2. 调用 user.refreshSessionToken() 强制刷新 token，目的是让 A 设备上的 sessionToken 过期

### A 设备上要做的操作如下

1. 客户端发出请求如果服务端返回 401 ，开发者需要提示当前用户登录信息失效，跳转到登录界面去

**Comment by wujun4code** [comment]
做不到跟微信一样的在线实时通知，但是只要 A 设备发现自己请求都 401 了，就应该知道当前 sessionToken 已经过期了，就可以默认是在其他设备上登录了。

**Comment by nicecui** [comment]
嗯，这样也可以，没什么问题了，A 设备启动时需要发出 isAuthenticated 请求来验证 sessionToken 是否有效。

**Comment by wujun4code** [comment]
这个文档已经有了。
