### ISSUE TITLE
你们的maven炸了?

### ISSUE THREAD

**Issue by leveychen** [leancloud/docs#2318]
http://mvn.leancloud.cn/nexus/content/repositories/public/

Error:(64, 14) Failed to resolve: cn.leancloud.android:avoscloud-statistics:v4.4.3
Error:(62, 14) Failed to resolve: cn.leancloud.android:avoscloud-sdk:v4.4.3

**Comment by jwfing** [comment]
http://mvn.leancloud.cn/nexus/content/repositories/public/cn/leancloud/android/avoscloud-statistics/v4.4.3/
http://mvn.leancloud.cn/nexus/content/repositories/public/cn/leancloud/android/avoscloud-sdk/v4.4.3/

@leveychen 这都是可以访问的啊，上面两个地址你在浏览器能打开吗？

**Comment by leveychen** [comment]
浏览器可以访问这些地址，在Android studio里打不开了  ，之前还是好的，今天更新了一下leancloud依赖。就炸了。

**Comment by leveychen** [comment]
Android Studio 我设置了代理，但是已经设置不代理 mvn.leancloud.cn  和 *.leancloud.cn

**Comment by jwfing** [comment]
那可能还是代理的问题吧，只要浏览器能访问，就证明这个 maven repositories 是可访问的了。
