### ISSUE TITLE
微信小程序文档完善

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2328]
原文链接：https://leancloud.cn/docs/weapp.html#在微信小程序中使用_LeanCloud

1.对于 Demo 的介绍，可以加一条：「如何使用 LiveQuery 实现对查询结果的实时更新」。Demo 的 README.md 里面的介绍更详细，要不要二者的介绍保持一致？

2.文档中要不要添加 Demo 的本地安装运行步骤？

3.准备工作 > 配置域名白名单这个小节下，可以更新下描述（对应开发者工具最新版）：
原文：如果你不需要进行真机调试可以跳过这一步（可在开发者工具的项目配置中勾选「开发环境不校验请求域名」）。
需要更新为：如果你不需要进行真机调试可以跳过这一步（可在开发者工具的详情>项目设置中勾选「不校验安全域名、TLS 版本以及 HTTPS 证书」）。

**Comment by myleslee** [comment]
1. Demo 的介绍可以二者保持一致，已更新。
2. 不在文档中重复「运行步骤」了，尽量降低维护成本。
3. 已更新。
