### ISSUE TITLE
实时通信，增加失败消息缓存相关的文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2332]
现在 iOS 和 Android 应该已经完成了这个功能，用于方便地在前端展示发送失败的消息并重发。

**Comment by tang3w** [comment]
可以通过调用 `-[AVIMConversation addMessageToCache:]` 方法把一条还未发送成功的消息缓存起来，待消息发送成功时，SDK 会自动将该消息更新为发送成功状态；也可以通过调用 `-[AVIMConversation removeMessageFromCache:]` 方法来从缓存中删除一条发送失败的消息。

**Comment by jwfing** [comment]
Android 这边的接口是：
```
  public void addToLocalCache(AVIMMessage message);
  public void removeFromLocalCache(AVIMMessage message);
```
