### ISSUE TITLE
导入 Class 的 CSV 文件格式的提示

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2334]
用户问题反馈：本地数据导入 LeanCloud 时，cvs 文件末含有几个空行，造成多创建几个空对象。用户社区问题链接：https://forum.leancloud.cn/t/class-cvs/16211

文档本地数据导入 LeanCloud > CSV 格式文件: 这个地方要不要提示用户注意一下,避免文件末尾出现多余空行。文档链接：https://leancloud.cn/docs/dashboard_guide.html#本地数据导入_LeanCloud

**Comment by myleslee** [comment]
加这个提醒简单。不过如果后端可以处理的话可能体验更好，就是说在控制台里，如果发现上传的 CSV 文件包含空行，可以提示 `上传文件中包含空行，请选择： [x] 忽略空行 [ ]  空行生成空记录`。
@jwfing

**Comment by jwfing** [comment]
我觉得这应该是后端的 bug，没有对输入进行合法性检查，生成一个空记录没有任何意义，直接忽略掉空行就可以了。

**Comment by myleslee** [comment]
后端修复
