### ISSUE TITLE
[教程]如何实现网易云音乐社交账号管理的功能

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2342]
![image](https://user-images.githubusercontent.com/5119542/31702960-cf60b0f6-b39f-11e7-9132-ebd6c5a36748.png)

**Comment by wujun4code** [comment]
### 当前 sdk 状态

platform|关联社交账号|取消关联社交账号|以社交账号创建或者登录
--|--|--|--
iOS|[user addAuthData]|[user removeAuthData]|[user loginWithAuthData]
js|user.associateWithAuthData|user.disassociateWith(尚未开放)|user.signUpOrlogInWithAuthData
android|user.associateWithAuthData|user.disassociateWithAuth|user.loginWithAuthData
c#|user.LinkWith|user.UnlinkWith|user.LogInWith

#### 社交账号创建或者登录的 api 尚不统一

platform|以社交账号创建或者登录
--|--
iOS|[user loginWithAuthData: {"accessToken":"xxx"},platform:"facebook"]
js|user.signUpOrlogInWithAuthData({"accessToken":"xxx"},"facebook")
android|user.loginWithAuthData(AVThirdPartyUserAuth)|
c#|user.LogInWith("facebook",{"accessToken":"xxx"})

*注*：android 声明了一个对象来存储相关信息：

```java
public AVThirdPartyUserAuth(String accessToken, String expiredAt, String snstype, String userId
```


### 建议

### ios 

添加 associateWithAuthData 和 disassociateWith 接口如下:

```objc
user associateWithAuthData:*AVUser  platform:*NSString
user disassociateWith:platform:*NSString
```

#### js
开放 disassociateWith 接口

#### android
提供 loginWithAuthData 的重载支持直接传入 authData 和 platform 的函数，不需要构造一个 AVThirdPartyUserAuth 对象。

#### c#
重命名 link 和 unlink 为 associateWithAuthData 和 disassociateWith

**Comment by zapcannon87** [comment]
简单来说，就是改变 API 的名称，对吗？

**Comment by wujun4code** [comment]
@zapcannon87 你可以提供一个新的，然后内部还是调用老的，这一切都随你，随意随意 或者 desprated 也阔以。

**Comment by wujun4code** [comment]
@jwfing

**Comment by jwfing** [comment]
感觉这样更合理一些：
- 关联社交账号：
`user.associateWithAuthData`
- 取消关联社交账号：
`user.disassociateWithAuthData`
- 以社交账号创建或者登录：
`User#logInWithAuthData({"accessToken":"xxx"},"platform")`

**Comment by wujun4code** [comment]
@jwfing 
以上的话 js 还是维持现状的，c# 这边改一下参数位置和名字吧。

**Comment by jwfing** [comment]
看起来 js 以前名字取的比较讲究啊。。。

**Comment by jwfing** [comment]
> 以上的话 js 还是维持现状的，c# 这边改一下参数位置和名字吧。

我们的标准不是要谁改或者不要谁改，只是看看哪一种命名方式更合理一些。我个人是觉得从文档的描述来看，上面的接口命名是最直白和准确的。

**Comment by wujun4code** [comment]
我没意见了，我已经更新了 顶部 的建议，就这么干吧。

**Comment by wujun4code** [comment]
C# 已经改完了。

**Comment by jwfing** [comment]
有个问题确认一下， associateWithAuthData 这个方法，iOS/JS 是静态方法，还是 instance 方法？

**Comment by jwfing** [comment]
@wujun4code  之前的总结有误吧，我看 取消关联社交账号 的现有接口是：
1. Android：AVUser.dissociateAuthData(AVUser user, String type, AVCallback cb)  ***这是 class 方法***
2. iOS：[user deleteAuthDataForPlatform:block]   ***这是 instance 方法***
3. JS：无

取消关联的接口名叫 dissociateAuthData 比较好吧，而且我们还需要把 class 方法/ instance 方法统一一下，`AVUser.dissociateAuthData(user, type)` 这个调用方式比较诡异，为什么不直接 `user.dissociateAuthData(type)` 呢？
我看 iOS 那边增加关联的函数也是 instance 方法，不是 class 方法（JS/Android 是 class 方法）。我们以前搞成 class 方法的原因是什么？ @daweibayu @leeyeh
