### ISSUE TITLE
转移 JavaScript 文档按条件保存对象的位置

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2364]
https://leancloud.cn/docs/leanstorage_guide-js.html#保存选项

这里其实不是 save 操作，应该是 update 操作的。save 时无法指定 query 满足某个条件。放到「保存对象」下给用户造成了误解：https://leanticket.cn/tickets/14625

REST API 这里的位置是正确的：
https://leancloud.cn/docs/rest_api.html#按条件更新对象

**Comment by myleslee** [comment]
不知道我理解得正不正确，`fetchWhenSave` 应该还是 save 的 options 吧，这样它还放在「保存选项」那一节中，归为 save，而把 `query` 挪到「更新对象 > 按条件更新对象」下去。所有 SDK 都改。
@nicecui @leeyeh @wujun4code @jwfing @tang3w

**Comment by leeyeh** [comment]
fetchWhenSave 好像也是只会返回更新的那个字段的最新值，所以创建的时候指定 fetchWhenSave 确实没啥用，对吗 @paomian

**Comment by paomian** [comment]
fetchWhenSave 更新的时候只会返回更新的值，insert 时候会返回所有的数据
