### ISSUE TITLE
小程序域名白名单配置文档改进

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2370]
小程序域名白名单配置  可以再详细些。
https://leancloud.cn/docs/weapp-domains.html

### **需要详细的地方：**

**「1. 选择 LeanCloud 应用」**   
这部分选择应用的按钮不太像一个可以点击的按钮，这一步很容易被忽略。

**「3. 增加以下域名」** 
这部分文档可以再详细一些：

可以在 request 域名下面标注「6个域名都要添加，缺一不可」。
可以在 socket 域名下面标注「4个域名都要添加，缺一不可」。 

### **需要增加的地方：**

**是不是可以增加配置成功的微信开发平台的截图，或小程序开发工具的截图，给用户一个对照参考。**

### 论坛中涉及的问题：

小程序发布后上传数据失败
https://forum.leancloud.cn/t/topic/16432

开发工具上没问题的但是苹果真机预览 报错code：101 为什么
https://forum.leancloud.cn/t/code-101/16337/27

**Comment by myleslee** [comment]
建议不加截图：
- 有些用户可能不看文字，只按截图上的地址填写
- 小程序 UI 会变，截图可能会过时

文档已经做调整，步骤比以前更清晰。
