### ISSUE TITLE
短信 SMS 服务使用指南--Android SDK 和Java SDK区分问题

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2372]
文档地址：https://leancloud.cn/docs/sms-guide.html#验证类短信 

「短信 SMS 服务使用指南」里面：
![snip20171108_10](https://user-images.githubusercontent.com/11917002/32537784-c9efd27c-c49e-11e7-995b-4fadfd708e97.png)

这个文档里显示的Java  都是指 Android SDK 的Java.

点击Java SDK 的文档，进入>短信 SMS 服务使用指南，让我误解上图指的示例代码：是Java SDK 的方法。
![snip20171108_11](https://user-images.githubusercontent.com/11917002/32537993-755abc80-c49f-11e7-9f61-cff98811e190.png)

### 建议的解决办法
1：「Java」  替换成---> 「Android-Java」或者「Android」
      好让Android SDK 和 Java SDK有一个区分。
2：去掉 Java SDK 顶部导航栏的指引。
      //或者在短信 SMS 服务使用指南里面加上 Java SDK 的相关方法。

**Comment by myleslee** [comment]
@jwfing 请您决断

**Comment by BinaryHB** [comment]
因为语言本身是有多种用途的，Java 客户开发 Android 这样的移动端、也可以开发后端。同样，JavaScript 可以开发 Web 端，也可以作为 Node.js 开发后端。

所以我的建议是，我们代码下面的选择器，用来表示「平台性」。主要取决于当前语言所在的语境，是前端移动端，还是后端。
1、存储，前端移动端相关的 Java 改成 Android。比如短信：
![image](https://user-images.githubusercontent.com/6046086/33063708-35337702-cede-11e7-9ba8-0b111bb4e911.png)

2、云函数里的 JavaScript 改成 Node.js：
![image](https://user-images.githubusercontent.com/6046086/33063598-e3220014-cedd-11e7-9bfb-b6910c8c4171.png)

**Comment by SXiaoXu** [comment]
问题：有些用户从： [Java >短信 SMS 服务使用指南]  这里面进入的时候，会误以为Android SDK 的方法 「AVSMSOption」 是 Java SDK 的方法。

**建议**：增加 Java SDK  短信服务指南的示例代码。现在文档中没有。

 需要使用 Java SDK 短信功能的用户社区链接：
 https://forum.leancloud.cn/t/leancloud/16547/3 
 https://forum.leancloud.cn/t/java-sdk/16604/1

**Comment by jwfing** [comment]
我们目前 Android SDK 和 Java SDK 代码不同源，接口差异也比较大，之后我会抽时间把他们两个合到一份 codebase 上（大工程），在这之前，我们还是把 `Java` 变成 `Android` 吧，避免误导用户。

**Comment by BinaryHB** [comment]
等丰老师统一 Android 和 Java 的 code base 后，两边的代码就是完全一致的了。

然后 code block 里的 Java 分类可以扩展为 Java / Android。
