### ISSUE TITLE
实时通信文档，拆分暂态消息和自定义消息

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2377]
https://leancloud.cn/docs/realtime_guide-objc.html#暂态消息
https://leancloud.cn/docs/realtime_guide-android.html#暂态消息

这两个文档把自定义消息和暂态消息放到了一起，事实上两者不是一回事，需要拆开分别介绍。

**Comment by myleslee** [comment]
@wujun4code 你来改吧

**Comment by wujun4code** [comment]
![image](https://user-images.githubusercontent.com/5119542/32664642-8ac150bc-c5f7-11e7-9dcc-2f75ccc60395.png)

**Comment by wujun4code** [comment]
根本没有在一起啊。。。

**Comment by nicecui** [comment]
暂态消息的话，只有下面这一行代码不就够了么...？
```
[self.tomConversation sendMessage:message options:AVIMMessageSendOptionTransient callback:nil];
```

而且看起来暂态消息里面的示例代码是自定义消息：
```
@interface YourOperationMessage : AVIMTextMessage <AVIMTypedMessageSubclassing>
```

**Comment by wujun4code** [comment]
这个我得打电话给你解释了。。。暂态是可以用自定义消息的方式构建的，比如对方正在输入这种消息是最好封装成一个自定义消息类型发出去的。

**Comment by nicecui** [comment]
我一直觉得暂态消息反正服务端也不保存，就当做普通消息加暂态选项发出去就好了，居然还要这么复杂的实现....
总感觉这段自定义消息的示例代码放到自定义板块里面会更合适...

**Comment by myleslee** [comment]
那可以在「自定义消息」里提一下：

`[暂态消息](暂态消息) 也是通过自定义消息的方式来实现的。`

可以吗？

**Comment by nicecui** [comment]
嗯，我觉得可以这样做
