### ISSUE TITLE
[统计] 新增一些参数说明

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2390]
位置：https://leancloud.cn/docs/rest_api.html#hash172404328

新增：
1、metrics=lost_user_7，表示「7 天流失用户数」；
2、metrics=page_exit，表示页面退出，「页面跳出率」= page_exit / page_visit。

**Comment by BinaryHB** [comment]
https://github.com/leancloud/uluru-platform/issues/2753

**Comment by BinaryHB** [comment]
请 @juvenn 确认下，信息和参数名 lost_user_7、page_visit 无误。

**Comment by myleslee** [comment]
@juvenn 增加的部分见：
https://github.com/leancloud/docs/pull/2391/files#diff-236292fe4e9a9b32a3ff69e19cb941e7R200

**Comment by juvenn** [comment]
没有问题 👍
