### ISSUE TITLE
文档采用 algolia 后 之前的锚点失效了

### ISSUE THREAD

**Issue by jiacai2050** [leancloud/docs#2395]
比如
https://leancloud.cn/docs/realtime_v2.html#%E6%9D%83%E9%99%90%E5%92%8C%E8%AE%A4%E8%AF%81

工单回复的文档引用如果用了锚点也就失效了，感觉需要兼容一下。

**Comment by myleslee** [comment]
这个链接在 algolia 之前就被修改了，凡是使用了 url encoded 的 anchor 也都被一起改掉了。

你这个链接现在要用：
https://leancloud.cn/docs/realtime_v2.html#hash-188224612
将来可能还会变回来：
https://leancloud.cn/docs/realtime_v2.html#权限和认证

一种方法是在回复工单是写上引用的标题或内容关键字，如：
> 请参考文档中的「权限和认证」：https://leancloud.cn/docs/realtime_v2.html#hash-188224612

这样 anchor 失效了，读者还能根据关键字「权限和认证」进行搜索来定位内容。

anchor 转换前与转换后的对应关系倒是有，但数量比较多（TOTAL: hrefs: **1017**, ids: **3932**），用 ngix redirect 可能影响性能，或是在 docs 站点的 404 页面加个脚本，从下面这个日志里找到 match 后跳转。

<img width="380" alt="screen shot 2017-11-22 at 19 58 31" src="https://user-images.githubusercontent.com/108758/33126673-44483c36-cfc0-11e7-9c6d-d790006a3fe1.png">

**Comment by jiacai2050** [comment]
一个网页的某个位置，可以放多个锚点，感觉最好能做到平滑迁移，否则之前贴出去的链接都不能找到正确位置，感觉体验很不好。
