### ISSUE TITLE
[短信] 说明华东节点、美国节点的短信价格

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2405]
#### 问题背景：
目前我们的短信价格文档，都是从国内节点的立场来说明的。当华东节点、美国节点的短信上线后，文档读起来就十分混乱了。

#### 改进目标：
1、明确短信文档服务于：华北、华东和美国三个节点；
2、各个节点下的短信服务国家列表、对应价格；

### 改哪里
1、[国际短信](https://leancloud.cn/docs/sms-guide.html#hash701356668) 这个小节标题更改：国际短信 -> 节点短信价目表

2、在 [服务覆盖区域和价格](https://leancloud.cn/docs/sms-guide.html#hash-228064280) 小节里，最开始增加一行：

国号 | 国家或地区 | 国家代号 | 单价（元/条）
-- | -- | -- | --
86 | 中国 | CN | 0.05（华东、华北节点）/0.2（美国节点）

然后在后面单价那一列里，加上「所有节点均为 XXX」

国号 | 国家或地区 | 国家代号 | 单价（元/条）
-- | -- | -- | --
1 | 美国 | US |  所有节点均为 0.07
1 | 加拿大 | CA | 所有节点均为 0.07
7 | 哈萨克斯坦 | KZ | 所有节点均为 0.58
7 | 俄罗斯 | RU | 所有节点均为 0.28
....

3、原「国家短信」里的第二个小节 [开通国际短信服务](https://leancloud.cn/docs/sms-guide.html#hash1579896394) 移动到文档开头的 [开通短信服务](https://leancloud.cn/docs/sms-guide.html#hash1120305634) 里，放在「在应用选项中完成短信配置」之后。

然后它的文案做下更改：
标题「开通国际短信服务」--->「国内节点使用国际短信」
内容「国际短信服务是需要额外开启的」---> 「国内节点，如华北和华东，使用国际短信，是需要额外开启的」

4、[国际短信](https://leancloud.cn/docs/rest_sms_api.html#hash701356668) 这一小节，最后一句：
「要了解短信可送达的所有国家或地区以及费率，请参考 国际短信。」
--->
「要了解各个节点短信可送达的所有国家或地区以及费率，请参考 [节点短信价目表](https://leancloud.cn/docs/sms-guide.html#hash701356668)。」

5、[短信服务 REST API 详解](https://leancloud.cn/docs/rest_sms_api.html) 文档开头：

「我们支持国内短信和国际短信，并为每个 LeanCloud 账户提供 100 条国内短信的免费额度进行测试，超过的部分将实时从账户余额中扣除，所以请务必保证账户余额充足。具体的价格请参看 官网价格。」
--->
「LeanCloud 的各个节点，为每个 LeanCloud 账户提供 5 元的短信免费额度进行测试（不显示在账户余额里），超过的部分将实时从账户余额中扣除，所以请务必保证账户余额充足。具体的价格请参看 [节点短信价目表](https://leancloud.cn/docs/sms-guide.html#hash701356668)。」

**Comment by BinaryHB** [comment]
需要 @paomian 的 LGTM，确认 [改哪里] 第 2 步里的：
1、每个节点服务国家列表是否一致？
2、唯一区别是，华北、华东节点的中国短信价格为 0.05，而美国节点的中国短信价格为 0.2？

**Comment by myleslee** [comment]
还是将节点都单独列出来好，即使价格一样，也避免使用「所有节点均为 xx」：

国号 | 国家或地区 | 国家代号 | 华北|华东|美国
-- | -- | -- | --| --|--
1 | 美国 | US |  0.07| 0.07| 0.07|
1 | 加拿大 | CA |  0.02| 0.07| 0.07|
7 | 哈萨克斯坦 | KZ |  0.01| 0.07| 1.00|

再为这个表格加个过滤/搜索，因为太长了，改善体验。

**Comment by BinaryHB** [comment]
嗯。价格分开列好，这样可以被搜索到。

**Comment by paomian** [comment]
没问题
