### ISSUE TITLE
[统计] 实时统计已经下线,  需要删掉相应的 REST_API

### ISSUE THREAD

**Issue by zqq90** [leancloud/docs#2407]
删掉的小结如下: `统计数据 API ` > `数据查询 API` > `获取某个应用的实时统计数据：`

位置: https://leancloud.cn/docs/rest_api.html#hash704893677 

具体内容:

```
获取某个应用的实时统计数据：
.....

参数名 | 含义
-- | --
metrics | 统计数据项
platform | 应用平台：iOS、Android，可选，默认是全部。

返回数据
...
````

cc @juvenn @BinaryHB

**Comment by BinaryHB** [comment]
补充一下。删除的文档内容是：

从 获取某个应用的实时统计数据：（包括这行字） 到 批量获取： 中间的所有文档。
