### ISSUE TITLE
[统计] 实时统计已经下线, 一些指标需要下掉

### ISSUE THREAD

**Issue by zqq90** [leancloud/docs#2408]
删掉的指标如下: `统计数据 API ` > `数据查询 API`
位置: https://leancloud.cn/docs/rest_api.html#hash704893677

参数名 | 说明
-- | --
active_user_hour | 活跃用户数（按小时查看）
new_user_hour | 新增用户数（按小时查看）
session_hour | 启动次数（按小时查看）

cc @juvenn @BinaryHB

**Comment by BinaryHB** [comment]
补充一下。删除的文档内容是：
 
从 `获取某个应用的实时统计数据：` 到 `批量获取：` 中间的所有文档。
