### ISSUE TITLE
ping 地址显示错误

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2410]
SDK 安装指南中验证网络的 **ping** 地址显示错误。应该显示专属二级域名，实际显示如下图：

![snip20171204_5](https://user-images.githubusercontent.com/11917002/33543458-11cf8bc8-d912-11e7-8c05-6bd909498cae.png)

**文档中错误的地方有：**
1.[Swift SDK 安装指南 - 验证 ](https://leancloud.cn/docs/sdk_setup-swift.html#hash1262261)。
2.[PHP SDK 安装指南 - 验证 ](https://leancloud.cn/docs/sdk_setup-php.html#hash1262261)。
3.[Java SDK 安装指南 - 验证 ](https://leancloud.cn/docs/sdk_setup-java.html#hash1262261)。
4.[Python SDK 安装指南 - 验证 ](https://leancloud.cn/docs/sdk_setup-python.html#hash1262261)。
5.[JavaScript SDK 安装指南 - 验证 ](https://leancloud.cn/docs/sdk_setup-js.html#hash1262261)。

社区用户反馈连接 ：https://forum.leancloud.cn/t/ping-v2domain/16690

**Comment by myleslee** [comment]
Closed by #2409
