### ISSUE TITLE
「CDN 加速」内容更正

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2424]
文档原文：「**中国节点的文件存储服务自带 CDN 加速访问。 美国节点没有现成的 CDN 加速访问服务，需要用户自行配置（步骤）。**」

**问题：**
1、中国的 CDN 加速是需要配置的，美国是默认有的，请 @kadashu  确认。
2、配置步骤链接失效，点击无响应。

文档链接：

[数据存储开发指南 · Objective-C - 文件 - CDN 加速](https://leancloud.cn/docs/leanstorage_guide-objc.html#hash-1364316385)。

Android/Python/JavaScript/Java/PHP「数据存储开发指南- CDN 加速」部分同上。

**Comment by kadashu** [comment]
中国区用的七牛，默认有 CDN 加速
美国区用的 S3，没有 CDN 加速
>1、中国的 CDN 加速是需要配置的，美国是默认有的

https://leancloud.cn/docs/faq.html#hash-1573330760
>2、配置步骤链接失效，点击无响应。
