### ISSUE TITLE
验证 SessionToken 的示例代码缺失

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2429]
1、Android 地址：https://leancloud.cn/docs/leanstorage_guide-android.html#hash-666999517

小节标题：验证 SessionToken 是否在有效期内

增加代码：
```
        AVUser.getCurrentUser().isAuthenticated(new AVCallback<Boolean>() {
            @Override
            protected void internalDone0(Boolean aBoolean, AVException e) {

            }
        });
```
2、PHP 地址：https://leancloud.cn/docs/leanstorage_guide-php.html#hash-666999517

请 @juvenn 补充一下代码。

3、Java 地址：https://leancloud.cn/docs/leanstorage_guide-java.html#hash-666999517

请 @jwfing 补充一下代码。

**Comment by jwfing** [comment]
PHP/Java SDK 一般都是用在服务器端的，这种场景下应该没有 currentUser 这种用法，所以文档里面把这部分移除为好。

**Comment by BinaryHB** [comment]
丰老师说的在理。我们平台上应该也没有拿 Java 来开发 PC 客户端的用户。

达叔只加 Android 文档的示例代码就好了。这个 issue 我关了。
