### ISSUE TITLE
文档中的 Demo 链接指向  Github demos 汇总页面

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#243]
![image](https://cloud.githubusercontent.com/assets/5022872/7315907/94dd08a6-eaa4-11e4-9b25-eb4aa3d00323.png)

比网页，Github 上直接改 Readme.md 来得更敏捷些，也更方便配图。Github 上也有不少这样的汇总项目，如 [android-open-project](https://github.com/Trinea/android-open-project)  ，[awesome-ios-ui](https://github.com/cjwirth/awesome-ios-ui) 。

没有问题的话，将链接至 https://github.com/leancloud/leancloud-demos

**Comment by jwfing** [comment]
先不要这样改，github 的 demo 页要清理一下才行。

2015-04-24 17:15 GMT+08:00 lzwjava <notifications@github.com>:

**Comment by lzwjava** [comment]
能说说需要怎样清理吗？

**Comment by jwfing** [comment]
simpleChat 已经好了没有？iOS／Android／Javascript 全部连通的
