### ISSUE TITLE
每日短信限制规则更新

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2452]
改动位置：https://leancloud.cn/docs/rest_sms_api.html#hash1358585625

怎么改：
`一个自然日的 24 小时内只能向同一个手机号码发送 10 条验证类短信、15 条通知类短信，这些限制将于次日凌晨 0 点被重置。`
--->>>
todo 测试中

**Comment by BinaryHB** [comment]
cc @paomian

**Comment by paomian** [comment]
如果某个自然日内，触发了每日上限，服务端的限制将于，这个自然日内的第一条验证类短信发送时间点的 24 个小时后解除。

不敢相信，一个流控做这么复杂

**Comment by BinaryHB** [comment]
@paomian 确认下「通知类短信」的限制规则？

**Comment by paomian** [comment]
我们这边都是自然日限制，确定要做成他这样么？我感觉好奇怪啊

**Comment by BinaryHB** [comment]
验证码的这个限制，你能绕过去？按照他们的这个规则，你是如何做到自然日限制的？

**Comment by paomian** [comment]
一天一个 key

**Comment by paomian** [comment]
现在文档需要将「自然日」改为 24 小时内，如果允许，应举例说明
「您在 2018-01-01 11:59:00 发送了十条短信，这时会进入流控状态，需要等待 24 小时后，即  2018-01-01 11:59:00 分才可再次发送短信」

**Comment by BinaryHB** [comment]
通知类短信的规则，现在不清楚。我今明两天来测试一下。

**Comment by myleslee** [comment]
结论是改为「24 小时内」？

**Comment by paomian** [comment]
对

**Comment by BinaryHB** [comment]
实测结果：

### 验证类短信
计量单位，是 24 小时，不是自然日。

当发送了第一条验证类短信后，在这个时间点之后的 24 小时里，最多再发送 9 条验证类短信，共 10 条验证类短信。依次类推。

### 通知类短信

云片未作任何限制。目前 API 是按自然日来处理的，当某天发送超过 15 条的上限后，次日凌晨重置。
