### ISSUE TITLE
补充离线分析的限制说明

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2463]
来源：https://leanticket.cn/tickets/14865

文档修改位置：https://leancloud.cn/docs/leaninsight_guide.html#hash1213926

改动：
1、补充一行文字：离线分析结果导入到另一张表的条目，不能超过 200 条。
2、`_User 表的 sessionToken、password、salt 字段，因为安全原因也被限制查询。`
--->>>
`_User 表的 sessionToken、password、salt 字段，所有表的 ACL 字段，因为安全原因也被限制查询。`

**Comment by myleslee** [comment]
Closed by 5cebcd9
