### ISSUE TITLE
补充 JS SDK 的 LiveQuery Debug 代码

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2483]
Debug 代码：
```
localStorage.setItem('debug', 'LC*');
```

可以放到之前统一放调试代码的地方：
https://leancloud.cn/docs/start.html
![image](https://user-images.githubusercontent.com/10130959/37339866-0ca605b8-26f7-11e8-96e9-b0238adf839b.png)

也可以单独放到 LiveQuery 的页面：
https://leancloud.cn/docs/livequery-guide.html#hash753677491

**Comment by myleslee** [comment]
其他语言还有没有单独针对 LiveQuery 进行 debug 的方法？

**Comment by nicecui** [comment]
没有了，iOS 和 Android 都是通用的一行代码
