### ISSUE TITLE
英文文档计划

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2489]
## 标识说明

emoji|含义
--|--
⛔️ |**已在计划中，尚未开始**
🚧 |**正在进行中**
✔️ |**已完成**
🈹 |**不打算翻译**

## 云存储

子模块|状态|备注|中文版|英文版|Dead Line|
--|--|--|--|--|--
服务总览| ⛔️ | |[数据存储服务总览](https://leancloud.cn/docs/storage_overview.html)||2018Q2
SDK 使用| ✔️  ||||2018Q2

## 实时通信

子模块|状态|备注|中文版|英文版|Dead Line|
--|--|--|--|--|--
服务总览| ⛔️ | |[实时通信服务总览](https://leancloud.cn/docs/realtime_v2.html)||2018Q3
SDK 使用| ⛔️ ||||2018Q3

## 云引擎

子模块|状态|备注|中文版|英文版|Dead Line|
--|--|--|--|--|--
服务总览| ⛔️ | |[云引擎服务总览](https://leancloud.cn/docs/leanengine_overview.html)||2018Q3
网站托管| ⛔️ ||||2018Q3

## 消息推送

子模块|状态|备注|中文版|英文版|Dead Line|
--|--|--|--|--|--
iOS| ⛔️ ||||2018Q4

**Comment by weakish** [comment]
见 https://github.com/leancloud/docs-en/
