### ISSUE TITLE
Python 自定义错误码需要遵守 http code 格式

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2513]
来源：https://leanticket.cn/tickets/15112

文档地址：https://leancloud.cn/docs/leanengine_cloudfunction_guide-python.html#hash554227936

改动：

`错误响应码允许自定义`
--->>>
`错误响应码允许自定义，但是必须遵守 [HTTP状态码](https://zh.wikipedia.org/zh-hans/HTTP状态码) 的格式，比如 4xx。`

**Comment by sdjcw** [comment]
我没有问题。
