### ISSUE TITLE
关于客户端获取 ACL 问题整理讨论

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2522]
如果想在获取对象的同时返回对象的 ACL 值，需要满足两个条件：

**1.  在控制台 > 存储 > 设置中有一个选项「查询时返回值包括 ACL」，必须勾选上。**

![image](https://user-images.githubusercontent.com/11917002/38982357-36e44532-43f4-11e8-81b4-20c4cbdcbd47.png)

**2.  需要传参数 returnACL= true，在客户端获取对象的 ACL 值需要单独 include 一下。**

## REST API
```
curl -X GET \
   -H "X-LC-Id: JMBPc7y4SUPRDrOSHXjXVMN7-gzGzoHsz" \
  -H "X-LC-Key: Wib2dECd48h1FzivFrH628ju" \
   -G \
  --data-urlencode 'returnACL=true' \
   https://jmbpc7y4.api.lncld.net/1.1/classes/Todo/5ad06a679f54540045a76b68
```
## iOS
```
AVQuery *query = [AVQuery queryWithClassName:@"Todo"];
[query whereKey:@"objectId" equalTo:@"5ad06a679f54540045a76b68"];
query.includeACL = YES;
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        
   }];
```

三个用户提问，答案先记在这里，再看一下放在文档哪个位置合适。
计划更新在 [ACL 权限管理开发指南](https://leancloud.cn/docs/acl-guide.html) 文档中。

社区涉及用户：
https://forum.leancloud.cn/t/getacl/14629
https://forum.leancloud.cn/t/ios-acl/17748
https://forum.leancloud.cn/t/acl/17780

**Comment by BinaryHB** [comment]
需要先确认：是不是因为不兼容的设计导致，客户端必须传 "returnACL":"true" 的键值对。

目前 Android 完全没有传这个参数，功能本身是不可用的。

**Comment by BinaryHB** [comment]
请 @jwfing 丰老师看下，`query include attr 里面填上 acl ` 的代码要怎么写。

**Comment by jwfing** [comment]
android 这边如果调用 `query.include("ACL")` 是没有效果的，看来 android sdk 也需要像 iOS sdk 一样增加一个 includeACL 的配置项。

**Comment by jwfing** [comment]
属性命名上，iOS 这边因为已经有一个 `[Query includeKey:]` 的方法，如果这里还是叫做 `includeACL` 恐怕会引起误解，不如按照 REST API 的提法改成 `returnACL` 的好。 @zapcannon87 觉得呢？

**Comment by zapcannon87** [comment]
OK，我觉得可以。

**Comment by jwfing** [comment]
@zapcannon87 算了，先不改名字了，我看 JS SDK 也是 `includeACL` 这样命名的，我给 android 这边加一个与你们相同的属性吧。

**Comment by jwfing** [comment]
@SXiaoXu @BinaryHB Android sdk 会在这个 PR 里面解决：https://github.com/leancloud/android-sdk-all/pull/190

**Comment by BinaryHB** [comment]
Android 实例代码：

```
        AVQuery<AVObject> query = new AVQuery<>("Todo");
        query.includeACL(true);
        query.findInBackground(new FindCallback<AVObject>() {
            @Override
            public void done(List<AVObject> list, AVException e) {
                
            }
        });
```

**Comment by leeyeh** [comment]
```js
var query = new AV.Query('Todo');
query.includeACL(true);
query.find().then(function(todos) {
  // 查询结果
}).catch(function(error){
  // 异常处理
})
```
