### ISSUE TITLE
去掉短信免费额度

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2568]
之前会赠送给每个账户 6 块钱，现在这个赠送已经取消了，所以这个常见问题可以去掉了。
https://leancloud.cn/docs/rest_sms_api.html#hash-1843898040

**Comment by myleslee** [comment]
`AV.User.requestLoginSmsCode(测试手机号)` 还是免费的，对吧？

**Comment by jwfing** [comment]
没有取消，这个 issue 我先关闭了。
