### ISSUE TITLE
「知识库 | 云引擎」为什么服务器重启后，LeanCache 没有自动恢复？

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2596]
先检查 Redis 的版本是不是高于 v2.2.5。

如果是的话，需要在初始化的时候设置 `retry_max_delay ` 和 `max_attempts ` 两个参数，然后本地做个实验：

1. 正常运行 redis server 和应用。
2. 停止 redis server。
3. 观察应用开始输出类似于 `redis err: Error: Redis connection to localhost:6379 failed - read ECONNRESET` 的错误信息。并且输出间隔逐渐增加（因为重试时间间隔是 `This delay normally grows infinitely` 的）。
4. 然后观察重试次数打到 `max_attempts` 设置的值时会发生什么，预期是不要 catch 这个异常，让异常抛出，直接样应用因为此异常退出，这样云引擎容器会自动重启实例，或者云引擎管理程序也会因为健康检查失败而重新部署该实例。

其次，还需要注意配置下「允许应用在 `redis server` 链接失败时容忍的最大时间」，是根据 `retry_max_delay` 和 `max_attempts` 的组合配置，比如 `retry_max_delay` 设置为 8 秒，`max_attempts` 设置为 6 次，则 redis server 连不上时重连间隔大概是这样：1 秒，2 秒，4 秒，8 秒，8 秒，8 秒，然后抛出重连失败异常。也就是应用处于 `redis server` 连不上 30 多秒左右。注意该值不要太短（10 秒以内），因为可能存在一些网络波动。

**Comment by sdjcw** [comment]
知识库标题建议改成：更完善的 LeanCache 重连方式

问题：虽然 redis client 一般都会有重连机制，但是存在一些极端情况导致一直无法重连成功，所以下面提供一种更好的重连实践。

解决办法：
    基本思路：如果 LeanCache 的 redis server 链接断开，则使用 redis client 的重连机制进行尝试，尝试一定次数仍无法连接成功则抛出异常，让应用异常退出。云引擎管理程序会重启实例，这样能解决一些极端情况下的重连失败。

（然后类似上面的文档）

需要修改的地方：

> 先检查 Redis 的版本是不是高于 v2.2.5。

版本 *低于* v.2.5.0 时有效，v.2.5.0 之后使用 `retry_strategy`， https://github.com/NodeRedis/node_redis/releases/tag/2.5.0-1  (回头再补充个示例代码)。

然后观察重试次数「达」到

直接「让」应用因为此异常退出。

**Comment by sdjcw** [comment]
我做了一些实验，发现这个问题要讲清楚还挺麻烦，因为问题次数不多，暂时先针对性的解释。
