### ISSUE TITLE
您好 

### ISSUE THREAD

**Issue by zfk513** [leancloud/docs#2619]
请问数据导出后如何打开？是什么格式？
打开后不会操作，没有后缀 o(TヘTo)

**Comment by myleslee** [comment]
不是没有后缀，后缀是 `.tar.gz`，是一种压缩文件格式。参见 https://baike.baidu.com/item/tar.gz
在 Windows 中可以使用 WinRAR 或 7zip 打开。解压缩后会有多个 `.json` 文本文件。

**Comment by zfk513** [comment]
原来是这样，解压后没有后缀，加了json还有乱码，所以我才觉得奇怪
