### ISSUE TITLE
希望文档可以增加 RPC 云函数示例和非 PRC 云函数示例。

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2621]
希望文档可以增加 RPC 云函数示例和非 PRC 云函数示例。
RPC 返回 AVObject 应当怎么写，非 RPC 返回的不是 AVObject 应当怎么写。

**Comment by jysperm** [comment]
不太懂你的意思，云引擎这边文档上已经都是 Promise 写法了

**Comment by nicecui** [comment]
@jysperm 之前我没看清楚，确实都是 Promise 了。改了下需求，希望增加 RPC 和非 PRC 的示例代码。

**Comment by jysperm** [comment]
RPC 和非 PRC 对于服务器端代码来说没有任何区别；客户端的 RPC 和非 PRC 在文档里都有

**Comment by nicecui** [comment]
我觉得还是有区别的，我写云函数的时候总担心自己返回的是不是标准的 AVObject。例如我能不能返回一个自己构造一个 AVObject 的 Array 。

**Comment by jysperm** [comment]
可以的，这个倒是确实可以添加一段关于云函数返回值的描述

**Comment by weakish** [comment]
> 我写云函数的时候总担心自己返回的是不是标准的 AVObject。例如我能不能返回一个自己构造一个 AVObject 的 Array 。

经我黑盒试验，返回值的情况是：

- AVObject :ok:
- Array<AVObject> :ok:
- Object<String, AVObject|NonAVObject> :ok: 

但是，直接返回非 Object，如 string、number，得到的是空对象 `{}`。
类似地，直接返回一个包含非 Object 的数组， 其中的非 Object 成员也会被序列化为 `{}`。
例如，一个返回 `[1, post]` （post 是一个 AVObject）的云函数，rpc 调用的结果是：

```json
{
  "result": [
    {},
    {
      "objectId": "5c88d968303f390037d1152e",
      "__type": "Object",
      "className": "Post"
    }
  ]
}
```

不太确定序列化为空对象 `{}` 是不是预期的结果？ @jysperm

**Comment by jysperm** [comment]
https://github.com/leancloud/leanengine-node-sdk/blob/master/lib/leanengine.js#L302-L320

看起来确实是一个 Bug，设计上这个接口应该支持任何的嵌套方式。

**Comment by weakish** [comment]
Closed in favor of #3063
