### ISSUE TITLE
android 即时通讯文档有错误

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#2698]
https://leancloud.cn/docs/realtime_guide-android.html#hash578071618
<img width="1152" alt="2018-08-27 4 18 18" src="https://user-images.githubusercontent.com/985038/44648875-fddd3280-aa14-11e8-9c45-6bf1b9596215.png">

**Comment by wujun4code** [comment]
这有什么问题？接口错了还是描述错了？

**Comment by wujun4code** [comment]
##2699
