### ISSUE TITLE
[feat] md 语法渲染序列图

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2710]
## 示例
依赖库：[https://bramp.github.io/js-sequence-diagrams/](https://bramp.github.io/js-sequence-diagrams/)

\```seq
Andrew->China: Says Hello
Note right of China: China thinks\nabout it
China-->Andrew: How are you?
Andrew->>China: I am good thanks!
\```

会被渲染成:

![image](https://user-images.githubusercontent.com/5119542/45075958-5601ec00-b11b-11e8-9603-4bcee5a24045.png)

**Comment by wujun4code** [comment]
![image](https://user-images.githubusercontent.com/5119542/45080383-61f3ab00-b127-11e8-83da-065062652810.png)

不知道为什么不能设置 simple 样式只能渲染成上面这个挫样……

**Comment by wujun4code** [comment]
终于实现了。。。

**Comment by weakish** [comment]
现已支持这一特性（基于 mermaid）
