### ISSUE TITLE
第三方登录更新文档产品线

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#2715]
### 更改
1. 移除 https://leancloud.cn/docs/ 页面最底下的「其他」->「开源组件」->「第三方社交账号登录组件」
2. 删除 `https://leancloud.cn/docs/sns.html` 页面

**Comment by BinaryHB** [comment]
ref：https://github.com/leancloud/docs/pull/2623

**Comment by myleslee** [comment]
已更。
