### ISSUE TITLE
[feat]短信验证码的各种用法的整理以及 API 重命名

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2730]
## 问题来源

https://leanticket.cn/tickets/18476

## 当前的问题

手机号注册/手机号登录/手机号激活（verified  = ture）/操作行为验证（付款）/手机号重置密码这些场景我们都支持的，需要一个单独的 block 来介绍，这几种场景对应的流程和每一个流程应该调用的接口。

## API 的命名也有点不太友好

建议提供如下几个函数：

- `sendSignUpSmsCode`
- `signUpByMobilePhone`
- `sendLogInSmsCode`
- `logInByMobilePhone`

如上「专事专办」的接口。

**Comment by weakish** [comment]
@wujun4code 现在已经有 sms-guide，API 的整理可以去 paas 开个 issue
