### ISSUE TITLE
[新版文档 v3 UI 意见箱]

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2741]
## 预览地址

[leancloud-docs-v3-mkdocs/](https://wujun4code.github.io/leancloud-docs-v3-mkdocs/)

## 源码

[https://github.com/wujun4code/leancloud-docs-v3-mkdocs](https://github.com/wujun4code/leancloud-docs-v3-mkdocs)

### 文档的生成工具希望这一次能彻底切换

当前的复杂的各种框架掺杂在一起很难维护，多种奇技淫巧混合维护困难。

**Comment by hjiang** [comment]
这个新的版本是怎么生成的？

**Comment by nicecui** [comment]
想问下老版文档有什么问题，新版文档又是如何解决这些问题的？

**Comment by wujun4code** [comment]
> 这个新的版本是怎么生成的？

用 mkdocs 生成的

**Comment by wujun4code** [comment]
> 想问下老版文档有什么问题，新版文档又是如何解决这些问题的？

老版文档的问题到没有特别严重的，突出的几点我觉得不好用的地方在于：

1. 首页导航的产品划分已经与我们新版官网的划分不一致的
2. 单个文档的阅读的时候，针对当前产品没有一个相关的快捷导航，新版文档的左边 TOC 就是要解决这个问题，比如你在看存储的时候，关联了 AVUser，而 AVUser 又关联了 ACL，这个是存储产品内部的强关联， 所以在左边给出了一个 TOC 的链接导航，间接地也是排列了一个产品内部的子模块之间的关联。
3. 老版文档的杂音太多，例如 最佳实践和开发指南这两者打开的频率显然不在一个等级，不应该放在一起
4. REST API 不应该是个单独的分类，应该分列到各个产品中去（之前达成过共识）

总之，文档的大部分内容不会变化，只是首页导航/顶部 Tab 连接/单一文档产品的模块关联/左右 TOC 是这次修改的主要内容。

**Comment by jwfing** [comment]
首页里，把「平台与语言」感觉脉络更清晰一些。现在又有语言大类，又有功能/产品大类，所以看起来让人感觉有点乱。如果我们就坚持一个方向，应该也不会引起阅读或者查找障碍。

**Comment by wujun4code** [comment]
> 首页里，把「平台与语言」感觉脉络更清晰一些。现在又有语言大类，又有功能/产品大类，所以看起来让人感觉有点乱。如果我们就坚持一个方向，应该也不会引起阅读或者查找障碍。

并列的展示可以通过其他的前端手段来实现，例如给两个 Tab 按钮：按照语言/平台划分 | 按照产品划分，在同时存在的情况下，屏幕上只会有一种分类方式，我自己阅读文档的时候，在了解一个产品的完整形态（解决什么问题/我如何使用/接口长什么样子/SDK 怎么导入/产品子模块之间的关系）的时候是需要一个按照产品大类进行导航的功能，而实际上当我熟悉了一个产品（例如存储）之后，我后续的访问都会通过语言来快速定位。这一点我不知道其他工程师有没有共同的习惯和体验。

因此这个我觉得是前端的设计或者说是 UX 的活儿，我觉得这两个维度本质上不冲突，他们俩应该是并存的。

**Comment by jwfing** [comment]
如果同一功能的不同语言的文档，最后都在一起（通过 tab 切换），那么是不是就不会有「后续的访问都会通过语言来快速定位」这种便捷方式了？

**Comment by wujun4code** [comment]
> 如果同一功能的不同语言的文档，最后都在一起（通过 tab 切换），那么是不是就不会有「后续的访问都会通过语言来快速定位」这种便捷方式了？

那就缺少了另一个功能：我想知道用 js 在 leancloud 到底能开发哪些功能？我只会写 js，但是我需要通过每一个产品的介绍，看看这个产品支不支持 js sdk，这个就是一个非常难过的事情，比如我们的聊天根本不可能有 php 的客户端 sdk，这个就是按照语言列出该语言能覆盖的产品列表的功效。

**Comment by nicecui** [comment]
> 我想知道用 js 在 leancloud 到底能开发哪些功能？

我觉得这种场景很奇怪，一般用户都是：我要开发一个产品 => 这个产品有 XX 功能 => 看一下 LeanCloud 产品是否支持这个功能 => 这个产品用 JS 能不能写。

而不是：
我只会 JS => 我现在不知道自己要干啥 => 我要通过 LeanCloud JS 能写的产品来决定我要做啥。

> 按照产品分类，然后同一功能的不同语言的文档，最后都在一起（通过 tab 切换）

我也觉得产品和语言都放出来太混乱了，这种是一种比较好的方式，符合我们现在按产品划分的特点，同时也是主流场景。

**Comment by wujun4code** [comment]
> > 我想知道用 js 在 leancloud 到底能开发哪些功能？
> 
> 我觉得这种场景很奇怪，一般用户都是：我要开发一个产品 => 这个产品有 XX 功能 => 看一下 LeanCloud 产品是否支持这个功能 => 这个产品用 JS 能不能写。
> 
> 而不是：
> 我只会 JS => 我现在不知道自己要干啥 => 我要通过 LeanCloud JS 能写的产品来决定我要做啥。
> 
> 或者即使确实是从 JS 语言入手的，决策逻辑也应该是这样的：
> 我想写 Web 聊天 => 找一下 LeanCloud 有没有聊天 => 我用 JS 能不能写。
> 这个逻辑也是售前电话里面用户提问的一个流程。
> 
> > 按照产品分类，然后同一功能的不同语言的文档，最后都在一起（通过 tab 切换）
> 
> 我也觉得产品和语言都放出来太混乱了，这种是一种比较好的方式，符合我们现在按产品划分的特点，同时也是主流场景。

我举例的是，我知道 leancloud 有哪些产品了，但是我只会 js，我想找找，js 有咩有对应产品的 sdk ，这个时候如果有一个按照语言分类的列表，他一眼就可以看到 js 的列表里面包不包含这个产品。

另一个维度是，我不知道 leancloud 有哪些产品，我按照产品去看文档，看到一个我感兴趣的产品的时候，给出这个产品可以被哪些语言的 sdk 使用（这个我还没想好怎么在首页展示，让我想想）。

这就是一个表查询，通过表里面的不同的列值（key）查找单个 record 的需求，按照常用列值（key），分别展示。

**Comment by nicecui** [comment]
> 我知道 leancloud 有哪些产品了，但是我只会 js，我想找找，js 有咩有对应产品的 sdk 

我觉得这种逻辑情况下，我们把产品大大的标注出来，先在一堆产品中找即时通信，然后即使通信下再找 JS，两步完成。
如果按语言区分，就是先在一堆语言下找 JS，然后 JS 下找即时通信，也是两步。

如果找东西的步骤都是一样的，按照现在我们产品优先的原则，只按产品划分就可以了。

**Comment by wujun4code** [comment]
> > 我知道 leancloud 有哪些产品了，但是我只会 js，我想找找，js 有咩有对应产品的 sdk
> 
> 我觉得这种逻辑情况下，我们把产品大大的标注出来，先在一堆产品中找即时通信，然后即使通信下再找 JS，两步完成。
> 如果按语言区分，就是先在一堆语言下找 JS，然后 JS 下找即时通信，也是两步。
> 
> 如果找东西的步骤都是一样的，按照现在我们产品优先的原则，只按产品划分就可以了。
> 
> > 我不知道 leancloud 有哪些产品，我按照产品去看文档，看到一个我感兴趣的产品的时候，给出这个产品可以被哪些语言的 sdk 使用
> 
> 这个按产品划分就可以了，看起来没什么问题。

我不觉得这两种查找方式是彼此对立的，为什么有一种另外一种就必须被消灭？我上面也说了，这是两个 key-value 的查找方式，只是 key 不一样，不是每一个用户理解产品的方式是按照 LeanCloud 的产品划分来理解的，有一部分硬核工程师天生就喜欢按照语言/平台来查找，我们应该从服务的角度提供更多的查找方式，另外，我也说了，如果非要在同一时间只显示一种的话，也应该从前端 UX 的角度去设，而不是内容上就删除其中一种。

**Comment by nicecui** [comment]
我也觉得两种不是对立的，但给用户的信息应当只有一个重点，并且尽可能简单。

**Comment by jysperm** [comment]
建议当前文档内的小标题目录放在左边，相关的其他文档放在右边，调换一下

**Comment by jysperm** [comment]
mkdocs 是 Python 语言的么？我还是建议使用 JS 的工具链，本来文档项目就可以认为是一个前端项目，JS 的工具链会更丰富更好维护。

**Comment by wujun4code** [comment]
> 建议当前文档内的小标题目录放在左边，相关的其他文档放在右边，调换一下

我在上面提到了支持你这种，但是需要修改模板。

> mkdocs 是 Python 语言的么？我还是建议使用 JS 的工具链，本来文档项目就可以认为是一个前端项目，JS 的工具链会更丰富更好维护。

这个我调研过太多了，很少有能够 pk mkdocs 的工具，你看源码就是 md 毫无任何 js 脚本的情况下， 已经能生成长得不错的 docs 了，而其他的工具链都要重复地写一堆 html 和 css，我们做文档重点不是在工具链，而出产出的内容。

**Comment by jysperm** [comment]
我觉得不在于「默认情况下有多么简单」，而是在于后面对于奇奇怪怪的需求有多少支持能力，你有信心把我们现在的文档上的功能都改用 mkdocs 实现么？比如陈伟那个文档评论的功能。

> 已经能生成长得不错的 docs 了

我觉得文档的样式如何和文档生成工具是没有关系的，生成工具也不应该去管样式

> 要重复地写一堆 html 和 css

这是任何一个生成工具都可以解决的问题吧。确实之前的生成工具非常混乱，但我觉得这是因为长期缺乏（对生成工具本身）的维护导致的，切换到一个新的工具，如果不考虑后续的维护的话，并不会有什么改变。

**Comment by wujun4code** [comment]
> 我觉得不在于「默认情况下有多么简单」，而是在于后面对于奇奇怪怪的需求有多少支持能力，你有信心把我们现在的文档上的功能都改用 mkdocs 实现么？比如陈伟那个文档评论的功能。
> 
> > 已经能生成长得不错的 docs 了
> 
> 我觉得文档的样式如何和文档生成工具是没有关系的，生成工具也不应该去管样式
> 
> > 要重复地写一堆 html 和 css
> 
> 这是任何一个生成工具都可以解决的问题吧。确实之前的生成工具非常混乱，但我觉得这是因为长期缺乏（对生成工具本身）的维护导致的，切换到一个新的工具，如果不考虑后续的维护的话，并不会有什么改变。

所以我支持用 js 的工具链去生成最终的 md，正如我们现在做的这样，这没问题，你说的文档评论的功能，我觉得用 Gatsby 更好实现。

我偏向于 Gatsby 的主因也是在这货可以拓展更多动态的功能，本身就基于 React。我的优先级是 Gatsby > mkdocs > 当前 > 其他新工具。

**Comment by jwfing** [comment]
既然现在已经有三位同事对首页的组织有意见，我们是否可以以功能为主，同时也保留一个按照语言找文档的入口呢？我本地试了一下，大概会显示成这样子：
<img width="1062" alt="doc-v3-index" src="https://user-images.githubusercontent.com/985038/47554723-907a4f00-d93c-11e8-8602-649a2d143b6a.png">
应该可以让大部分浏览路径比较快捷，同时也照顾了一些特殊场景的入口。而且上线以后我们也可以通过 GA 的统计结果看到，究竟有多少用户走的是语言/平台找文档的这条路，如果有很多人这样做，我们可以把这种方式的权重调高一点。

**Comment by wujun4code** [comment]
我上面说到了这种方式，我这周来实现一下。

**Comment by jwfing** [comment]
mkdocs 有一个不好的地方，不能加 hidden page，所有要渲染的页面都需要出现在导航里面，这比较难搞。

**Comment by jysperm** [comment]
前几天，我、吴俊、李叶 讨论了关于生成工具的选择。吴俊想要使用 Gatsby；我是觉得不应该选择 Gatsby，而是应该选择更纯粹的生成工具，或者直接在老的生成工具上做修补；李叶的态度相对中立。

我们最后并没有达成什么结论，但我在这里简单列一下我的观点：

Gatsby 钦定了 React，这是没有必要的，一个生成工具不应该过多干涉运行时的行为。即使我们在文档中使用 React 也并不需要一个「支持 React 的生成工具」。Gatsby 钦定 React 可能会带来额外的麻烦，例如在 Gatsby 中需要用 React(JSX) 来写页面模板，这增加了修改页面模板的门槛（之前只是普通的 HTML 和 CSS），关键是并没有这个必要，React 并没有在构建阶段提供什么好处。

关于生成工具，我建议继续在原有的工具链上面做调整和精简，我觉得之前的工具链除了没有专人维护（切换一个生成工具并不能解决这个问题）之外，大的方向上是对的（生成工具不应该过多干涉运行时的行为，且保留足够的灵活性）。

**Comment by hjiang** [comment]
不管用什么，我就希望 toolchain 能简化一下。现在根目录构建相关的配置有：

- `Gruntfile.js`
- `Rakefile`
- `fabfile.py`
- `package.json`

涉及到三种语言四个构建工具，对维护的人来说门槛太高。

**Comment by hjiang** [comment]
有没有钦定 React 我倒是觉得不重要。毕竟 React 和普通 HTML/CSS 功能上是等价的，想不到有什么功能是一个可以实现而另一个不能的。有时为了做体验比较好的集成就会需要减少一些可订制的选项。对于维护的人来说如果在学习一个我们特有的很复杂的文档构建系统和学习 React 之间做选择，他肯定会选择更有价值的后者。

我没做过对其他工具的仔细调研，这里只是拿 Gatsby 来举个例子，我意思不是说我就支持用它，而是说在满足我们现在需要的功能的前提下，以简化流程为优先，避免 over-engineering.

**Comment by weakish** [comment]
> 现在根目录构建相关的配置有：
> 
>     * `Gruntfile.js`
> 
>     * `Rakefile`
> 
>     * `fabfile.py`
> 
>     * `package.json`
> 
> 
> 涉及到三种语言四个构建工具

`Gruntfile.js` 和 `package.json` 算一套 （grunt 和 npm），用于构建文档。

看上去 `Rakefile` 和 `fabfile.py` 是用来部署的，fabric 里是部署的逻辑，然后 rake 调用 fabric 实际部署到多个节点。　:scream: 

另外还有一个 `deploy.sh`，看起来是独立于上面 rake + fabric 的另一套部署逻辑，似乎是将生成的静态页面放到一个 git 仓库中管理，然后通过 push 到 remote 的方式部署。

这两套部署逻辑现在是同时使用么？还是说其中有一种已经不用了？

**Comment by weakish** [comment]
> 这两套部署逻辑现在是同时使用么？还是说其中有一种已经不用了？

经了解，现在用的是 `deploy.sh`，rake + fabric 已经不用了，这两天我会提 pr 把它们去掉。

另外补充一些 Zulip 上的相关讨论：

> 12月把新版文档和新的构建工具确定一下吧，我现在偏向于不太想动现在的构建工具了，但是精简 md 数量和根据不同语言生成纯静态的 html 方向不变，左右 TOC 和首页导航也会机基于上个月讨论做出调整

@wujun4code 

> 如果没有什么特别的原因要动就不用动了啊。文档最重要的还是内容。

@hjiang
