### ISSUE TITLE
[feat] 单一 md 根据不同语言/平台生成对应多份 html

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#2747]
## 需求描述

例如 `storage.md`在内容中有如下设置：

```
{{ languages=['js','java','objc','swift'] }}
```

将会生成如下几个 html:

```
storage.md
storage-js.html
storage-java.html
storage-objc.html
storage-swift.html
```

**Comment by fuchenshi** [comment]
目前英文文档已经在尝试类似的做法，把所有语言的代码都放在 `.tmpl` 文件下，然后依然会给每个语言建立一个 `.md` 文件，包含类似下面内容：

```
{% extends "./leanstorage_guide.tmpl" %}
{% set platform_name = "JavaScript" %}
```

这样在 `.tmpl` 文件里可以直接通过 `platform_name` 来切换针对当前语言显示的代码和叙述，像这样：

```
{% if platform_name === "JavaScript" %}
// Code here
{% endif %}
{% if platform_name === "Android" %}
// Code here
{% endif %}
```

这样做的话就暂时无需修改构建文档的程序，不过如果能想办法把每个语言的文件给剔除掉而只保留一个文件的话可以让目录看起来更简洁。

**Comment by weakish** [comment]
现在英文文档的结构，本质上就是单一源文件生成多份按语言分的文档：

- 所有的内容都在 topic.tmpl 下，不同语言主要依靠模板的 if else 结构支持
- topic-lang.md 只有两行，一行是继承 topic.tmpl，一行是指定当前 lang （赋值 `platform_name` 变量），除此以外没有其他新增内容

（这和单一源文件只有一步之遥，只需把 topic-lang.md 都去掉，只用 topic.tmpl —— 也可以改名成 topic.md　—— 然后编写相应的 grunt 任务。）

而中文文档的结构就比较复杂，以 topic.tmpl 为模板，topic-lang.md 继承 topic.tmpl，承袭其总结构以及其中的一些公共内容，然后加上语言特定的内容，而一些跨 topic 的内容，另外放在 _parts.html 等处，topic.tmpl 中 include，这就导致一些问题：

- 想要修改某个 SDK 的内容，很可能需要从 topic-lang.md 追溯到 topic.tmpl，并进一步追溯到 topic.tmpl 中 include 的文件，这个[追溯的过程比较费时][365258073f]，尤其是在不熟悉系统架构的情况下。同样，新增内容，也需要考虑到底放到哪个部分。

- 同样，因为同一段内容可能有三个以上物理位置，所以[出现重复][js]的时候不方便排查。

- 在编辑器中编辑 topic-lang.md 文档时，看不到继承自 topic.tmpl 乃至 topic.tmpl include 的很多内容，[很不方便]。

[365258073f]: https://github.com/leancloud/docs/commit/365258073f1204a66ae153a946b248b2dba1823d
[js]: https://github.com/leancloud/docs/blob/master/views/sdk_setup-js.md#%E9%AA%8C%E8%AF%81
[很不方便]: https://github.com/leancloud/docs/pull/2833#pullrequestreview-196924948

仅就上面两种方案而言，我觉得单一源文件的方案较优：

1. 文档架构应该尽可能简单，避免太多过于「智能」的逻辑
2. 现有的编辑器，并不能非常智能地展开继承的块，或者方便地在有 extend 或 include 关系的多份源文件之间跳转，所以把所有内容尽可能集中到一个源文件至少比较清楚。
3. 编写代码示例的时候，更方便参考其他语言的例子。需要对各语言的代码片段进行统一修改的时候，也更方便。

单一源文件的缺点：

1. 单个文件篇幅较大

    很多编辑器有 outline 和 fold 功能

2. 跨 topic 的文档块复用

    有必要的时候，仍可以在单一源文件中 `include` 其他文档块。另外，以 `include` 方式复用文档块宜慎用。比如开启 debug log 这块内容，从逻辑上说，和 SDK 安装关系最密切，应该放在相应的位置。其他文档页面可以用链接的方式引用，而不是在所有需要提到的地方生成一遍（这样编辑起来不能一目了然，而对从头到尾线性阅读文档的读者来说，也需要速读一过才能确定已经在其他地方读过了）。

**Comment by fuchenshi** [comment]
> 比如开启 debug log 这块内容，从逻辑上说，和 SDK 安装关系最密切，应该放在相应的位置。其他文档页面可以用链接的方式引用，而不是在所有需要提到的地方生成一遍

这部分我是这样理解的：

同样的内容只写一遍，把它放在最相关的文档内，其它文档如果需要让用户阅读相关内容，则用 `请参阅 [XX 指南](xx.html)` 这样的语言链接过来。

不知道我理解得是否准确……

**Comment by weakish** [comment]
嗯，链接到相应的 section（`XX.html#hashYY`）。不过这只是我个人的想法。

**Comment by jwfing** [comment]
大家可以体验一下现在新的 RTM 文档：https://leancloud.cn/docs/realtime_v2.html#hash745944513
我个人还是比较赞成这样的方式的：
- 所有语言都在一个文档里面，开发者可以根据自己的选择实时切换；
- 开发指南不是功能和 API 的罗列，而是会讲述更多的上下文，包括但不限于使用场景与具体需求、实现机制、注意事项，等等

而这样的文档，现在的工具也都是完全支持的（语言差异部分都可以在一份 md 文档里面描述，还是比较集中的）。

**Comment by weakish** [comment]
目前就保持现在的设计。
