### ISSUE TITLE
国际短信价格更新问题

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2774]
文档链接： https://leancloud.cn/docs/sms-guide.html#hash-228064280

**官网显示价格：**
65 | 新加坡 | SG | ￥ 0.42 | ￥ 0.42 | ￥ 0.42
92 | 巴基斯坦 | PK | ￥ 0.21 | ￥ 0.21 | ￥ 0.21
852 | 香港 | HK | ￥ 0.51 | ￥ 0.51 | ￥ 0.51
855 | 柬埔寨 | KH | ￥ 0.43 | ￥ 0.43 | ￥ 0.43
977 | 尼泊尔 | NP | ￥ 0.45 | ￥ 0.45 | ￥ 0.45

**@paomian 给出的当前的短信计费数据：**

```
(defonce ccc-price {"+34" 0.75, "+852" 0.53, "+58" 0.41, "+60" 0.34, "+977" 0.73, "+351" 0.43, "+57" 0.55, "+886" 0.46,
"+66" 0.34, "+856" 0.68, "+960" 0.11, "+855" 0.93, "+33" 0.64, "+7" 0.85, "+81" 0.68, "+39" 0.75, "+853" 0.27, "+30"
0.5, "+63" 0.37, "+40" 0.62, "+998" 0.73, "+1" 0.38, "+91" 0.09, "+27" 0.23, "+61" 0.48, "+971" 0.27, "+966" 0.31,
"+49" 0.72, "+54" 0.59, "+82" 0.4, "+92" 0.22, "+65" 0.43, "+90" 0.25, "+52" 0.42, "+62" 0.25, "+55" 0.48 "+86" (case
(config/api-env) :us 0.2 0.05) "+95" 1.10 "+44" 0.35})

```
**对比  @paomian 给出的数据，需要修改的价格如下：**

**新加坡 0.42 变为 0.43
巴基斯坦 0.21 变为 0.22
香港 0.51 变为 0.53
柬埔寨 0.43 变为 0.93
尼泊尔0.45 变为 0.73**

----
此处有一个疑问，「哈萨克斯坦」和 「俄罗斯」国号相同，如何判断这两个国家当前价格？同理，「美国」和「加拿大」如何区分？ @wujun4code  
![image](https://user-images.githubusercontent.com/11917002/48699216-e84a6400-ec23-11e8-9336-2d931b7a9708.png)

**Comment by wujun4code** [comment]
国号其实是运营商自己的编号，他们有自己的统一编号，发短信的时候这是一个短信运营商自己内部的参数，我们的开发者不用关心这个，只要按照要求传递，或者只传递国家代号就可以（具体问泡面），价格与这个参数无关。

**Comment by SXiaoXu** [comment]
@paomian 给出的数据是  "+7" 0.85，这个 0.85 元是现在的「哈萨克斯坦」还是 「俄罗斯」的单价呢？ @wujun4code

**Comment by paomian** [comment]
现在的价格就是 0.85

**Comment by SXiaoXu** [comment]
因为「哈萨克斯坦」和 「俄罗斯」之前是两个不同的价格， "+7" 0.85 是指「哈萨克斯坦」和 「俄罗斯」现在都是 0.85 吗？

**Comment by paomian** [comment]
对
