### ISSUE TITLE
Android 混合推送一处图片不正常显示

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/docs#2828]
文档地址：https://leancloud.cn/docs/android_mixpush_guide.html#hash1809538850
图片名称： /images/HMS-pushData.png

![image](https://user-images.githubusercontent.com/11917002/51595036-bc53a380-1f30-11e9-86b4-144b95b5a466.png)

**Comment by weakish** [comment]
奇怪，grunt 起的本地服务可以正常显示

![screenshot_2019-01-23 android - leancloud](https://user-images.githubusercontent.com/114114/51597524-671a9080-1f36-11e9-90a5-4baadbd88d26.png)
