### ISSUE TITLE
所有的request都出现url错误

### ISSUE THREAD

**Issue by LastMonopoly** [leancloud/docs#2844]
<img width="412" alt="format" src="https://user-images.githubusercontent.com/839799/52633859-9ce0e280-2f00-11e9-8e5a-5db5dc0fe74b.PNG">

我用的chrome 浏览器，关掉了所有 extension；
incognito 模式下一切正常

**Comment by weakish** [comment]
> incognito 模式下一切正常

估计是浏览器缓存的问题，今天下午合入的提交 5a1e0ba00202ec692459a7d1f7cc9e9f2f6378fd 涉及到 url，可能是您的浏览器缓存的过时 js 文件没有及时更新。建议清下缓存看看。

**Comment by LastMonopoly** [comment]
> > incognito 模式下一切正常
> 
> 估计是浏览器缓存的问题，今天下午合入的提交 [5a1e0ba](https://github.com/leancloud/docs/commit/5a1e0ba00202ec692459a7d1f7cc9e9f2f6378fd) 涉及到 url，可能是您的浏览器缓存的过时 js 文件没有及时更新。建议清下缓存看看。

确实是，谢谢你的及时回复
