### ISSUE TITLE
360chrome 9.5.0.130 ctrl+f 搜索，然后滚动、点击空白处等操作，然后搜索框会消失

### ISSUE THREAD

**Issue by yolio2003** [leancloud/docs#2845]
其他页面很少有这个现象，换了 chrome 也没有这个问题，
所以是 360chrome + leancloud 文档 特有的，
其中，这个版本的文档更新后 360chrome 多个版本 【中长期】都有这个问题！

**Comment by weakish** [comment]
Firefox 下也没有这个问题，看来是 360 浏览器的兼容性问题。360 浏览器目前不在优先兼容列表中，所以这个可能要暂时搁置了。

如果有 360 浏览器用户有意贡献兼容性代码，非常欢迎。
