### ISSUE TITLE
在 IM 创建 conversation 的所有示例中加上 `unique: true`

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#2858]
创建 conversation 时指定 `unique: true` 会导致成员相同的 conversation 被重用，这是适合大多数场景的用法，能大大减少 conversation 的数量，降低查询压力。目前我们的示例里大部分是没有这个参数的，开发者不容易看到。

在以后的 SDK 版本里这个参数会默认为 `true`。REST API 应该也会在某个时候改。

**Comment by hjiang** [comment]
@weakish @fuchenshi 因为中英文版都会涉及所以同时 assign 给你们了。

**Comment by fuchenshi** [comment]
https://github.com/leancloud/docs/tree/add-unique

给 JS 的先加上了。

**Comment by weakish** [comment]
当前进度：

- [x] 中文和英文的 js (by fuchenshi)
- [x] 英文的 java、objc
- [x] 中文 REST API 指南 #2874
- [ ] 中文 rtm 指南，延后（等 #2868 完成后，在重构的 rtm 指南上进行）

**Comment by jwfing** [comment]
@weakish https://github.com/leancloud/docs/pull/2868 这个已经上线了。
