### ISSUE TITLE
梳理文档的类型

### ISSUE THREAD

**Issue by weakish** [leancloud/docs#2859]
不计最佳实践和相关阅读，现有文档类型包括：

1. SDK 安装

    - 是否和快速入门合并？
    - 或者，并入指南（目前英文文档的做法）？ 

2. 快速入门

3. 指南

    新版指南（目前只有 LeanMessage 有），引入了以下变动：

    1. 结合具体的使用场景编写，而不仅仅是功能的罗列　:+1:

    2. 不按语言划分文档 （考虑到大多数开发者看代码示例的时候只关心某一个平台，还是旧版各语言分开比较好）

    3. 分为初、中、高三个部分：

        1. 是拆分三个部分还是旧版一份比较好？（从线性阅读的角度考虑，循序渐进也不错，但只有一份更方便查找）
        2. 初级和快速入门的关系，是否两者中只需保留一份？
        3. 中、高两部分是否合并？不合并的话按什么标准划分？　　　  

4. SDK API

    现在托管站点有 leancloud.cn/api-docs、readthedocs.io、leancloud.github.io，是否有必要统一放到一个站点？

**Comment by jwfing** [comment]
有些问题我解释一下。
>  不按语言划分文档 （考虑到大多数开发者看代码示例的时候只关心某一个平台，还是旧版各语言分开比较好）

做这个改动，主要的出发点并不是开发者看几个平台，而是因为我们功能越来越多，每一个功能还按照语言分为多个文档，导致首页的内容开起来比较凌乱，所以后来讨论的结果是，开发者上来应该首先是找功能，找到功能之后就进入专门的功能页面选择自己熟悉的语言/平台进行阅读，因此才简化了内容索引，并且把多个语言的文档放到了一起。

> 分为初、中、高三个部分

这里拆分的主要原因是，一份文档内容太长导致阅读压力增加，并且原来的单一文档基本都是功能的罗列，要想结合场景展开的话，就显得更长了，所以我们按照使用功能的深浅顺序拆分了多个文档。至于说初级和快速入门的关系以及是否需要合并，可能是你看错了，即时通讯这个模块下没有「快速入门」的文档。而「中、高两部分是否需要合并」，则需要根据他们的内容多少以及是否有递进关系来决定。
总的来说，多个层次分明的文档，其阅读效果是好过一份大文档的，这也是我们开始拆分以及拆分之后得到的明显的反馈。

**Comment by jwfing** [comment]
> 现在托管站点有 leancloud.cn/api-docs、readthedocs.io、leancloud.github.io，是否有必要统一放到一个站点？

现在这样分开，主要是由于各个 SDK 模块的发布流程和工具不一样导致的，并且这几个文档的风格也有较大差异，所以统一放到一起的必要性也不大 -- 看 api-doc 的开发者应该不多，同时看几份 api-doc 的人就更少了，所以这里没有必要投入太多精力来搬家。
