### ISSUE TITLE
整理 rtm 新版聊天文档，让首页只展示新版文档。

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#2861]

**Comment by nicecui** [comment]
最近也在弄聊天文档，同步一下发现的问题：
* 寻找内容困难：基础 - 进阶 - 高阶，这三个词太晦涩了，用户要找一个功能的话，还要自己先判断这个功能属于这三个当中的哪一个。
* 「自定义消息类型」模块，没有写内容。
* 没有「暂态消息」
* 文档底部，「高阶技巧」链接失效
*「 消息等级」仅对聊天室消息生效，却写在了统一的消息发送选项中。

总之，请仔细检查下每个功能点：
* 在文章结构中的位置是否合适。
* 描述是否准确。是否易于理解。
* 示例代码是否正确。

**Comment by weakish** [comment]
> 寻找内容困难：基础 - 进阶 - 高阶，这三个词太晦涩了，用户要找一个功能的话，还要自己先判断这个功能属于这三个当中的哪一个

#2859 里也有一些关于新旧指南形式讨论
