### ISSUE TITLE
修正国际短信价格

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2931]
https://leancloud.cn/docs/sms-guide.html#hash-228064280

这个文档需要做以下两件事：
1、把美国节点的价格换成美元，价格参考：https://github.com/leancloud/uluru-platform/blob/master/uluru-commons/resources/sms_pricing.json

2、4 月 3 日等后端发布后，增加新西兰国家

**Comment by weakish** [comment]
还要加下卡塔尔

**Comment by nicecui** [comment]
新西兰及卡塔尔均已更新在上面的文档中，新西兰 +64，卡塔尔 +974
