### ISSUE TITLE
集成 Android 推送设置默认启动的 Activity 后，点击消息栏无法启动 Activity

### ISSUE THREAD

**Issue by cjIsMyName** [leancloud/docs#3090]
通过 PushService.setDefaultPushCallback(this, MainActivity.class); 设置响应通知栏的点击事件，但是测试下来发现无效，请问哪里还有设置有问题？推送试了透传消息是可以的，但是显示通知栏后，点击通知栏无法调到应用内（此时应用是开启在后台运行的）
测试环境：小米系统  Android 系统 6.0

**Comment by jwfing** [comment]
请通过论坛或者工单来反馈问题。
