### ISSUE TITLE
更新 java unified sdk 文档

### ISSUE THREAD

**Issue by weakish** [leancloud/docs#3101]
java-unified-sdk 的 wiki 上有一些说明（主要是如何从老 android sdk 切换）。 目前存储部分拂尘已经初步完成。

其他有待更新。

**Comment by SXiaoXu** [comment]
java-unified-sdk 待更新的文档记录:

- [ ] **[Android 推送开发指南](https://leancloud.cn/docs/android_push_guide.html)** 
- [ ] **[Android 混合推送开发指南](https://leancloud.cn/docs/android_mixpush_guide.html)** 
- [ ] **[数据模型设计指南](https://leancloud.cn/docs/relation-guide.html)**
- [ ] **[ACL 权限管理开发指南](https://leancloud.cn/docs/acl-guide.html)**

其他待更新

- [ ] Android ChatKit 升级到新 SDK 然后更新文档。
- [ ] **[ChatKit 使用指南 · Android](https://leancloud.cn/docs/chatkit-android.html)**
