### ISSUE TITLE
应用内搜索指南独立成篇

### ISSUE THREAD

**Issue by weakish** [leancloud/docs#3113]
> https://leancloud.cn/docs/app_search_guide.html
> 感觉现在和「DeepLink」混在一起好奇怪
> 应用内搜索还是一个挺常用的功能，最好能单独出一个页面

-- jysperm on zulip

**Comment by jwfing** [comment]
deeplink 是应用内搜索结果的展示方式，放在一起来说还是可以的。只是需要把搜索相关的内容写得更详细一点就可以了。

**Comment by weakish** [comment]
closed in favor of #958

**Comment by weakish** [comment]
刚刚昆山这边讨论了下，现在应该很少人用 DeepLink 了，所以计划将 DeepLink 拆出来，作为最佳实践。
