### ISSUE TITLE
云代码指南中部分锚点不对

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#313]
https://leancloud.cn/docs/cloud_code_guide.html
里面「Cloud 函数」的锚点写成了 https://leancloud.cn/docs/cloud_code_guide.html#cloud-函数 ，应该是 https://leancloud.cn/docs/cloud_code_guide.html#Cloud_函数

**Comment by sdjcw** [comment]
有空帮忙看下这三篇文档：

* 新 Node.js 运行时： https://leancloud.cn/docs/leanengine_guide-node.html
* 新 Python 运行时：https://leancloud.cn/docs/leanengine_guide-python.html
* 云代码 2.0 https://leancloud.cn/docs/leanengine_guide-cloudcode.html

**Comment by myleslee** [comment]
好的
