### ISSUE TITLE
SDK 初始化文档更新

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/docs#3211]
ref: https://github.com/leancloud/paas/issues/1037

SDK 提供简化的设置 Server URL 的方法，然后文档跟进。

- [x] js （原来就有）
- [x] java
- [x] swift
- [x] objc
- [x] c#

**Comment by jwfing** [comment]
> SDK 提供简化的设置 Server URL 的方法

@zapcannon87 统一一下方法名吧：

**Comment by jwfing** [comment]
`setServerURLs` ？

**Comment by zapcannon87** [comment]
## 现状

### Objc 

只有配置单独模块的 API

```objc
[AVOSCloud setServerURLString:@"https://xxx.example.com" forServiceModule:AVServiceModuleAPI];
```

### Java / Android 

只有配置单独模块的 API

```java
AVOSCloud.setServer(AVOSService.API, "https://xxx.example.com");
```

### Swift

只有配置单独模块的 API

```swift
LCApplication.Configuration(customizedServers: [.api("https://xxx.example.com")]
```

### .Net

只有配置单独模块的 API

```csharp
new AVClient.Configuration {
	ApiServer = new Uri("https://xxx.example.com")
}
```

### JavaScript

既能配置单独模块的 API，也能统一配置所有模块（两者选其一）

```js
// 分模块配置
AV.init({
  appId: "{{appid}}",
  appKey: "{{appkey}}",
  serverURLs: {
  	api: "https://xxx.example.com"
  }
});
// 统一配置
AV.init({
  appId: "{{appid}}",
  appKey: "{{appkey}}",
  serverURLs: "https://xxx.example.com"
});
```

## 问题

* SDK 的模块（service）命名有歧义，比如 API 模块其实是对应存储服务
* 绝大多数用户是一个 URL 绑定所有服务，把同一个 URL 配置到多个模块，代码显得臃肿
* 以前的自定义域名 API 是为独立或私有部署服务的，不是必需配置项；未来国内节点的 App ID，App Key 以及 Server URL 是必需配置项

## 解决方案

### 现有方案分析

JavaScript SDK 目前的统一配置方式基本解决了上述三个问题：

* 没有 API 模块这种有歧义的参数
* 绑定所有服务的 URL 只用在初始化时配置一次
* App ID，App Key 以及 Server URL 需要在初始化时同时配置，体现了必需性

同时，还有其它优点：

* 保留了传统的「分模块配置」API，这样不影响国外节点以及独立或私有部署的用户
* 「分模块配置」和「统一配置」这两种方式是互斥的，用户只能选一种，避免的混用的风险

不太好的地方：

* 统一配置 URL 时，serverURLs 是 String 类型，参数的命名有点奇怪，一般来说 XXXs 对应的都是数组或合集这种类型。

### 结论

各 SDK 的最佳改动如下：

#### Objc

**增加 API**

```objc
[AVOSCloud setApplicationId:@"{{appid}}" clientKey:@"{{appkey}}" serverURLString:@"https://xxx.example.com"];
```

#### Java / Android

**增加 API**

```java
AVOSCloud.initialize("{{appid}}", "{{appkey}}", "https://xxx.example.com");
```

#### .Net

**增加 API**

```csharp
AVClient.Initialize("Eohx7L4EMfe4xmairXeT7q1w-gzGzoHsz", "GSBSGpYH9FsRdCss8TGQed0F", "https://xxx.example.com");
```

#### Swift

**现有 API 的参数支持**

```swift
LCApplication.default.set(
	id: "{{appid}}",
	key: "{{appkey}}",
	configuration: LCApplication.Configuration(customizedServers: "https://xxx.example.com")
)
```

@leeyeh @jwfing @onerain88

**Comment by zapcannon87** [comment]
基本上，是希望 API 如这样：`LeanCloud-SDK.init(app-id, app-key, serverURL)`

**Comment by jwfing** [comment]
java unified sdk 6.0.0 版本已经支持：https://github.com/leancloud/java-unified-sdk/releases/tag/leancloud-sdk-6.0.0

**Comment by weakish** [comment]
swift 17.0.0 已经支持（现在暂时还是 beta）
c# v20190925.1 已支持

**Comment by zapcannon87** [comment]
Swift SDK 的 API 不会变了，可以把文档的 PR 准备好。

```swift
do {
    try LCApplication.default.set(
        id: {{app-id}},
        key: {{app-key}},
        serverURL: {{app-server-url}})
} catch {
    print(error)
}
```

**Comment by zapcannon87** [comment]
Objc SDK 的代码已经调整完了（还未发版），可以把文档的 PR 准备好。

```objc
[AVOSCloud setApplicationId:{{app-id}} clientKey:{{app-key}} serverURLString:{{server-url}}];
```

**Comment by weakish** [comment]
似乎下午 objc 的 12.0.0 已经发布了

文档 pr 在 #3245

**Comment by zapcannon87** [comment]
Swift SDK 昨晚发布 17.0.0
