### ISSUE TITLE
增加敏感词过滤时，触发的方法

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#3254]
如果一个人发的消息被敏感词过滤了，那么 OnMessageUpdated 方法会被触发。

**Comment by weakish** [comment]
[消息的撤回和修改][edit] 章节有：

> 如果系统修改了消息（例如触发了内置的敏感词过滤功能，或者云引擎的 hook 函数），对话成员（包括发送者）同样会收到 AVIMClient.OnMessageModified 事件。

[edit]: https://leancloud.cn/docs/realtime-guide-intermediate.html#hash1993383390

不过这里 OnMessageModified 是很久以前 c# sdk 的事件，现在改成 OnMessageUpdated，稍后我另外提个 pr 更正一个。这个 issue 就先关掉了。

**Comment by nicecui** [comment]
这个章节是写消息的撤回和修改的，没有人会到这里找敏感词的信息的，敏感词应该单独再列一个小标题出来。
