### ISSUE TITLE
详细说明：云函数及 Hook 函数写到哪里

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#3289]
在线编辑或者 cloud.js 文件中。

目前文档没有对这里进行详细的说明，导致初次接触云引擎的用户不知道把函数写到哪。

**Comment by weakish** [comment]
@jysperm  我看 cloud.js 里又加载了 functions，要不要把 node-js-getting-started 里 cloud.js 中定义的 hello 也移到 functions 目录下，这样一个云函数对应一个文件，比较清楚？（也避免给初接触的用户太多选项，还要考虑到底是直接在 cloud.js 中写，还是到 functions 里写。）

**Comment by jysperm** [comment]
不太确定这样是否会更容易理解，如果没有太明显的收益的话我觉得还是不要改，因为我们有大量的文档和资料已经钦定云函数要写在 cloud.js 里了。

**Comment by weakish** [comment]
o.k.

**Comment by nicecui** [comment]
> 因为我们有大量的文档和资料已经钦定云函数要写在 cloud.js 里了。

并没有大量的文档和资料说明，新手看文档还是很难找到在 cloud.js 里面，这也是提出这个 issue 的原因。

**Comment by jysperm** [comment]
![image](https://user-images.githubusercontent.com/1191561/67832804-c177fb80-fb1d-11e9-9eaa-54593d91724d.png)

这里有写

https://leancloud.cn/docs/leanengine_cloudfunction_guide-node.html#hash20005220

**Comment by jysperm** [comment]
不过确实应该在入门指南里面提一下 

https://leancloud.cn/docs/leanengine_quickstart.html
