### ISSUE TITLE
ios 文档中没有说明 delegate 

### ISSUE THREAD

**Issue by weakish** [leancloud/docs#3331]
默认读者熟悉 delegate 模式

**Comment by zapcannon87** [comment]
像 [Delegation](https://en.wikipedia.org/wiki/Delegation_(object-oriented_programming)) 这种语言层级的特性，因为和 LeanCloud 的服务并没有太大关系，所以我认为没必要在文档里去说明它。

退一步，如果要加上说明链接，也倾向直接使用[官方文档](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/DelegatesandDataSources/DelegatesandDataSources.html)。

**Comment by nicecui** [comment]
赞同使用官方文档。

**Comment by zapcannon87** [comment]
SO 上面的高票回答不一定靠谱，比如[这个](https://stackoverflow.com/a/9372856/8756034)。

（不过这个 PR 已经被合并了，就先这样吧）

**Comment by weakish** [comment]
其实 js 文档还有一节介绍 promise 的…… 

因为 `client.delegate = delegator;` 实际上是伪代码，所以我觉得额外加个说明比较好。

原本我最初就是打算链接到 Apple 的文档，但是那个 url 比较长，所以我又找了一圈网上介绍 objc delegate 的文章，发现一个 SO 回答比较简洁，其中的参考链接中包括了官方文档，所以就用了这个。现在新提了个 pr 换到官方文档。
