### ISSUE TITLE
添加 setDefaultACL:withAccessForCurrentUser 的文档

### ISSUE THREAD

**Issue by tang3w** [leancloud/docs#341]

**Comment by zapcannon87** [comment]
> 感觉这个接口只是一个便利的封装（实际上可能也没便利到哪儿去），它的存在可能还会增加用户的理解成本。
目前只有 objc 有，那就按最小成本来处理，忽略这个接口，objc 的文档也按通用形式来，与其它 SDK 保持一致。

这个 issue 可以关了。

cc @weakish
