### ISSUE TITLE
fix(sms): 通过短信验证码验证手机号或重置密码需提供手机号参数

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/docs#3421]
* [通过短信验证码去验证手机号](https://leancloud.cn/docs/rest_sms_api.html#hash-1852874258)（1.1/verifyMobilePhone/收到的验证码）
* [通过短信验证码去重置密码](https://leancloud.cn/docs/rest_sms_api.html#hash-1895095901)（1.1/resetPasswordBySmsCode/收到的验证码）

上述接口，目前的文档均没有标明需提供手机号参数：`mobilePhoneNumber`。

根据 [API 的 PR](https://github.com/leancloud/uluru-platform/pull/3414)，当前应该是倾向请求的参数里携带 `mobilePhoneNumber` 的。

建议把缺省的 `mobilePhoneNumber` 参数补上。

**Comment by weakish** [comment]
记得上次问过 @paomian  是不需要的。leancloud/uluru-platform/pull#3414 处理的测试手机号这个例外情形，应该并没有体现带手机号的倾向。

**Comment by zapcannon87** [comment]
因为 Swift 短信接口的实现是需要用户提供手机号参数的，所以我在想是不是后来倾向让用户提供手机号参数。

@weakish 你再向泡面确认一下吧，如果**手机号参数并不倾向让用户来提供**，那就关了这个 issue。

**Comment by weakish** [comment]
@paomian ☝️

**Comment by weakish** [comment]
@zapcannon87 问了泡面，推荐是带。我来改下。
