### ISSUE TITLE
建议构建文件中增加对blob的示例；建议JS SDK安装指南中增加对uni-app的安装示例

### ISSUE THREAD

**Issue by CaoMeiYouRen** [leancloud/docs#3495]
建议 数据存储开发指南 · JavaScript-文件-构建文件 中增加对blob的示例
我看了下文档中并没有关于用blob来构建AV.File的方式，还是翻lssues找到的。就像这样
```
new AV.File (name, {blob: {uri: "xxxxx"}});
```

另外建议JavaScript SDK 安装指南中增加对uni-app的安装示例
uni-app：https://uniapp.dcloud.io/
经过测试安装方式和微信小程序一致【而且由于uni-app对微信小程序的兼容，所以可以全端使用】
```
const AV = require('leancloud-storage/libs/av-weapp-min.js');
//或
import AV from 'leancloud-storage/dist/av-weapp.js';
```

**Comment by weakish** [comment]
感谢建议，会在文档加上 `{blob: {uri}` 的示例。

我们尚未充分测试 uni-app 和 leancloud sdk 的兼容性，现在暂时不会在 SDK 指南中加入 uni-app 的说明。欢迎去[论坛][forum]分享使用 uni-app 的心得。

[forum]: https://forum.leancloud.cn/c/ji-zhu-fen-xiang/34-category

**Comment by CaoMeiYouRen** [comment]
> 感谢建议，会在文档加上 `{blob: {uri}` 的示例。
> 
> 我们尚未充分测试 uni-app 和 leancloud sdk 的兼容性，现在暂时不会在 SDK 指南中加入 uni-app 的说明。欢迎去[论坛](https://forum.leancloud.cn/c/ji-zhu-fen-xiang/34-category)分享使用 uni-app 的心得。

了解
