### ISSUE TITLE
feat(storage): exclude keys when fetching

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/docs#3521]
## 需求

[zulip](https://zulip.leancloud.tk/#narrow/stream/12-sdk/topic/js.20fetch.20keys), [forum](https://forum.leancloud.cn/t/createdat-updatedat/22505)

## 建议

@weakish 考虑一下需不需要在文档中添加相关的示例代码。

**Comment by weakish** [comment]
之前已经加上了 #3516

**Comment by zapcannon87** [comment]
我的意思是给 SDK 的存储指南也加上？
