### ISSUE TITLE
按照README说明安装失败

### ISSUE THREAD

**Issue by Daxing** [leancloud/docs#353]
我在多个开发环境中按照README安装，都出现一下错误，求解答。

AppledeMacBook-Pro:web stephen$ npm install
npm WARN package.json avoscloud-docs@0.0.0 license should be a valid SPDX license expression
npm WARN unmet dependency /Users/stephen/mygit/help_center/web/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars-helpers requires lodash@'~2.2.1' but will load
npm WARN unmet dependency /Users/stephen/mygit/help_center/web/node_modules/assemble/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.2
grunt-nunjucks@0.1.3 node_modules/grunt-nunjucks
AppledeMacBook-Pro:web stephen$ npm ls 
npm WARN unmet dependency /Users/stephen/mygit/help_center/web/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars-helpers requires lodash@'~2.2.1' but will load
npm WARN unmet dependency /Users/stephen/mygit/help_center/web/node_modules/assemble/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.2

**Comment by Daxing** [comment]
能否提高更详细环境配置说明，软件版本号，依赖库等等。

**Comment by hjiang** [comment]
请问是在云代码项目中安装依赖出现的问题吗？

@aisk @sdjcw

**Comment by Daxing** [comment]
本地mac和阿里云的ubuntu

**Comment by aisk** [comment]
只是 warning，项目应该可以运行。另外您要在本地跑 docs 项目的话，应该是用 npm install --dev

**Comment by Daxing** [comment]
谢谢，我修改了一下几个package.json里依赖库的版本号，就可以了。

**Comment by myleslee** [comment]
我遇到了类似的错误，安龙做了修改，我同步到本地后，可以成功部署。
