### ISSUE TITLE
黑名单和禁言只支持 m.count > 2 的会话

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/docs#3545]
## 背景

[zulip 讨论](https://zulip.lcops.cn/#narrow/stream/12-sdk/topic/rtm.20.E7.AD.94.E7.96.91/near/2020640)

## 建议

[即时通讯文档](https://leancloud.cn/docs/realtime-guide-senior.html#hash-1219710371)把这个限制条件补充上

**Comment by weakish** [comment]
这个限制已经在 leancloud/avoscloud-push#2611 中去掉了
