### ISSUE TITLE
即时通讯文档对话自定义属性表不统一

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/docs#3582]
https://leancloud.cn/docs/realtime-guide-beginner.html#hash-1197882253

各 SDK 显示的表不一样，需要统一一下。例如有的 SDK 有 `attr` 这个字段，有的 SDK 没有。

**Comment by weakish** [comment]
`attr` 等字段缺失，有的是因为相应 SDK 没有实现，有的是这个表漏掉了。我在 #3584 里补充了下（另外顺序也重排了下，和 sdk api doc 或源码的声明顺序保持一致，以便对照）。
