### ISSUE TITLE
《即时通讯开发指南（V2）》写明 realtime 的创建过程

### ISSUE THREAD

**Issue by sdjdd** [leancloud/docs#3594]
[一，从简单的单聊、群聊、收发图文消息开始](https://leancloud.cn/docs/realtime-guide-beginner.html) 中未提及 `realtime` 是如何创建的，感觉会给第一次使用的用户造成一定的困惑。

加上
```js
const realtime = new Realtime({
  appId: "{{appid}}",
  appKey: "{{appkey}}",
  server: "https://please-replace-with-your-customized.domain.com",
});
```
会不会好一些。

**Comment by weakish** [comment]
前面「阅读准备」里提到需要先「完成 SDK 安装与初始化」。我再在这一段代码上面加了一个指向 SDK 配置指南的链接 #3597

**Comment by sdjdd** [comment]
> 前面「阅读准备」里提到需要先「完成 SDK 安装与初始化」。我再在这一段代码上面加了一个指向 SDK 配置指南的链接 #3597

嗯，这块我没看仔细。其实「创建 IMClient 」和 「阅读准备」离得挺近的，不加也可以。
