### ISSUE TITLE
多语言调用 REST API 示范文档

### ISSUE THREAD

**Issue by killme2008** [leancloud/docs#37]

**Comment by wujun4code** [comment]
http://docs.wujun.apiary.io/#reference/0/-leanstorage/0
目前在这里生成实例代码。但是它默认的模板不好，会酌情修改。

**Comment by weakish** [comment]
手工维护的话成本太高。

像 postman 和 insomnia 之类的工具都支持粘贴 curl，自动生成各种语言的代码。
所以我打算在文档中提一下，让开发者自己生成。
文档里就不用再通过工具自动生成一遍了。
