### ISSUE TITLE
搜索结果有问题

### ISSUE THREAD

**Issue by wangxiao** [leancloud/docs#381]
搜索「发票」

https://leancloud.cn/search.html?q=%E5%8F%91%E7%A5%A8
这个搜索结果第一个页面是 404

**Comment by myleslee** [comment]
@wangxiao 现在有结果了，不 404 了，其他搜索关键字也没问题，应该是修复了吧？

**Comment by wangxiao** [comment]
没有。就是搜索这个关键字结果不太对。

**Comment by wangxiao** [comment]
@sunchanglong 大龙有时间看下。
