### ISSUE TITLE
安全文档应增加对系统特殊表的说明

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#384]
系统表指 `_` 开头的表，需要解答：
1. 用户是否仍有责任对这些表设置 ACL 来保证基本的安全，还是系统有合理的默认设定。
2. 用户设置 ACL 或者对客户端隐藏部分列后，是否会对登录、关注等系统功能造成影响。

**Comment by shifuchen98** [comment]
感觉有一个需要提醒用户的点就是现在 `_User` 表各字段的「只限所属用户读写」默认是关闭的，所以未登录一个账户的情况下也是能够获取这个账户的很多信息的。

**Comment by weakish** [comment]
> 感觉有一个需要提醒用户的点就是现在 `_User` 表各字段的「只限所属用户读写」默认是关闭的，所以未登录一个账户的情况下也是能够获取这个账户的很多信息的。

class 权限那里禁掉了查询，也算是有基本的安全保障（前提是 objectId 没有被泄露）。
