### ISSUE TITLE
Android 混淆的章节怎么没有了

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#390]
@lbt05 @myleslee

**Comment by lzwjava** [comment]
看到了 ，在FAQ 中，但有点隐藏

https://github.com/leancloud/docs/commit/e1d6561f021aaad99f14eb02f4869bab18b99f75

**Comment by lzwjava** [comment]
希望能加个链接 @myleslee

**Comment by myleslee** [comment]
嗯对，加个链接是对的。87c4ffe101
