### ISSUE TITLE
文档评论应该有集中展示、管理的页面

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#393]
现在用户添加了评论，工程师没法及时知道。希望可以做到如下几点：
1，一览列出用户的评论（时间序），包括关联文档、具体段落、评论内容；
2，可以人工管理用户评论，譬如可以标注已解决（顺带给用户发一封站内短信，告知结果，表示感谢），可以删除一些灌水的评论；
3，我们可以形成一个制度，每周统计、分析一下用户评论，列一个以周为单位的改进计划（指出文档 bug 的除外）；

**Comment by myleslee** [comment]
嗯目前我在用离线数据来得到一些必要信息。陈伟也在进行上面的一些工作。@sdjcw
![Image of Query Result](http://ac-lhzo7z96.clouddn.com/1436753587300)

**Comment by sdjcw** [comment]
我是打算这周抽点时间做个控制台的。

**Comment by myleslee** [comment]
- 增加分配给工程师的功能，可以把留言内容、文档名称和段落直接转发出去，省得每次要发截屏给工程师，好让他们知道要修改的确切地方。
- 增加留言的处理状态，如「未处理、处理中、完成」，象工单一样，这样不让「已完成」的留言出现在队列中。

**Comment by hjiang** [comment]
分配给工程师 - 其实只要做成可以一键把评论转化为 GitHub issue 就行。

Da Li <notifications@github.com>于2015年7月30日 周四上午11:17写道：

**Comment by myleslee** [comment]
@hjiang 嗯对，转成 issue。

**Comment by sdjcw** [comment]
以后评论插件相关在 https://github.com/leancloud/doc-comment/issues 讨论。上面的需求已经建立 issue：
https://github.com/leancloud/doc-comment/issues/8
https://github.com/leancloud/doc-comment/issues/9

这个我就先关闭了。
