### ISSUE TITLE
文档模板编辑器需求

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#417]
1. 编辑时，可以渲染 MD 样式
2. Block 底色与 TMPL 模板区分
3. 一个默认的目标渲染的选项
4. Block 行内与段落的区分
5. Block Id 优化显示和输入
6. 默认描述需要在编辑时显示出来

**Comment by wujun4code** [comment]
@wangxiao

**Comment by wangxiao** [comment]
好的，先记录在此，感觉 Demo 的优先级会更高一点。
