### ISSUE TITLE
iOS SDK 3.1.2.7 版本 podspec 文件有问题

### ISSUE THREAD

**Issue by candyan** [leancloud/docs#422]
3.1.2.7 的 podspec .a 没有导入进去。
3.1.2.6 的 podspec 所有的.h 文件 都木有找到。

以下这两个是我重写的。我这边试了可以用
https://gist.github.com/candyan/24e6878c40b6371b8772
https://gist.github.com/candyan/30e5039bb997b737610f

**Comment by myleslee** [comment]
@tang3w @jwfing, please help verify if this is an issue. Thank you!

**Comment by tang3w** [comment]
「3.1.2.7 的 podspec .a 没有导入进去」，能否描述一下重现的步骤？
「3.1.2.6 的 podspec 所有的.h 文件 都木有找到」，目前已经在 3.1.2.7 中修复了。

你应该是使用 0.38 吧？我测试下来，使用 0.38.0.beta.2 安装，没有出现 .a 文件没有导入进去的情况。

能否描述一下第一个问题的重新步骤？包括 CocoaPods 的版本，以及如果可能的话，提供一下 Podfile 吧，感谢！

**Comment by myleslee** [comment]
@candyan 可否按上面 tang3w 的描述提供更多信息？

**Comment by candyan** [comment]
是滴。。。0.38

**Comment by tang3w** [comment]
能告知一下对 podspec 都做了哪些关键的改动？

**Comment by candyan** [comment]
直接使用了 "vendored_frameworks" = AVOSCloudIM.framework

而不是用 .a 和 .h (因为你们直接提供的是 '.framework')。

**Comment by tang3w** [comment]
你好，我们提供的 .framework 包含了静态库（.a 文件）的，CocoaPods 安装的时候会拷贝出来。

我们再确认一下什么问题吧，谢谢反馈。

**Comment by candyan** [comment]
OK。。你们再看看吧。。。虽然我不太理解你们为啥非要把 .framework 里面的  .a copy出来单独使用，而不直接使用 .framework 。如果你们想使用 .a 和 .h 应该在 jenkins build 完之后 就把 .a 和 .h 提取出来 之后把 .a 和 .h zip 成一个包。
