### ISSUE TITLE
中文正文采用兰亭黑（OS X）

### ISSUE THREAD

**Issue by sparanoid** [leancloud/docs#452]
原讨论 https://github.com/leancloud/avfr/issues/406

**Comment by myleslee** [comment]
字体效果挺好！

段落间距现在只有 10px，分段看起来不很明显。下面是 margin-bottom 为 10px 和 1.5em 的对比：
<hr>
<img width="894" alt="screen shot 2015-08-12 at 11 21 00" src="https://cloud.githubusercontent.com/assets/108758/9215950/6b9c0c4e-40e4-11e5-9d85-05f78c32fabe.png">
<hr>

<img width="898" alt="screen shot 2015-08-12 at 11 20 27" src="https://cloud.githubusercontent.com/assets/108758/9215949/6b9978c6-40e4-11e5-9567-0d5d859581f3.png">

**Comment by wangxiao** [comment]
😳 兰亭黑会显得宽一点，和我写字风格挺像。。。我也很喜欢。。。
