### ISSUE TITLE
代码块最后多一个换行，导致粘贴到命令行终端时立刻执行

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#456]
图示地方多了一个空行：
![image](https://cloud.githubusercontent.com/assets/5022872/9191319/4f5ca7d0-4032-11e5-8a08-e64183bc9730.png)

下面我只用了 Command+V 粘贴了就马上执行了，不能编辑后再执行：

![image](https://cloud.githubusercontent.com/assets/5022872/9191327/7eccd7b0-4032-11e5-9a62-eda4d428968f.png)

原因是代码块最后面多了个换行。

很多时候需要确认一下再执行，比如这里改掉 `gid`，再或者改掉class。

有时操作又是危险的，比如创建某个对象，这样一粘贴就马上执行了，可能污染开发者线上的数据。

希望达叔有空的时候都能批量改过来，Thanks~

@myleslee

**Comment by myleslee** [comment]
嗯这一点发现得好！

看了一下，这跟 Markdown 关系不大，在 MD 源码中本来就没有换行，换行可能是在前端渲染（prettyprint）时自动加入了一行 `<span class="pln"> </span>`（接下来是切换应用的下拉菜单）。

给前端提了一个 [issue #415](https://github.com/leancloud/avfr/issues/415)。

**Comment by myleslee** [comment]
#415 已解决。
