### ISSUE TITLE
短信签名不允许特殊字符，文档中没有写出

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#478]
https://forum.leancloud.cn/t/topic/1555
https://leancloud.cn/docs/error_code.html#_600

**Comment by myleslee** [comment]
@killme2008 @paomian 请求补充文档。

**Comment by wujun4code** [comment]
@myleslee 我跟泡面会在本月合作一起写一个短信的专门的文档，把短信模板，短信发送，发送查错等详细介绍一下。单独分离出来会好一点。毕竟短信已经成为我们一个不能忽视的模块。

**Comment by myleslee** [comment]
文档己做分离和必要补充。
