### ISSUE TITLE
@engine.cloud_code会导致部署失败，改为@engine.define就没有问题

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#480]
云引擎Python，定时任务：
@engine.cloud_code
def log_timer():
    print 'Log in timer.'

@engine.cloud_code会导致部署失败，改为@engine.define就没有问题

**Comment by aisk** [comment]
全局搜了一下，没有 @cloud_code 的文档。

**Comment by nicecui** [comment]
@aisk https://leancloud.cn/docs/leanengine_guide-python.html#定时任务

**Comment by aisk** [comment]
漏掉了 views 目录，sorry…… 🙏
