### ISSUE TITLE
iOS实时通信-群组聊天-成员管理-邀请成员，代码片段中的else少了“}”

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#497]
iOS实时通信-群组聊天-成员管理-邀请成员，代码片段中的else少了“}”

**Comment by myleslee** [comment]
@nicecui 下回可以直接将离问题点最近的链接贴出来，比如：<https://leancloud.cn/docs/ios_realtime_v2.html#成员管理>

己修复。
