### ISSUE TITLE
Android查询AVQuery<AVObject>，漏掉了<AVObject>

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#520]
https://leancloud.cn/docs/android_guide.html#%E6%9F%A5%E8%AF%A2%E6%9D%A1%E4%BB%B6
查询字符串中包含“XX“内容，可用如下方法：
AVQuery query = new AVQuery("Post");
需要修改为
AVQuery<AVObject> query = new AVQuery<AVObject>("Post");

否则在findinbackground的callBack中会自动调用
@Override
protected void internalDone0(Object o, AVException e) {
}

**Comment by myleslee** [comment]
@lbt05 请核实。

`AVQuery query = new AVQuery("Post");` 
需要修改为：
`AVQuery<AVObject> query = new AVQuery<AVObject>("Post");`

Thanks.

**Comment by lbt05** [comment]
internalDone0不要重载啊。。。。

**Comment by lbt05** [comment]
AVQuery<AVObject> query = new AVQuery<AVObject>("Post");
和
AVQuery query = new AVQuery("Post"); 

其实都可以

**Comment by nicecui** [comment]
如果没有<>中的AVObject，除了Done方法外，编译器还会自动补全internalDone0这个方法。

**Comment by lbt05** [comment]
protected void internalDone0(Object o 这个地方的自动填充是由FindCallback的Generic来决定的。
写成这样试试看 
andQuery.findInBackground(new FindCallback<AVObject>()

**Comment by nicecui** [comment]
嗯，明白。只是略担心会对用户造成影响。
