### ISSUE TITLE
评论鼠标经过自动展开，鼠标离开自动收起

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#533]
现在是：

![normal](https://cloud.githubusercontent.com/assets/5022872/9867292/838a9166-5b9e-11e5-94c7-e9ebf5d95425.gif)

类似这样的效果(或者向下弹出)：

![wechatgif](https://cloud.githubusercontent.com/assets/5022872/9867197/82381546-5b9d-11e5-8627-77ce7aae64fe.gif)

因为移动到评论的图标上方，很大几率就是要点开评论的。自动展开的体验相对要好一些。要关闭的话，任意方向移开即可，操作稍微快些。

评论一多，这样的体验感觉更轻快便捷一些。

可以体验一下，每个段落几乎都有评论，所以需要更便捷的方式：https://leancloud.cn/docs/ios_os_x_guide.html

其实可以的话，评论搞成弹幕也不错 ^ 页面上附加一个弹幕的开关。

@sdjcw @sunchanglong

**Comment by sdjcw** [comment]
不太建议鼠标移动上去直接展现，因为可能存在评论很多需要滚动条，还有需要复制评论里面内容（比如代码）的场景。

我建议鼠标点击弹出，然后点击外面自动关闭评论框，而不是非要点击评论框右上角的 X，这样有点太强制了。

至于弹幕还是算了吧。。显得太过于娱乐了。

另外，评论越来越多了，所以评论图标蓝色有点抢眼了，很容易抢夺用户的注意力，记得之前浅灰色的一版蛮漂亮的。 @sparanoid

**Comment by myleslee** [comment]
同意。或者「ESC 键关闭窗口」。

**Comment by myleslee** [comment]
[Medium 的方式](https://medium.com/life-learning/how-to-get-any-job-you-want-even-if-you-re-unqualified-6f49a65f5491#.qqoeuh6s9)：

<img width="849" alt="screen_shot_2015-10-26_at_11_57_30" src="https://cloud.githubusercontent.com/assets/108758/10721081/01dacdba-7bd9-11e5-8184-bab0657a201c.png">

--------------

<img width="987" alt="screen shot 2015-10-26 at 11 57 45" src="https://cloud.githubusercontent.com/assets/108758/10721082/01dbe83a-7bd9-11e5-8397-096a4f05adf3.png">

**Comment by sparanoid** [comment]
> 另外，评论越来越多了，所以评论图标蓝色有点抢眼了，很容易抢夺用户的注意力，记得之前浅灰色的一版蛮漂亮的。 @sparanoid

之前 @kadashu 觉得太不直观了，我才变成现在这个颜色的，你们不要这样……
