### ISSUE TITLE
聊天文档需要跟进新功能

### ISSUE THREAD

**Issue by wujun4code** [leancloud/docs#542]
1. 单点登录（必做）
2. 原子创建对话（必做）
3. 消息缓存的全局开关是否提及？假如提及了缓存开关是否要针对缓存内容的解释，比如存了哪些，缓存存储策略以及存储策略是否解释？（需要讨论）@jwfing @tang3w @lbt05 

关于第 3 点，我个人建议是

***需要解释的***
* 缓存全局开关
* 聊天记录有缓存，目的是为了减少流量。

***不解释的***
* 不解释缓存同步的算法
* 不公开表结构
* 不提及 sqlite

**Comment by jwfing** [comment]
还有以下内容需要补充说明一下：
1，系统对话
2，离线消息（Android）
3，遍历历史消息（从服务器获取，从缓存获取）
4，conversation 的本地存储——用在保存最近对话列表上
5，setTimeoutIntervalInSeconds
6，iOS：使用 AVIMConversationUpdateBuilder 来更新对话的属性
7，iOS：富媒体消息中增加文件消息
8，获取在线成员列表

**Comment by jwfing** [comment]
对于缓存的说明，同意吴骏的方案。

**Comment by wujun4code** [comment]
已完结
