### ISSUE TITLE
短信收发常见问题一览，链接失效

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#555]
https://leancloud.cn/docs/android_sms_guide.html#常见问题
https://leancloud.cn/docs/ios_os_x_sms_guide.html#常见问题
https://leancloud.cn/docs/js_sms_guide.html#常见问题

常见问题一览，短信问题的链接全部失效，
修改为：
https://leancloud.cn/docs/rest_sms_api.html#常见问题_FAQ

**Comment by jwfing** [comment]
没有失效啊，只是全部统一指向一个地方了。

**Comment by nicecui** [comment]
现在的指向是这个：
https://leancloud.cn/rest_sms_api.html#/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98_FAQ

**Comment by nicecui** [comment]
点击“短信收发常见问题一览”，打开的是404页面

**Comment by myleslee** [comment]
嗯原始链接中不应该加 / 。已改正。
