### ISSUE TITLE
[LeanEngine] 本地运行，报 401 Unauthorized 错误（来自文档评论）

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#562]
<https://leancloud.cn/docs/leanengine_guide-node.html#本地运行>

<img width="367" alt="screen shot 2015-10-09 at 11 17 39" src="https://cloud.githubusercontent.com/assets/108758/10385131/73ba7a12-6e77-11e5-8230-b38c6e388fb9.png">

**Comment by myleslee** [comment]
<img width="365" alt="screen shot 2015-10-12 at 17 14 24" src="https://cloud.githubusercontent.com/assets/108758/10424789/c3c6a730-7104-11e5-8f75-9e2e9576969c.png">

新留言 @sdjcw @aisk

**Comment by sdjcw** [comment]
这个问题的原因是这样的：
1，因为需要部署等操作，所以命令行工具需要用户输入 masterKey
2，因为为了方便，所以我们只要用户输入 appId 和 masterKey 就可以启动并调试应用，再输入一个 appKey 显得很麻烦，而且 masterKey 这个更高权限的 key 都给了，appKey 可以省略。
3，因为 masterKey 可以当作 appKey 来使用，所以我们很多和服务器的交互直接使用 masterKey 是没问题的。
4，但是问题来了，文档上列出来的 curl 命令，其实是给了 appId 和 appKey 作为鉴权信息，又因为上面的原因，应用启动时没有收集 appKey，而是使用 masterKey 当作 appKey，所以鉴权失败（因为用户给的 appKey 和应用内部初始化用的 appKey 不一样）

解决办法有两个：
1，让用户再输入个 appKey
2，用户输入 masterKey 后，命令行通过 appId 和 masterKey 去查询下 appKey，并保存本地。

个人建议第二个方案，不过我们需要费点劲提供一个接口。

**Comment by myleslee** [comment]
在接口实现之前，先用第一个方法吧，不报错就行，用户多输一次 appKey 应该不是大事。

等接口实现以后，再把文档 curl 改回来。 @jwfing @sdjcw @aisk

**Comment by myleslee** [comment]
命令行工具升级为 0.9.1 之后的版本就不会 Unauthorized 了。实施了方案二。@sdjcw 威武！

**Comment by sdjcw** [comment]
是 @jysperm 实现的，子亭威武！
