### ISSUE TITLE
文档中出现parseObjects，parseException是不是不太合适？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#564]
https://leancloud.cn/docs/status_system.html#获取收件箱状态
public void done(final List<AVStatus> parseObjects, final AVException parseException) {}

**Comment by hjiang** [comment]
确实，以前的例子使用了这些命名，应该改过来。

**Comment by myleslee** [comment]
是不合适，一直在努力消灭呵呵。已修复。PR #565
