### ISSUE TITLE
把当前页面的所有 contributor 及最近 contributor 的头像自动放在页脚

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#580]
一个低优先级的小 feature，鼓励 pull request。

**Comment by sparanoid** [comment]
放在哪个页面的页脚？会很多的吧？

**Comment by hjiang** [comment]
就是读者看的当前这篇文档的页脚。改过一篇文档的人应该不会很多，而且可以显示得紧凑一些。就是不知道好不好实现。

**Comment by sparanoid** [comment]
最开始我想的是可以用 `git` 命令来做，但只能取到名字和邮箱

所以我觉得可能要 GitHub 的 API 来取头像，比如：

https://api.github.com/repos/leancloud/docs/commits?path=README.md

如果是渲染的时候直接生成的话，我觉得构建过程估计会很慢

但直接前端调用 GitHub API 的话，国内的速度似乎会有问题

/cc @sunchanglong @wangxiao

**Comment by hjiang** [comment]
嗯，这个不急，没其他事的时候可以作为一个好玩的事情来做。

**Comment by lzwjava** [comment]
可以的话，在页脚能加如一个`最近变更` 的链接，链接到 github 上针对于这个文件的 commits 记录。

比如 iOS 指南的文档，可以链接到 https://github.com/leancloud/docs/commits/master/md/ios_os_x_guide.md

方便开发者看到最近的改动。

比如开发者升级到了 iOS 9 然后出了些问题，我们把 iOS 9 适配指南更新到了存储文档里，但这段文字和其它文字混在一起，没有太突出，不好找。

有最近改动的链接的话，开发者就容易去看，从而快速看到最近的改动。也可以确认一下我们有没有对文档进行更新。

**Comment by sparanoid** [comment]
@lzwjava 其实现在还有一个问题，是某次改进引入的，我记得部分文档是根据模板自动生成的，比如某一功能的不同平台的实现，这种文档就就没办法取到 commits 记录、contributor 这些信息了

**Comment by lzwjava** [comment]
其实还好，对这些情况特别判断一下就行了。

Gitignore 里有这些：
```
md/leanengine_guide-cloudcode.md
md/leanengine_guide-node.md
md/leanengine_guide-python.md

.idea
md/realtime_guide-android.md
md/realtime_guide-dotnet.md
md/realtime_guide-ios.md
md/realtime_guide-js.md

md/acl_guide-android.md
md/acl_guide-ios.md
md/acl_guide-js.md
md/acl_guide-python.md

md/acl_quick_start-android.md
md/acl_quick_start-ios.md
md/acl_quick_start-js.md
```

判断是否在此文档是否存在于 gitignore 。如果存在，则在 views 文件夹中，`md/acl_quick_start-android.md` 变成 `views/acl_quick_start-android.md`

`md/acl_quick_start-android.md`  应该是由 `md/acl_quick_start.md` 与 `md/acl_quick_start.tmpl` 合成的。可以简单一点，不考虑 tmpl 的改动。

**Comment by sparanoid** [comment]
先在 https://github.com/leancloud/docs/blob/master/package.json 里加了一些，使用 `grunt release` 会自动更新：

更多说明：https://github.com/leancloud/docs#版本更新

**Comment by sparanoid** [comment]
> 其实还好，对这些情况特别判断一下就行了。 

参考上面的 commit，目前是很简单的通过前端来实现的
