### ISSUE TITLE
待补充：如何查询 1. 数据表中列默认值为 false 的记录 2. 带默认值的新增列的数据

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#584]
https://ticket.leancloud.cn/tickets/7605
用boolean字段做查询条件时，返回结果与预期不符

新添加表列默认值问题
https://ticket.leancloud.cn/tickets/5831

**Comment by shifuchen98** [comment]
Resolved by https://github.com/leancloud/docs/pull/3147 and https://github.com/leancloud/avfr/pull/1742.
