### ISSUE TITLE
[JS 存储 / Python 存储 / .NET 存储]  补充区分云代码调用环境的函数。

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#596]
https://ticket.leancloud.cn/tickets/6115
https://ticket.leancloud.cn/tickets/6806
工单和用户评论都有涉及。

可参考 https://leancloud.cn/docs/ios_os_x_guide.html#区分生产环境调用
iOS、Android、REST API 都有相关内容。

---

**JS 存储**
- 可以补充到 https://leancloud.cn/docs/js_guide.html#云引擎_函数 下面  
-  将标题「云引擎 函数」中间的空格去掉

**Comment by myleslee** [comment]
@wujun4code @aisk @leeyeh

**Comment by wujun4code** [comment]
这个经过发掘， .NET 就没有这个接口。。。下周一发布新版 Unity sdk 会带这个接口。

**Comment by myleslee** [comment]
https://leancloud.cn/docs/leanengine_cloudfunction_guide-python.html#切换云引擎环境
