### ISSUE TITLE
应用内社交重复关注不报错，文档需要更新

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#600]
文档中残留着报错的判断：
https://leancloud.cn/docs/status_system.html#关注_取消关注
应该去掉
if (error.code==kAVErrorDuplicateValue) {
        //重复关注
}

**Comment by myleslee** [comment]
@tang3w 请确认

**Comment by tang3w** [comment]
@nicecui 为什么需要去掉呢，是后端不再支持还是其他原因？

**Comment by killme2008** [comment]
目前重复关注不报错的，就认为关注成功。

2015-10-16 17:33 GMT+08:00 Tianyong Tang <notifications@github.com>:

> @nicecui <https://github.com/nicecui> 为什么需要去掉呢，是后端不再支持还是其他原因？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leancloud/docs/issues/600#issuecomment-148666047>.
>



-- 
庄晓丹
Email:        killme2008@gmail.com xzhuang@avos.com
Site:           http://fnil.net
Twitter:      @killme2008
