### ISSUE TITLE
[JS 存储] 示例代码需要重新审核一遍，并根据用户评论做必要的内容修正

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#609]
示例代码中有错误，比如：
<img width="919" alt="screen shot 2015-10-16 at 11 59 40" src="https://cloud.githubusercontent.com/assets/108758/10604278/e71ec530-7755-11e5-9b5f-c971bfc2d055.png">
应改为：`error: function(error) {`

这个页面上用户评论也比较多，需要整体回复下，并对内容做必要的更正。

**Comment by wujun4code** [comment]
已修改，但是找不到哪个 pr 了。。
