### ISSUE TITLE
JS存储，获取Pointer为文件类型的url时，告诉用户需要在query中加入include方法

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#620]
https://leancloud.cn/docs/js_guide.html#获取文件的内容

我的写法为：
var avatarPhoto = object.get("avatarFile");
var url = avatarPhoto.url();
问题：发现url获取不到。

同时发现有用户也遇到了同样的问题：
https://forum.leancloud.cn/t/js-file-objectid-file-url/3689
https://forum.leancloud.cn/t/jssdk-post-img-file-url/1716

解决方案：
通过query获取object时，应该在query中加入include方法。
例如：
var query = new AV.Query("TestObject");
query.include('avatarFile');
query.get(
//获得object，再获得object中的avatarFile，然后可以通过.url()方法获取url
);

**Comment by wujun4code** [comment]
我来修改吧，这一段很多 sdk 都需要说明。

**Comment by wujun4code** [comment]
但是这个确实是 Pointer 查询的问题，在文件单独介绍一下吧。

**Comment by wujun4code** [comment]
### 文件查询
文件的查询依赖于文件在系统中的关系模型，例如，用户的头像，有一些用户习惯直接在 `_User` 表中直接使用一个 `avatar` 列，然后里面存放着一个 url 指向一个文件的地址，但是，我们更推荐用户使用 Pointer 来关联一个 {{userObjectName}} 和 {{fileObjectName}}，代码如下：

{% block code_user_pointer_file %}

```js
    var data = { base64: '文件的 base64 编码' };
    var avatar = new AV.File('avatar.png', data);
    
    var user = new AV.User();
    var randomUsername = 'Tom';
    user.setUsername(randomUsername)
    user.setPassword('leancloud');
    user.set('avatar',avatar);
    user.signUp().then(function (u){
    });
```
