### ISSUE TITLE
iOS“注册手机号码验证”需要增加requestMobilePhoneVerify的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#622]
requestMobilePhoneVerify这个方法用来重新发送验证手机号的短信。
目前在Android和JS中都有说明，而iOS中没有。

iOS：https://leancloud.cn/docs/ios_os_x_guide.html#手机号码验证

在下面的文档中都有说明：
https://leancloud.cn/docs/js_guide.html#短信验证手机号码
https://leancloud.cn/docs/android_guide.html#手机号码验证

**Comment by myleslee** [comment]
@tang3w 请补充

**Comment by tang3w** [comment]
iOS 文档好像把短信独立出来了，在 https://leancloud.cn/docs/sms_guide-ios.html#注册验证

**Comment by myleslee** [comment]
已补充至新文档： <https://leancloud.cn/docs/sms_guide-ios.html#没收到注册验证短信_>
点击链接后向上一点就是。
