### ISSUE TITLE
JS存储，Collection是否应该去掉？

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#627]
https://leancloud.cn/docs/js_guide.html#Collection
每当去new一个collection时，就会弹出警告：
AV.Collection is deprecated, please don't use it anymore.

**Comment by myleslee** [comment]
@killme2008 应该可以去掉吧？

**Comment by myleslee** [comment]
得到庄神首肯，可以去掉（PR #654）。只是可惜了丰神 @jwfing 曾在此部分示例代码中加入的「李雷和韩梅梅」的例子……
