### ISSUE TITLE
文档配图重构

### ISSUE THREAD

**Issue by myleslee** [leancloud/docs#630]
需要看起来再简洁一些，与整个文档风格匹配。

https://leancloud.cn/docs/rest_sms_api.html#验证码发送逻辑图
![leancloud_sms_sequence](https://cloud.githubusercontent.com/assets/108758/10752212/19374a6c-7cc2-11e5-9798-bf905a80046a.png)

https://leancloud.cn/docs/realtime_v2.html#权限和认证

![leanmessage_signature2](https://cloud.githubusercontent.com/assets/108758/10752211/1922b2be-7cc2-11e5-830e-37753efaf0a2.png)

**Comment by sdjcw** [comment]
LeanEngine 说明 hook 函数时，最好也能配个图，开发者会更容易理解 hook 函数的调用时期。

**Comment by sparanoid** [comment]
嗯，元素扁平抽象一些我觉得就比较好了

**Comment by weakish** [comment]
要不要干脆改成 diagram
