### ISSUE TITLE
Android 聊天「对话添加成员」被邀请者应该收到 onMemberJoined 通知

### ISSUE THREAD

**Issue by leeyeh** [leancloud/docs#634]
https://leancloud.cn/docs/realtime_guide-android.html#添加其他成员

**Comment by myleslee** [comment]
@wujun4code .NET 文档也缺少这个通知，你看 SDK 要不要做相应调整。

**Comment by wujun4code** [comment]
被邀请者也要收到 onMemberJoined  ，他不是收到 onInvited  了么？

**Comment by leeyeh** [comment]
两个都会收到的，https://github.com/leancloud/avoscloud-push/blob/master/push-server/doc/protocol.md#加人

**Comment by myleslee** [comment]
@daweibayu @wujun4code 
这个 issue 还需要开着吗？

**Comment by daweibayu** [comment]
好久远的 issue 了，我明天看一下是否还需要更改

**Comment by weakish** [comment]
[新版 rtm 指南已经有了][doc]

[doc]: https://leancloud.cn/docs/realtime-guide-beginner.html#hash-457342839
