### ISSUE TITLE
iOS / Android SDK 关于实时通信签名部分的文档和代码范例需要更新

### ISSUE THREAD

**Issue by sunng87** [leancloud/docs#639]
- [x] Android SDK 关于签名的代码实例是 v1 版本的，需要更新到 v2
- [ ] Android 的签名部分的文档需要对 `action` 传入的值有明确的说明和介绍
- [ ] iOS 需要对 `action` 可能传入的值做整理（目前列举了 join / invite / kick 可能是 v1 版本的，没有对 session/open 时的 `action` 的说明）

新版本的云代码签名服务器端 https://github.com/leancloud/realtime-messaging-signature-cloudcode 

@wujun4code @lbt05 @tang3w

**Comment by lbt05** [comment]
[Android SDK 关于签名的代码实例是 v1 版本的，需要更新到 v2] 你确定么

**Comment by sunng87** [comment]
@lbt05 

这里几个参数都还是 v1 的

   params.put("watch_ids",watchIds);

   params.put("group_id",convId);
   params.put("group_peer_ids",targetPeerIds);

**Comment by lbt05** [comment]
ok

**Comment by wujun4code** [comment]
目前已更新。
