### ISSUE TITLE
iOS SDK findConversationsWithCallback: 方法卡主线程

### ISSUE THREAD

**Issue by candyan** [leancloud/docs#643]
iOS SDK中：

AVIMConversationQuery 中的 findConversationsWithCallback: 是同步的？

在我调用这个方法时会卡我的主线程。。即使我在外面加了 异步的GCD。。

**Comment by myleslee** [comment]
@nicecui  请帮忙与 @tang3w 确认

**Comment by tang3w** [comment]
的确是这样，这是个 bug，下个版本会修复掉，争取这周发出来。

**Comment by tang3w** [comment]
你好，请问 SDK 的版本号是多少？我们已经在 3.1.3.1 版本修复了。

**Comment by candyan** [comment]
@tang3w 3.1.5.2

**Comment by tang3w** [comment]
你好，我用最新版的 SDK 测试后没有发现卡主线程的现象。虽然我们的 callback 是在主线程回调的，但是查询逻辑都是在后台线程中执行的。你确认是不是 callback 中的逻辑导致了阻塞？

**Comment by candyan** [comment]
@tang3w

 limit 1000

kAVCachePolicyIgnoreCache  和 kAVCachePolicyCacheOnly 时不会卡

kAVCachePolicyNetworkOnly 会卡

你们是不是 save cache的时候在主线程做的？

而且 limit 10 的时候不会感觉卡顿。。可能是因为写数据的量很小

**Comment by tang3w** [comment]
缓存是在另一个后台线程中做的，也不排除是 sqlite 在插表时造成的，要 debug 一下才行。能否把你的 appid、clientId 以及查询语句告诉我一下？

**Comment by candyan** [comment]
app id: 4yzezhrkk0ba1lg4uk8r6mmye9kw313gnrt53ms23hd42ygu

client id: 1

```_conversationQuery = [[AVIMClient defaultClient] conversationQuery];
_conversationQuery.cachePolicy = kAVCachePolicyNetworkOnly;
[_conversationQuery whereKey:kAVIMKeyMember containedIn:@[@"1"];
[_conversationQuery orderByDescending:@"updatedAt"];
_conversationQuery.limit = 1000;
[_conversationQuery findConversationsWithCallback:^(NSArray *objects, NSError *error) {}];
```

@tang3w

**Comment by tang3w** [comment]
已经找到一个会造成阻塞的地方，已经修复，随下个版本发布出来。

**Comment by myleslee** [comment]
@candyan 

SDK 有新版：<https://leancloud.cn/docs/sdk_down.html>，请测试，多谢！

3.1.6.5 发布日期：2015-11-24
修复 conversation 缓存阻塞主线程的问题
修复 client 状态转移的问题

**Comment by myleslee** [comment]
关闭 Issue。如果这个问题还没解决，请移步到论坛：<https://forum.leancloud.cn> 来提交问题，那里的热心用户和我们的工程师会帮助解答。如果购买技术支持，可以提交工单：<https://ticket.leancloud.cn>。
