### ISSUE TITLE
iOS SDK queryMessagesBeforeId:timestamp:limit:callback: 当 前两个参数为 nil 和 0 时 返回数据很奇怪

### ISSUE THREAD

**Issue by candyan** [leancloud/docs#644]
`queryMessagesBeforeId:timestamp:limit:callback:` 前两个参数为 nil  和 0 时

返回结果有时会少一些 message

我的预计结果是和 `queryMessagesFromServerWithLimit:callback` 的 callback 结果一样。

`queryMessagesFromServerWithLimit:callback` 这个接口就完全木有问题（也许。。至少我还没有发现）

具体问题的描述 在 https://forum.leancloud.cn/t/ios/3755/8 这里。。。

是不是跟 你们 sdk 里的 cache 有关？

**Comment by candyan** [comment]
我怀疑其结果跟 `queryMessagesWithLimit:callback` 结果一致。。但上次复现的时候木有试，只试了 `queryMessagesFromServerWithLimit:callback` 接口

**Comment by myleslee** [comment]
@candyan 这里只是处理与文档相关的问题。具体的技术问题，请继续在用户社区里提问。
