### ISSUE TITLE
实时通信总览中的“iOS清除_badge”链接失效

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#646]
https://leancloud.cn/docs/realtime_v2.html#iOS_离线消息推送
其中的：
桌面图标也会有相应的红点 badge，清除 badge 的操作请参考 iOS 推送指南 - 清除 badge。
“ iOS 推送指南 - 清除 badge”链接失效

正确链接是：
https://leancloud.cn/docs/ios_push_guide.html#清除_Badge

**Comment by myleslee** [comment]
Fixed in PR #642
