### ISSUE TITLE
各个文档的 `<title>` 里应该有本篇标题

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#655]
现在全都是「LeanCloud 文档」，不利于浏览器书签以及搜索结果的显示。

**Comment by wujun4code** [comment]
这个在目前的渲染模式下，好像没地方改……
@sparanoid @wangxiao @sunchanglong

**Comment by sparanoid** [comment]
之前私底下和 @sunchanglong 讨论过，我想迁移到 Jekyll 或者 nanoc，你们有没有什么想法？

**Comment by hjiang** [comment]
各种系统和现在比利弊是什么？

**Comment by wujun4code** [comment]
那我写的这么多 md 还能有用么。。。我好悲桑。。

**Comment by hjiang** [comment]
@wujun4code Jekyll 和类似的系统基本都是 Markdown 的，文档本身倒是变化不大。

**Comment by wujun4code** [comment]
好，那我建议最好支持在 md 文档上有一个 特殊的变量，
set  {{html_title}} = "LeanCloud iOS SDK 数据查询指南" 
这样 我们写 md 的时候 就可以 hook 这个变量~

**Comment by hjiang** [comment]
现在的 HTML 是怎么生成的？如果我们能改的话，能不能在文档里找 <h1>xxxx</h1> 然后把中间的内容填到 title 里？

**Comment by hjiang** [comment]
现在的 HTML 是怎么生成的？如果我们能改的话，能不能在文档里找 <h1>xxxx</h1> 然后把中间的内容填到 title 里？

**Comment by sparanoid** [comment]
> 那我写的这么多 md 还能有用么。。。我好悲桑。。

可以用的

> 现在的 HTML 是怎么生成的？如果我们能改的话，能不能在文档里找 `<h1>xxxx</h1>` 然后把中间的内容填到 title 里？

现在的实现是 @sunchanglong 写的，不想大改的话我觉得可以实现一下？

> 各种系统和现在比利弊是什么？

这个说起来比较复杂了，jekyll 我比较熟悉，GtiHub 自己的也有不少项目在用，应用广泛，模板是 Liquid，配合 [front-matter](http://jekyllrb.com/docs/frontmatter/) 非常适合做文档项目；nanoc 上手快，lightweight，和 jekyll 大同小异，但大概两年前做过一个 500 页左右的项目，生成速度明显劣于 jekyll，现在的情况未知，[developer.github.com](http://developer.github.com) 就是 nanoc 做的

做迁移的问题就是我们现在的文档项目结构比较复杂，有几个文档还是根据自定义模版生成的，另外加上我们自制的评论系统，改动可能会比较大
