### ISSUE TITLE
云引擎文档没有说明本地文件系统只有 `/tmp` 可写

### ISSUE THREAD

**Issue by hjiang** [leancloud/docs#656]

**Comment by sdjcw** [comment]
这个限制会在将来发布的新版本中移除。后续使用 image 来部署应用，将开放写权限。
新版本预计半个月之后上线。

**Comment by sdjcw** [comment]
现在不开放是因为代码目录是在中央存储，允许写临时文件容易污染这个空间。

**Comment by hjiang** [comment]
但这个是不是本来也不该开发，避免用户在实例里保存状态。

**Comment by sdjcw** [comment]
用户使用新版部署就可以向本地磁盘写数据了，同样我们需要在文档里明确说明本地磁盘不能作为持久化存储使用，每次部署都会清空。

用户用本地磁盘可能是自己临时生成的缓存，这类使用我们也不反对。
