### ISSUE TITLE
Update syntax highlighting theme

### ISSUE THREAD

**Issue by sparanoid** [leancloud/docs#667]
Try https://github.com/sparanoid/almace-scaffolding/blob/master/_app/assets/themes/curtana/_less/module-syntax.less

**Comment by myleslee** [comment]
怎么看效果？

**Comment by sparanoid** [comment]
@myleslee 类似 http://sparanoid.com/lab/amsf/syntax-highlighting.html

我发现这边的语法高亮的库比较挫，CSS class 是不一样的，有时间仔细看下

**Comment by weakish** [comment]
Close as this issue is out of date. Feel free to open a new issue for new syntax highlight theme ideas.
