### ISSUE TITLE
JS ACL文档，最后的云引擎ACL链接失效

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#679]
https://leancloud.cn/docs/acl_guide-js.html#最佳实践

整片文档最后一句话中：
云引擎 Hook 函数使用 ACL链接失效，应该为：https://leancloud.cn/docs/acl_guide_leanengine.html

**Comment by wujun4code** [comment]
我错误的使用了/这个符号…明天修复

发送自 Outlook<http://aka.ms/Ox5hz3> for Android on iPhone 18




On Thu, Nov 5, 2015 at 4:07 AM -0800, "Cui Yiran" <notifications@github.com<mailto:notifications@github.com>> wrote:


https://leancloud.cn/docs/acl_guide-js.html#最佳实践<https://leancloud.cn/docs/acl_guide-js.html#%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5>

整片文档最后一句话中：
云引擎 Hook 函数使用 ACL链接失效，应该为：https://leancloud.cn/docs/acl_guide_leanengine.html

―

**Comment by myleslee** [comment]
PR #665 已修复，忘了及时发布。已上线。
