### ISSUE TITLE
Android消息推送，App被用户从后台杀掉后收不到推送的情况，需要说明一下。

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#686]
如果Android中的App被用户从后台中杀掉，会收不到我们的推送，这个是Android自身的机制造成的。现在针对这个问题，已经有不少用户提过工单，所有有必要向用户说明一下原因以及我们做出的努力。

用户提过的相关工单及论坛：
https://forum.leancloud.cn/t/android-leancloud/3292
https://ticket.leancloud.cn/tickets/5752
https://ticket.leancloud.cn/tickets/8346
https://ticket.leancloud.cn/tickets/8602
https://ticket.leancloud.cn/tickets/8221

Android消息推送文档链接：
https://leancloud.cn/docs/android_push_guide.html

**Comment by myleslee** [comment]
https://leancloud.cn/docs/faq.html#Android_应用进程被杀掉后无法收到推送消息

Closed by #1046
