### ISSUE TITLE
新文档：统计分析服务总览

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#691]
建议新起一篇指南，`统计分析服务总览`。内容包含常见指标含义，事件漏斗、用户群分析，常见问题等。

已经有了用户群分析指南，https://leancloud.cn/docs/user_groups.html
事件漏斗，目前只有在一篇博客上介绍了一下，这部分内容需要加到文档来。https://blog.leancloud.cn/651/

常见问题，搜索工单和论坛，应该很容易找到不少。

友商的统计界面，网站体验应该是差于我们的，但友商的文档很详尽。对留存率、活跃度等，如何利用这些指标，都有详尽的介绍。

目前文档里仅有各平台 SDK 的 API 使用以及用户群分析指南，是不够的。

@hjiang @jwfing @wujun4code @myleslee

**Comment by wujun4code** [comment]
这个我没意见，我建议@智维 你来写吧，@广成来 review 里面的内容是否表述正确，@达叔 和 我来审核文字内容，这件事情优先级不高，但是你可以自己拍一下日程表，而且十分建议模板化，配合 SDK 代码解释会更好。


On Nov 9, 2015, at 11:41, lzwjava <notifications@github.com<mailto:notifications@github.com>> wrote:


建议新起一篇指南，统计分析服务总览。内容包含常见指标含义，事件漏斗、用户群分析，常见问题等。

已经有了用户群分析指南，https://leancloud.cn/docs/user_groups.html
事件漏斗，目前只有在一篇博客上介绍了一下，这部分内容需要加到文档来。https://blog.leancloud.cn/651/

常见问题，搜索工单和论坛，应该很容易找到不少。

友商的统计界面，网站体验应该是差于我们的，但友商的文档很详尽。对留存率、活跃度等，如何利用这些指标，都有详尽的介绍。

目前文档里仅有各平台 SDK 的 API 使用以及用户群分析指南，是不够的。

@hjiang<https://github.com/hjiang> @jwfing<https://github.com/jwfing> @wujun4code<https://github.com/wujun4code> @myleslee<https://github.com/myleslee>
