### ISSUE TITLE
iOS离线消息推送，增加如何自定义消息内容的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#705]
#### 背景：
iOS上有离线消息推送的功能：
https://leancloud.cn/docs/realtime_guide-ios.html#启用离线消息推送

#### 用户遇到的问题：
iOS默认离线消息推送，内容是固定的，例如“您有一条离线消息”，无法做到直接显示用户的消息内容。
如果想要直接显示用户的消息内容，该怎么做呢？

#### 问题出现频率较高：
https://forum.leancloud.cn/t/ios/2677
https://ticket.leancloud.cn/tickets/7581
https://ticket.leancloud.cn/tickets/6731
https://ticket.leancloud.cn/tickets/8665
https://ticket.leancloud.cn/tickets/6626
https://ticket.leancloud.cn/tickets/6066
等等，外加我曾在QQ上遇到的用户一人

#### 问题解决方案：
需要结合云函数来一起实现此功能。
在云函数中定义一个_receiversOffline的函数，在函数中返回相应的内容。当存在离线用户时，此函数会自动被调用。

示例代码如下：

```
AV.Cloud.define('_receiversOffline', function(request, response) {
    var params = request.params;

    var json = {
        badge: "1",
        sound: "default",
        _profile: "dev",
        alert:params.content
    };

    var pushMessage = JSON.stringify(json);

    response.success({"pushMessage": pushMessage});
})
```

**Comment by ylgrgyq** [comment]
这里实际上应该看这个文档：https://leancloud.cn/docs/realtime_v2.html#离线推送通知
在这里说明了如何设置默认的推送消息，如何使用自定义的推送消息。但因为对云引擎 hook 的介绍在它下面，所以这里只是提了 _receiversOffline 但未提供具体使用方法，得跳到下面的云引擎 hook 那块看。

**Comment by nicecui** [comment]
嗯，现在的问题是，这样寻找太麻烦了，用户自己顺利全部找到的概率太低了，而且一部分人也不会写代码。
