### ISSUE TITLE
使用Python脚本进行用户注册，出现[600] 无效的短信签名。错误

### ISSUE THREAD

**Issue by DeanChensj** [leancloud/docs#710]
使用的是python的API
注册的过程大致如下，想用脚本随机生成一些假用户。
  user = User()
  user.set("username", username)
  user.set("password", "123456")
  user.set("mobilePhoneNumber", username)
  user.sign_up()
报错在sign_up()这一步， 数据库里确实增加了数据，但是注册似乎没有成功，这是为什么呢？

**Comment by myleslee** [comment]
在我们的文档站点搜索：`[600] 无效的短信签名`，可以找到：<https://leancloud.cn/docs/error_code.html#_600>

如果仍有问题，请到论坛（https://forum.leancloud.cn）里来提交问题，那里的热心用户和我们的工程师会帮助您解答。如果买了技术支持，可以提交工单（https://ticket.leancloud.cn）。

**Comment by DeanChensj** [comment]
您好..我之前就看了这个链接，但是，并没有提供解决方案呀..注册的过程中并没有涉及短信

**Comment by hjiang** [comment]
你的应用名是什么？是不是包含了短信签名里不允许的字符？最好到论坛或工单系统提问，因为这本身不是文档的问题。

**Comment by DeanChensj** [comment]
应用名：crowdsensing  短信签名是在用户注册的时候发生的么？ 我发现问题出在我自己设置了mobilePhoneNumber? 这一步会产生什么问题？

**Comment by hjiang** [comment]
`user.set("mobilePhoneNumber", username)` 你代码确实是这样写的吗？我们服务端会做号码格式检查，可能是这个问题。

**Comment by DeanChensj** [comment]
是的，我改成了先注册然后再设置的方法，可以正常工作了，大概我自己生成的电话号码并不符合条件吧。但是注册之后系统不会检查，谢谢~

**Comment by myleslee** [comment]
@DeanChensj 
>您好..我之前就看了这个链接，但是，并没有提供解决方案呀..注册的过程中并没有涉及短信

注册过程是否涉及短信，在后台里有选项来决定。请检查：控制台 >  选择 crowdsensing
 应用 > 设置 > 应用选项 > 短信：

<img width="199" alt="screen shot 2015-11-13 at 14 23 00" src="https://cloud.githubusercontent.com/assets/108758/11140149/2f589118-8a12-11e5-9b63-7a914bc35a05.png">

如果 **验证注册用户手机号码** 处于选中状态，那么使用 `user.set("mobilePhoneNumber", username)` 就会触发短信。

根据 <https://leancloud.cn/docs/error_code.html#_600> 的提示：
>……并且限制在 10（包含 10 个字符）个字符内。
>`要想默认发送的短信签名使用的是应用名称，应用名称可以在应用设置里修改。短信自定义模板可以在模板里自定义签名。`

你的应用名称「crowdsensing」为 12 个字符，超出了 10 个字符的限制，所以会收到 600 的错误。

**Comment by myleslee** [comment]
@DeanChensj，接上面。

你的应用名称「crowdsensing」为 12 个字符，超出了 10 个字符，如果此时：

- **验证注册用户手机号码** 为选中

这时，系统将默认使用 【crowdsensing】做为签名，因为超限，系统会产生 600 的错误。

而去掉 `user.set("mobilePhoneNumber", username)` 代码就不会触发短信，所以系统不会再报错，数据得以成功保存。

`sign_up()` 之后再去保存 mobilePhoneNumber，肯定是可以保存。但请检查一下 `_User` 表中列 `mobilePhoneVerified`，此时应该是 false，因为 600 的错误，验证短信并未成功发送，用户没有输入验证码来确认，mobilePhoneVerified 就不会变为 true。

`mobilePhoneNumber` 为 11 位数字，格式很好修正。但要想成功接收到验证短信，完成完整的注册流程，就要修复 600 的错误，那根据文档提示，这里有两种选择：

- **应用名称可以在应用设置里修改。**（&check;）<br/>
  进入 **控制台** > 选择 crowdsensing > **设置** > **基本信息** > **应用名称** 来修正，如 `crowd`。
- **短信自定义模板可以在模板里自定义签名。**<br/>
  在自创建的模板中指定一个合法的签名，如`【crowd】`。<br/>
  但是在 signIn 注册环节，我们不支持调用自定义模板，其他要发短信的场景里可以调用。

因此目前的解决方案只能修改应用名称，或取消 **验证注册用户手机号码** 选项，不对手机号码进行验证。

我们将来会在控制台增加选项来让注册环节也可以使用自定义的短信签名。谢谢！
