### ISSUE TITLE
数据存储API请求数的说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#715]
#### 问题
每个开发者账户每月享有 100 万次免费请求，但是有一些用户对具体的API接口有疑问，例如
saveall，deleteall，fetchall是算一次请求，还是多次请求？

#### 相关的论坛及工单问题：
https://forum.leancloud.cn/t/avobject-delete-all/2813
https://ticket.leancloud.cn/tickets/6171
https://forum.leancloud.cn/t/topic/3611/4

#### 问题答案：
saveall算多次请求。例如：调用一次saveall 保存 array 里面 100 条记录的内容，算 100 次 API 请求。
deleteall算一次请求。例如：调用 find/deleteall 查找/删除 500 条记录，只算一次 API 请求。
fetchall算多次请求。例如：调用一次fetchall获取array 里面100个对象，算100次API请求。

#### 放置位置
我的想法是可以放到这里：
https://leancloud.cn/docs/faq.html#API_相关

**Comment by Veeson** [comment]
请问如果请求添加数据失败的话也计算一次请求吗？

**Comment by myleslee** [comment]
@Veeson 
如果失败的原因是 [应用流控限制 error code 429](https://leancloud.cn/docs/error_code.html#_429) 请求被云端拒绝，就不算一次请求。

若是其他原因，例如 [权限 error code 430](https://leancloud.cn/docs/error_code.html#_403) 就算一次请求。

文档稍后也会更新。
