### ISSUE TITLE
增加聊天室作为 pubsub 场景的使用说明

### ISSUE THREAD

**Issue by sunng87** [leancloud/docs#756]
实时通信聊天室可以用到普通的 pubsub 场景，但是大部分用户想不到，我们需要在文档上说明

**Comment by leeyeh** [comment]
现在如果我想实现类似 github web 页面上基于 pub / sub 的通知功能，那么每个 tab 都是一个 subscriber，这时候 subscriber 其实是不需要持久化的。

基于推送协议来做是比较自然的方式，但是每个页面订阅的 channel 是不同的，会产生大量的 installation。如果基于聊天来做，那么引入了 conversation、client、message 等概念与 pub / sub 中的概念还是有一定区别的。

不知道有没有更好的方案。

**Comment by weakish** [comment]
这个感觉比较魔法，先关掉了。
