### ISSUE TITLE
补充 AV.Object.extend() 只能用在全局变量的说明

### ISSUE THREAD

**Issue by lzwjava** [leancloud/docs#78]
JS 保存保量一节

var GameScore = AV.Object.extend("GameScore");
var gameScore = new GameScore();
gameScore.set("score", 1337);
gameScore.set("playerName", "Sean Plott");
gameScore.set("cheatMode", false);

开发者很容易在局部变量使用，造成栈溢出。

**Comment by sdjcw** [comment]
https://leancloud.cn/docs/js_guide.html#avobject
这里其实有描述，不过可能不够明显，有什么更好的办法吗？

**Comment by killme2008** [comment]
首先我们自己的例子都改过来吧， js 指南里比较多这样 的例子，都可以改成

```javacript
var gameScore = new GameScore();
gameScore.set("score", 1337);
gameScore.set("playerName", "Sean Plott");
gameScore.set("cheatMode", false);
```

**Comment by sdjcw** [comment]
我提交了 RP: https://github.com/leancloud/docs/pull/81
