### ISSUE TITLE
云函数需要补充反序列化的示例

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#803]
参见：https://forum.leancloud.cn/t/json-class/4900/2

@leeyeh

**Comment by wujun4code** [comment]
这个会在云引擎文档中进行详细描述。

**Comment by leeyeh** [comment]
这个跟云函数没啥关系，是 JS SDK 的 API。

**Comment by wujun4code** [comment]
但是在 leanengine 文档里面得有一个连接过去，因为确实很多人在使用 cloud function 的时候需要注意这个问题。

**Comment by wujun4code** [comment]
目前 AVObject to JSON 和 JSON to AVObject 的 API 还没开放出去，暂时不提这个吧，我们开放了 API 再说。

**Comment by leeyeh** [comment]
3.0 开放了：https://github.com/leancloud/javascript-sdk/blob/master/changelog.md#300-2017-06-16

**Comment by BinaryHB** [comment]
先关了。没什么用户对这个有疑问。
