### ISSUE TITLE
需要在 SDK 登录代码处提示：频繁错误登录，会锁定账号

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#811]
目前，后台 REST API 所制定的规则是 15 分钟最多 6 次错误登录。

请在相关地方，进行提示。

**Comment by myleslee** [comment]
- 登录失败有错误状态码吗？
- 账号锁定后，_User 表里会有标记吗？怎么解锁？
- 对云引擎登录也适用吧？

**Comment by BinaryHB** [comment]
1) 错误码："code":1,"error":"登录失败次数超过限制，请稍候再试，或者通过忘记密码重设密码。"

2) 无标记，后台自己处理。15 分钟后自动解锁，如果再次尝试错误登录，锁定时间会后延 15 分钟。

3) 云引擎登录调用 REST API，同样受到这个限制。

**Comment by wujun4code** [comment]
我来加一下。这个还是比较重要的。
