### ISSUE TITLE
定时器数量，环境说明有误

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#877]
来源：
https://ticket.leancloud.cn/tickets/9252

https://leancloud.cn/docs/leanengine_guide-node.html#定时器数量
https://leancloud.cn/docs/leanengine_guide-python.html#定时器数量
“开发环境和测试环境的定时器数量都限制在 3 个以内”
应该修改为
“生产环境和测试环境的定时器数量都限制在 3 个以内”

**Comment by nicecui** [comment]
@sdjcw 请确认

**Comment by sdjcw** [comment]
“生产环境和预备环境的定时器数量都限制在 3 个以内”

以后测试环境都建议改叫 预备环境，因为域名是 stg-xxx.leanapp.cn， stg 是 staging 的缩写。
