### ISSUE TITLE
error_code.md里面的 iOS 的 AVConstants 链接失效

### ISSUE THREAD

**Issue by ChenYilong** [leancloud/docs#892]
文件：

docs/md/error_code.md

失效的链接：

iOS 的 AVConstants。

@leancloud/docs-editor

**Comment by myleslee** [comment]
@tang3w @jwfing 
在 <https://leancloud.cn/api-docs/iOS/index.html> 中是找不到 AVConstants 了

主文档：<https://leancloud.cn/docs/error_code.html>

**Comment by tang3w** [comment]
已经加上了。

**Comment by myleslee** [comment]
![screen shot 2016-01-19 at 13 22 12](https://cloud.githubusercontent.com/assets/108758/12410402/b67c7c3c-beaf-11e5-8903-347d9e346132.png)

`https://leancloud.cn/api-docs/iOS/docs/index.html#/c/data/kAVErrorAccountAlreadyLinked`

点了就是 404。其实是在同一页面内的跳转，能修复吗？@tang3w

**Comment by tang3w** [comment]
已修复链接 404 的问题。@myleslee

**Comment by myleslee** [comment]
:+1:
