### ISSUE TITLE
暂态对话不支持 踢出成员操作

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#899]
https://leancloud.cn/docs/realtime_v2.html#暂态对话_Transient_Conversation_

```
这是专门用来处理「聊天室」这种需求的。与普通对话一样，它也支持创建、加入/踢出成员等操作
```
修改为
```
这是专门用来处理「聊天室」这种需求的。与普通对话一样，它支持创建、自身主动加入、自身主动退出会话等操作，但不支持邀请加入、踢出成员这两个操作。
```

**Comment by myleslee** [comment]
你可能看的是缓存版。新版就是这样，只不过「不支持」放入了列表中：

<img width="888" alt="screen shot 2016-02-24 at 10 28 02" src="https://cloud.githubusercontent.com/assets/108758/13273828/5ee9492a-dae1-11e5-944b-ff7b1e208719.png">
