### ISSUE TITLE
定时器，增加错误说明

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#901]
相关链接：
https://leancloud.cn/docs/leanengine_guide-node.html#定时任务

问题来源：
https://forum.leancloud.cn/t/leancloud/5648/2

解决方案：
在定时任务处增加一个模块：「错误信息说明」

###### timerAction timed-out and no fallback available.
指你的某个定时器触发的 cloud 函数 15 秒都没有响应。

###### timerAction short-circuited and no fallback available
指你的某个定时器触发的 cloud 函数因为太多次超时而停止触发。

**Comment by nicecui** [comment]
@sdjcw

**Comment by sdjcw** [comment]
我没有问题。
