### ISSUE TITLE
iOS 推送证书补充说明如何配置项目

### ISSUE THREAD

**Issue by killme2008** [leancloud/docs#91]
@ufosky 这个可以参考 parse

https://parse.com/tutorials/ios-push-notifications 第四步。

**Comment by myleslee** [comment]
@ChenYilong @tang3w 文档需要加入这部分吗？
https://github.com/ParsePlatform/PushTutorial/tree/master/iOS#4-configuring-a-push-enabled-application

**Comment by ChenYilong** [comment]
嗯，可以考虑参考完善下。我来调整下。

**Comment by myleslee** [comment]
@ChenYilong 坐等 PR

**Comment by weakish** [comment]
[现文档已包含相关内容](https://leancloud.cn/docs/ios_push_cert.html)
