### ISSUE TITLE
使用 JS 的 signUpOrlogInWithMobilePhone 方法注册用户，可以不提供密码？

### ISSUE THREAD

**Issue by DIYgod** [leancloud/docs#950]
我试过了使用 signUpOrlogInWithMobilePhone 不提供密码是可以注册的，但文档中说用户的密码是必须提供的，是 bug 还是 feature？

如果是 feature，那么是不是用这种方式注册的用户只能用手机登录？

**Comment by leeyeh** [comment]
signUpOrlogInWithMobilePhone 相关的文档是这样写的： https://github.com/leancloud/docs/blob/master/md/js_guide.md#手机号码一键登录

并没有看到有关「密码是必须提供的」的描述

**Comment by killme2008** [comment]
如果没有提供 password，默认会随机生成一个，如果后续还想使用密码登陆，可以登陆后自行修改密码。

在 2016年2月15日 上午10:50，Lee Yeh <notifications@github.com>写道：

> signUpOrlogInWithMobilePhone 相关的文档是这样写的：
> https://github.com/leancloud/docs/blob/master/md/js_guide.md#手机号码一键登录
>
> 并没有看到有关「密码是必须提供的」的描述
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leancloud/docs/issues/950#issuecomment-184037089>.
>



-- 
庄晓丹
Email:        killme2008@gmail.com xzhuang@avos.com
Site:           http://fnil.net
Twitter:      @killme2008

**Comment by leeyeh** [comment]
此外，这个仓库的 issue 是用来反馈文档相关的问题，对于服务与 SDK 的功能问题欢迎到论坛（https://forum.leancloud.cn）反馈，谢谢支持。

**Comment by myleslee** [comment]
@killme2008  也就是说有两种选择：
1. 用户每次登录（没有缓存到本地）都可以使用短信验证码来完成，前提是打开了以下选项：
  <img width="342" alt="screen shot 2016-02-15 at 10 55 29" src="https://cloud.githubusercontent.com/assets/108758/13038800/af3beb96-d3d2-11e5-8b95-dd96901f6e97.png">
2. 使用验证码成功登录后，修改密码，下次就可以使用「手机号+密码」方式登录。

**Comment by myleslee** [comment]
@leeyeh 这次文档应该也是需要修改。稍后我会补充。

**Comment by DIYgod** [comment]
懂了，谢谢大家~

@leeyeh 这次也有文档没写清楚的原因😂
