### ISSUE TITLE
控制台使用指南需要重构

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#959]

**Comment by myleslee** [comment]
我在想有些必要的、短小的介绍还是放在界面里更直观，链接到文档也会降低用户体验。如 Parse：

<img width="712" alt="screen shot 2016-03-04 at 00 05 23" src="https://cloud.githubusercontent.com/assets/108758/13500570/15936986-e19e-11e5-9c02-f5d254d8dfec.png">

或者鼠标悬浮查看：

<img width="860" alt="screen shot 2016-03-04 at 00 06 00" src="https://cloud.githubusercontent.com/assets/108758/13500589/2aa40358-e19e-11e5-97de-79544ad40913.png">

**Comment by jwfing** [comment]
是的，字面释义式的说明就不要写在文档里了，我想总体说一下控制台可以干什么，做一件具体的事情该去哪里操作，诸如此类的操作指南。
