### ISSUE TITLE
[优先级低]计费和支付需要说明。

### ISSUE THREAD

**Issue by jwfing** [leancloud/docs#960]

**Comment by wujun4code** [comment]
请明示，哪个页面？

**Comment by qinyuhang** [comment]
https://leancloud.cn/docs/leanengine_plan.html#价格
这个页面的最下面写到：
“资源使用数量按当天最大资源占用计算。假设某天从 0 点至 23:59 分之间：
......
则当天费用按照 8 个基本资源计算。”
我想请问一下如何扩容某一个实例的基本资源？是用户手动操作？（如果是请问一下在哪里手动操作）如果是系统自动伸缩，请问有设置开关或者提示吗？

**Comment by myleslee** [comment]
@qinyuhang，感谢反馈。文档已补充：
>我想请问一下如何扩容某一个实例的基本资源？是用户手动操作？（如果是请问一下在哪里手动操作）如果是系统自动伸缩，请问有设置开关或者提示吗？

https://leancloud.cn/docs/leanengine_plan.html#调整实例规格
https://leancloud.cn/docs/leanengine_plan.html#增加实例
