### ISSUE TITLE
增加 Python 的批量操作接口

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#967]
问题来源：
https://forum.leancloud.cn/t/python-sdk-destroy-all/6345

文档位置：
https://leancloud.cn/docs/python_guide.html#删除对象

增加以下内容：
---------------------------- 文档正文 --------------------------------
批量删除实例可以通过  leancloud.Object.destroy_all() 方法
```
objects = [obj1, obj2, obj3]
leancloud.Object.destroy_all(objects)
```

请 @aisk Review 是否正确

**Comment by aisk** [comment]
LGTM :+1:
