### ISSUE TITLE
快速入门，JavaScript sdk，增加使用美国节点的方法

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#971]
问题详情：
快速入门里没有说明使用美国节点的方法

问题来源：
https://forum.leancloud.cn/t/us-leancloud/6357

文档位置：
https://leancloud.cn/docs/start.html
选择 JavaScript

解决方案：
在这段话下面增加使用美国节点的方法：

进行代码初始化，加入这行代码后，就可以创建 class 或任何其他操作了。想要跟进最新功能，可以到官方的 GitHub Repo 。
AV.initialize('bkaTfiY3Nc2jLJW7hXRmoFiK', 'FkooEOxbmkmSnlEvTjxPFEiy');
// 初始化 param1：应用 id、param2：应用 key

---------------------------- 文档正文 -------------------------------
```
// 初始化 param1：应用 id、param2：应用 key
AV.initialize('bkaTfiY3Nc2jLJW7hXRmoFiK', 'FkooEOxbmkmSnlEvTjxPFEiy');
// 如果要使用美国节点，请取消下方的代码注释
// AV.useAVCloudUS();
```

请 @wangxiao 看下代码是否正确

**Comment by wangxiao** [comment]
恩，是这样的。
