### ISSUE TITLE
美国节点下 Android setup 文档未更新

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/docs#973]
美国节点：https://us.leancloud.cn/docs/sdk_setup-android.html#Android_Studio

大陆节点：https://leancloud.cn/docs/sdk_setup-android.html#Android_Studio

```
dependencies {
    compile 'com.android.support:support-v4:21.0.3'

    //avoscloud-sdk 为 LeanCloud基础包
    compile 'cn.leancloud.android:avoscloud-sdk:v3.+'

   ...

}
```

以大陆节点为准，gradle 这个自动下载 SDK 的配置很重要，如果错了，会导致项目无法运行。

另外，这个文档模版不是 2 个节点共用的吧？

**Comment by myleslee** [comment]
大陆节点部署后，直接复制到美国节点。所以两个节点使用的文档都还是一套源。

昨天重新发布了一下，刚才检查美国文档已经同步了。有时会是浏览器缓存的问题，要强刷新一下。
