### ISSUE TITLE
如何通过 js api 实现登陆和注册呢？

### ISSUE THREAD

**Issue by dotku** [leancloud/docs#980]
所谓的 JavaScript 实际上是 NodeJS 的实现呀－－～？

**Comment by myleslee** [comment]
请参考文档：
JavaScript 数据存储开发指南 / 用户 /
- <https://leancloud.cn/docs/js_guide.html#注册>
- <https://leancloud.cn/docs/js_guide.html#登录>

后续问题可以前往 [用户社区](https://forum.leancloud.cn) 进行提问。
