### ISSUE TITLE
新的 iOS 文档，文件 缺少关联到 AVObject 及其他内容

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#983]
关联到 AVObject 如下图所示：
![image](https://cloud.githubusercontent.com/assets/10130959/13420989/c7313fcc-dfc5-11e5-9990-db558f6d551b.png)

同时还缺少「图像」「图像的缩略图」「文件元数据」「删除」「清除缓存」
https://leancloud.cn/docs/ios_os_x_guide.html#图像
https://leancloud.cn/docs/ios_os_x_guide.html#得到图像的缩略图
https://leancloud.cn/docs/ios_os_x_guide.html#文件元数据
https://leancloud.cn/docs/ios_os_x_guide.html#删除
https://leancloud.cn/docs/ios_os_x_guide.html#清除缓存

**Comment by wujun4code** [comment]
达叔已经加上了。。
